### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#10]
I'm currently working to add support for initializing a working environment in Docker. This will make it easier for people to contribute and will allow users to get started more quickly.

Will also add instructions in the readme.

**Comment by pierotofy** [comment]
Done

**Comment by vesnikos** [comment]
You should consider making the database spacially aware by the postgis extension for the database. That way spatial informations can be added at the models and querry can be made on them.

**Comment by pierotofy** [comment]
Yup! I haven't added postgis yet because there's currently no geospatial code, but it will be included as soon as we have some code that needs it!
