### ISSUE TITLE
WebODM hanging up

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#100]
While running a task on 38 images WebODM seem so be stuck in a loop.  Says its unable to close temp stats file.  The attached message from Docker repeated several times while trying to execute [ROOT_HAHOG] on one of the images in WebODM (see attached below).

![root_hahog_error](https://cloud.githubusercontent.com/assets/25381671/22856676/ecef0e40-f05b-11e6-8e67-9cb969d3f1cd.JPG)

I restarted Docker then my physical machine.  Restarted Docker and WebODM now receiving the following error at the bottom (could not translate host name 'db'):

![webodm_django_db_error](https://cloud.githubusercontent.com/assets/25381671/22856694/6e7bf4aa-f05c-11e6-90c4-d72cdff684f4.JPG)

As always, Thanks for the help.

**Comment by pierotofy** [comment]
Looks like you are running out of space! Make sure you have enough disk space.

**Comment by AnthonyCoughlin** [comment]
I don't believe this is the case (see screenshot below), or am I looking in the wrong place??

![webodm_space_error](https://cloud.githubusercontent.com/assets/25381671/22856991/55e9db54-f062-11e6-9909-5a8dba34056b.JPG)


I just wiped the WebODM folder again, cloned and upon updating got this error (see attached below).
.  I'm going to delete the folder and restart my machine again.  I'm getting close to uninstalling Docker and reinstalling.  I'll keep you updated.

![webodm_update_error2](https://cloud.githubusercontent.com/assets/25381671/22856992/670a68ea-f062-11e6-9f56-f80c5eac1e4c.JPG)

@pierotofy, can't thank you enough for the quick responses!

**Comment by AnthonyCoughlin** [comment]
Uninstalled Docker, restarted machine, and reinstalled Docker.  Deleted entire existing WebODM dir and recloned.  Ran WebODM update.  Back up and running.  Testing the same data set.  I'll keep you up to date.  Thanks again for the help.

**Comment by AnthonyCoughlin** [comment]
Everything seems to be running fine with regard to WebODM starting now.  However, I'm experiencing a new error: 'refinePatchPFGS failed'.  I'm going to start a new issue.
