### ISSUE TITLE
Feature Suggestion:  Report File Upload progress to clients/log

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1004]
I think it'd be amazing if NodeODM would report the progress of file/data upload to the connected clients (WebODM) as well as the log output, so that the end-user is apprised of exactly what image out of what image is being uploaded, when each image completes (an idea of how long it is taking per image), and the rough progress of this part of the process. I envision this looking/working similarly to how Drone.DB handles the reporting of Uploaded data when using the Hubs.

**Comment by pierotofy** [comment]
No bandwidth for this.
