### ISSUE TITLE
Can't upload the model from the Agisoft

### ISSUE THREAD

**Issue by marshallexperiment** [OpenDroneMap/WebODM#1008]
****************************************

### What's your browser and operating system? 

https://whatismybrowser.com/w/FQGRS44

### What is the problem?

I can't upload my models (DSM, DTM, Orthophoto, Point Cloud, and 3D Models) from the Agisoft rendering result.

### What should be the expected behavior?

I can view all my models in the Web Browser.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Please somebody help me how to import the model and can be visualized to WebODM. I've shared the link on below.
Link: https://dubox.com/s/1cD6Ss0KU3bTeCBapIgvrJw

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
