### ISSUE TITLE
incorrect Diagnostic page <title> 

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/WebODM#1014]
### What's your browser and operating system?
 
Chrome 91 on macOS (Catalina)

### What is the problem?

Pages appear to all have descriptive titles, except for the Diagnostic page which has `<title>Login - WebODM</title>`

<img width="659" alt="Screen Shot 2021-07-07 at 11 43 12 AM" src="https://user-images.githubusercontent.com/4806884/124789900-aecfdf80-df18-11eb-9449-ced3f5814076.png">

### What should be the expected behavior?

Page title should be descriptive 
(e.g. `<title>Dashboard - WebODM</title>` or `<title>Lightning Network - WebODM</title>`)

### How can we reproduce this? 

Check the page title in the browser tab when navigating to the Diagnostic page

**Comment by Saijin-Naib** [comment]
I tried to figure this out and got so lost!

Thanks for raising it.
