### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#102]
It would facilitate adoption if there were Python bindings to access the API.

**Comment by rmallermartins** [comment]
I'm thinking about creating a Python Client (for accessing and using the api) for WebODM. And even a Django Package after that, with Login and Host configuration in the settings.

Help would be appreciated, if anyone is interested :)

**Comment by pierotofy** [comment]
This would be awesome. I'd be happy to help (answering questions about the API, reviewing code, testing, providing feedback).

**Comment by rmallermartins** [comment]
@pierotofy would you be willing to create the project inside OpenDroneMap organization in github, or should I start it under my own?

**Comment by pierotofy** [comment]
@smathermather would be the right person to answer this.

**Comment by rmallermartins** [comment]
I created it in my own so I could start developing: https://github.com/rmallermartins/python-WebODM. @pierotofy I already have some questions about the API, should I ask them here?

**Comment by pierotofy** [comment]
Awesome. Yes you can ask here!

**Comment by rmallermartins** [comment]
Nice, will start with some then :)

**1. Are there Endpoints to retrieve, for example, one Project like "GET /api/projects/{id}"?** _I don't see any in docs, just listing with filters_
**2. Do Create, Update, Delete, etc... have json content on responses?** _Like Create returning the created Project fields, not well documented too_
**3. What the API returns when my auth Token has expired?**
**4. Is there a pattern for returning errors?** _Like both "required" and "Unable to login" returns with status_code 400. If it is the only code that return errors with, and if theses errors have some kind of pattern, or it depends on each API point?_

Ps: sorry if my English is rusty

**Comment by pierotofy** [comment]
@rmallermarmartinis We've forked your repo to https://github.com/OpenDroneMap/python-WebODM. If you want to make the OpenDroneMap repo the official repo, simply destroy (via the settings panel) your repository. You should have received commit permissions to do changes directly to the OpenDroneMap repository.

**Comment by rmallermartins** [comment]
@pierotofy Nice, already did that! Yes, I received permissions from @dakotabenjamin

**Comment by rmallermartins** [comment]
Guys, 2 problems.

1. Since the repo changed, Travis and Pyup stopped working and I don't have admin access to enable the process with my account.
2. I think Issues are disabled in the repo, could someone enable it? So we can start using the projects issues for this kind of thing ;)

**Comment by pierotofy** [comment]
1. I've enabled a travis build for that repo. I'm not too familiar with pyup, so I haven't done anything there yet. @dakotabenjamin would it be possible to grant @rmallermartins the permissions he needs to setup pyup?
2. I've enabled issues, they should be OK now.

Thanks!

**Comment by pierotofy** [comment]
Closing due to lack of interest / PyODM seems the better way to go forward as far as Python support is concerned.
