### ISSUE TITLE
WebODM georeferencing and stitching lead to random pixel data

### ISSUE THREAD

**Issue by ivan-work-account** [OpenDroneMap/WebODM#1029]
### What's your browser and operating system?
Chrome 92 on Windows 10.
The issue happens on Chromium on Ubuntu 18.04, too.

### What is the problem?
I have a bunch of orthoimages (~400) of power lines from a DJI drone and I am using WebODM to georeference and stitch them. Along with them, I have a geo.txt file containing the name x, y, z coordinates, and the omega phi degrees, and kappa. The issue that I have is that the resulting GeoTiff is a scramble of pixels and is georeferenced on the wrong continent. Everything works fine if I just stitch the images, without georeferencing them. Here is a sample of the content of the geo.txt file:
`
EPSG:32635

DSC09691.JPG 58.49244886 26.69862449 157.703 -12.62420 8.56771 -116.51796

DSC09692.JPG 58.49253200 26.69869385 157.427 -9.96216 5.83016 -116.67661

DSC09693.JPG 58.49261725 26.69876741 157.024 -6.54626 5.01152 -116.86102

DSC09694.JPG 58.49270073 26.69884230 156.700 -0.74087 2.34656 -117.03159

DSC09695.JPG 58.49277599 26.69891250 156.393 -0.19478 1.02632 -117.11589

DSC09696.JPG 58.49284336 26.69897707 156.215 -10.28164 5.84661 -116.33357
`
(I tried using a PROJ string instead of EPSG, but the result was still the same.)

Here is an example of an input image: [https://preview.redd.it/d2otfgg0eid71.jpg?width=6000&format=pjpg&auto=webp&s=dd5c7af01c69a385901e3ece5cdcc3cd783755f1](https://preview.redd.it/d2otfgg0eid71.jpg?width=6000&format=pjpg&auto=webp&s=dd5c7af01c69a385901e3ece5cdcc3cd783755f1)

And here is an example of the results that I get: [https://preview.redd.it/e1cgmagydid71.jpg?width=81&format=pjpg&auto=webp&s=4532caddea9348f94797f438cd6a36c3b386cdcd](https://preview.redd.it/e1cgmagydid71.jpg?width=81&format=pjpg&auto=webp&s=4532caddea9348f94797f438cd6a36c3b386cdcd)

I tried different sets of images with different sets of coordinates but the result was still the same.
The type of run that I do is just "Fast orthophoto". The results are the same whether image resizing is used or not.

### What should be the expected behavior?
The result should be stitched georeferenced orthoimages in GeoTIFF.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

You can try to make a "Fast orthophoto" run on WebODM and use the following images and geo.txt file: [https://ln4.sync.com/dl/0b7da4c20/ym2hk2rf-tb26sdkj-et9szisk-z8f62p54](https://ln4.sync.com/dl/0b7da4c20/ym2hk2rf-tb26sdkj-et9szisk-z8f62p54)

**Comment by pierotofy** [comment]
Looking at the `geo.txt` file, I suspect you swapped `geo_x` and `geo_y`; the format is:

```
<projection>
image_name geo_x geo_y [geo_z] [omega (degrees)] [phi (degrees)] [kappa (degrees)] [horz accuracy (meters)] [vert accuracy (meters)] [extras...]
...
```
