### ISSUE TITLE
Enable Web Mode from Desktop App

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#1038]
We should give people the option to run the Desktop App with the web features (e.g. share) enabled (as well as binding to 0.0.0.0 instead of localhost and reintroduce the login).

**Comment by TonyPHX** [comment]
This would still be a beloved feature!  : )

**Comment by CryoRig** [comment]
Still hoping this gets added (back?)

**Comment by pierotofy** [comment]
No bandwidth for this (and somewhat of a security risk), unfortunately.
