### ISSUE TITLE
Two jobs in queue but only one started.

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1044]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 92 on Windows 10

### What is the problem?

Two jobs in queue but only one started. 

### What should be the expected behavior?

A single job running and a bar showing the completion rate.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Dont know.

**Comment by APOS80** [comment]
I can cancel the job i can see with an empty progressbar. One job is still in queue, looking in the "node-odm-1" its there.
Looking at the computers workload theres something running.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
