### ISSUE TITLE
Missing ability to set up more than one node on the same pc.

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1047]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome Windows 10

### What is the problem?

I would like to be able to set up more than one node on the same computer without installing docker.

### What should be the expected behavior?

Ability to run more than one job at once on the same computer. Theres enuf cores to do it.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

By coding. :-)

**Comment by pierotofy** [comment]
You can run NodeODM natively (even multiple instances of it): https://github.com/OpenDroneMap/NodeODM/releases
