### ISSUE TITLE
Ortophoto has wrong ESPG

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1051]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome Windows 

### What is the problem?

ESPG:5850 was set in PCG list but GEOTIFF info say something else.

### What should be the expected behavior?

The ESPG in should be the same out.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Try it.

**Comment by pierotofy** [comment]
Hey @APOS80 :hand: currently all outputs are in UTM. We have a feature request for custom EPSG at https://github.com/OpenDroneMap/ODM/issues/1050
