### ISSUE TITLE
ODM community unreachable

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1053]
### What's your browser and operating system? 

Chrome windows 

### What is the problem?

Community on opendronemap.org unreachable.

### What should be the expected behavior?

Getting in an able to read posts

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Go there

**Comment by pierotofy** [comment]
Seems online now? https://community.opendronemap.org/

**Comment by APOS80** [comment]
![6DA82784-20F1-4BBD-A4C6-6DE7121E17C9](https://user-images.githubusercontent.com/6387252/132246056-4f0ebf1d-6e6b-4284-add6-86d2b9b43001.jpeg)

**Comment by APOS80** [comment]
I’m in Sweden, might be an internet issue.

**Comment by pierotofy** [comment]
Mm, got a confirmation from Italy as well. It seems to work from the US.

**Comment by pierotofy** [comment]
Pinging @smathermather @indiajohnson-cm

**Comment by APOS80** [comment]
I have no problem with the main page, just the community forum.

**Comment by smathermather** [comment]
Looking into it. I have confirmed it can't be accessed outside the US.
