### ISSUE TITLE
edit

### ISSUE THREAD

**Issue by 1134961980** [OpenDroneMap/WebODM#1055]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
windows   google

### What is the problem?

The project has been arranged locally.

Incomplete sinicization and automatic translation into Chinese.

Modifying the JSX file will not change the interface, and deleting the whole component will not affect the page program. What is the reason?

thank you!

### What should be the expected behavior?

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[Type answer here]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
