### ISSUE TITLE
WebODM process not generating requsted orthophoto-kmz

### ISSUE THREAD

**Issue by serbinsh** [OpenDroneMap/WebODM#1056]
### What's your browser and operating system? 

Apple Mac OSX 10.14.6 (18G9323) [Mojave]
Chrome Version 92.0.4515.159 (Official Build) (x86_64)

### What is the problem?

I am requesting the creation of an orthophoto KMZ file as part of the output asset set, but only this specific asset is not created.  However, the requested PNG is created.  This behavior is consistent with all my different projects. 

### What should be the expected behavior?

The processing workflow should generate a KMZ file of the resulting RGB orthophoto. At least according to my reading of the documentation

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Run a standard processing workflow, such as "High Resolution" but then edit the workflow to include options like PNG and KMZ.  

For example, see screenshot 

![Screen Shot 2021-09-08 at 9 01 43 AM](https://user-images.githubusercontent.com/3067369/132514142-be89c861-a501-4bde-a127-a4f1a8dbacc5.png)

Perhaps I am missing something?  Or perhaps because of the higher requested resolution the generation doesn't occur?

```
10-4-27-58:WebODM sserbin$ git log -1
commit f86c4a03d2318f2dbb351fc5710ab9fde9f73488 (HEAD -> master, origin/master, origin/HEAD)
Merge: a061a58 5ce33b6
Author: Piero Toffanin <pt@masseranolabs.com>
Date:   Tue Sep 7 00:57:41 2021 -0400

    Merge pull request #1054 from yudeqang/master

    add celery result backend config: retry policy
```

Any feedback is appreciated. Thanks!

**Comment by pierotofy** [comment]
Thanks @serbinsh for the report :pray: this should be fixed with #1057.

**Comment by serbinsh** [comment]
Thanks!  I will merge and try it out!

**Comment by serbinsh** [comment]
Hmm @pierotofy where should I expect to find the KMZ?  I just re-ran a workflow with the latest code and didn't have any luck generating the KMZ 
![Screen Shot 2021-09-08 at 12 58 04 PM](https://user-images.githubusercontent.com/3067369/132552422-36c0207b-0f66-49bc-a95e-53703333cd69.png)

![Screen Shot 2021-09-08 at 12 56 17 PM (2)](https://user-images.githubusercontent.com/3067369/132552390-033dc648-a45d-4fbe-ad6c-a06d9b7b603f.png)

![Screen Shot 2021-09-08 at 12 58 32 PM](https://user-images.githubusercontent.com/3067369/132552510-dc346b27-0286-4fae-8320-8bf0fcebf0a3.png)


```
10-4-27-58:WebODM sserbin$ git log -1
commit 3ce7cb3cef1496fb7b09f276303c0bff3f65bad7 (HEAD -> master, origin/master, origin/HEAD)
Merge: f86c4a0 7b33535
Author: Piero Toffanin <pt@masseranolabs.com>
Date:   Wed Sep 8 10:28:36 2021 -0400

    Merge pull request #1057 from pierotofy/kmz

    Show orthophoto KMZ in task assets
  ```

**Comment by pierotofy** [comment]
Did you issue:

`./webodm.sh update && ./webodm.sh restart`?

**Comment by serbinsh** [comment]
I definitely did ./webodm.sh update but I didn't do it as a single update/restart.  Let me try that!

**Comment by serbinsh** [comment]
Hhmmmm... not really sure what I might be doing wrong but even after doing 

```
./webodm.sh update && ./webodm.sh restart
```

and yet still not getting the KMZ output :/

**Comment by pierotofy** [comment]
Can you share the full task output of the task?

**Comment by serbinsh** [comment]
Here it is. looks like there was a command issued to create it.  I am mapping the data to my host machine so was looking in the output assets folder but am a little confused as to why the timestamps didn't update for the same project. this is why I am going to try again with a new project 

[task_output.txt](https://github.com/OpenDroneMap/WebODM/files/7131739/task_output.txt)

**Comment by pierotofy** [comment]
Ah, whoops! I've forgot to update NodeODM also. The KMZ is getting created, but is not included in the `all.zip` archive.

I've opened a fix in NodeODM.

**Comment by serbinsh** [comment]
ahh! no worries and thanks for opening a fix!

**Comment by serbinsh** [comment]
OK updated nodeODM, giving it another go

```
wolfmanodesktop:nodeodm sserbin$ git log -1
commit 3ce7cb3cef1496fb7b09f276303c0bff3f65bad7 (HEAD -> master, origin/master, origin/HEAD)
Merge: f86c4a0 7b33535
Author: Piero Toffanin <pt@masseranolabs.com>
Date:   Wed Sep 8 10:28:36 2021 -0400

    Merge pull request #1057 from pierotofy/kmz

    Show orthophoto KMZ in task assets
  ```
