### ISSUE TITLE
WebODM Flatpack/Snap?

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1061]
### What is the problem?

Hard to get going on Linux

### What should be the expected behavior?

WebODM as Flatpack or Snap would make things easier.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Docker is for sysadmins

**Comment by pierotofy** [comment]
Getting this to work on Snap/Flatpack is a significant effort; would you be interested in contributing toward this?

**Comment by APOS80** [comment]
> Getting this to work on Snap/Flatpack is a significant effort; would you be interested in contributing toward this?

I don’t know where to begin. I now some python and racket. Very little C.

**Comment by bluecamel** [comment]
I've just posted a [PR that adds a Debian package](https://github.com/OpenDroneMap/WebODM/pull/1066).  It's not exactly what you were asking for, but it might help if you are on a Debian-based system.

**Comment by pierotofy** [comment]
Closing, feel free to open a PR that implements flatpack and/or snap.
