### ISSUE TITLE
node unable bring online

### ISSUE THREAD

**Issue by mavicaleb** [OpenDroneMap/WebODM#1074]
What's your browser and operating system?

[Safari 15 Mac OS big sur 11.6]

What is the problem?

[I am unable to bring any processing node online]

What should be the expected behavior?

[]

How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[for the processing node I used "localhost" and port 3000, but the node never goes online and at the top says that it is offline. and when I try to add photos it gives me the error "There are no usable processing nodes. Make sure that at least one processing node is reachable and that you have granted the current user sufficient permissions to view the processing node (by going to Administration -- Processing Nodes -- Select Node -- Object Permissions -- Add User/Group and check CAN VIEW PROCESSING NODE). If you are bringing a node back online, it will take about 30 seconds for WebODM to recognize it." I have tried changing the port, adding multiple nodes, etc. I have looked at other discussions but have had a difficult time understanding what they are talking about. help would be much appreciated. ]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by mavicaleb** [comment]
Yes you can move it
