### ISSUE TITLE
Unable to resume processing 

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1084]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome Win 10

### What is the problem?

Resuming processing after pushing cancel and restarting computer doesn’t work. It instead starts over from the beginning.

### What should be the expected behavior?

Resume from the last step

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

try it I think

**Comment by pierotofy** [comment]
After canceling a task, there's a `Restart` --> `Resume Processing` option (if you're processing from local node). This does not apply to Lightning cloud nodes (which cannot restart a task).

![image](https://user-images.githubusercontent.com/1951843/156049329-bfb77c7e-e24e-4151-bcfd-e8e0c5708d63.png)

If this is not the issue (or if it doesn't work as expected), feel free to reopen with more details :pray:
