### ISSUE TITLE
Indication of completed calculation

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1087]
### What's your browser and operating system?
Chrome Win 10

### What is the problem?

Hard to se what steps is done.

### What should be the expected behavior?

I would like to se a dot or colouring to indicate if a step is calculated/done.

**Comment by pierotofy** [comment]
Hey @APOS80 we'd welcome a PR to improve this.

**Comment by APOS80** [comment]
> Hey @APOS80 ✋ we'd welcome a PR to improve this.

Don’t know what I can do, I know some python though. Wouldn’t know where to begin actually.

**Comment by pierotofy** [comment]
The frontend is Javascript/React. It could be a fun learning experience!

https://reactjs.org/

**Comment by APOS80** [comment]
> The frontend is Javascript/React. It could be a fun learning experience!
> 
> https://reactjs.org/

Got a jobb and a family, i hardly have time to breath

**Comment by pierotofy** [comment]
Closing, I'd welcome a PR that implements this. :pray:
