### ISSUE TITLE
Error when computing

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1088]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome, Windows 10

### What is the problem?

Error when processing

### What should be the expected behavior?

No error

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 3221226505
Traceback (most recent call last):
File "C:\WebODM\resources\app\apps\ODM\stages\odm_app.py", line 94, in execute
self.first_stage.run()
File "C:\WebODM\resources\app\apps\ODM\opendm\types.py", line 341, in run
self.next_stage.run(outputs)
File "C:\WebODM\resources\app\apps\ODM\opendm\types.py", line 341, in run
self.next_stage.run(outputs)
File "C:\WebODM\resources\app\apps\ODM\opendm\types.py", line 341, in run
self.next_stage.run(outputs)
[Previous line repeated 1 more time]
File "C:\WebODM\resources\app\apps\ODM\opendm\types.py", line 322, in run
self.process(self.args, outputs)
File "C:\WebODM\resources\app\apps\ODM\stages\openmvs.py", line 79, in process
system.run('%s "%s" %s' % (context.omvs_densify_path,
File "C:\WebODM\resources\app\apps\ODM\opendm\system.py", line 106, in run
raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 3221226505

===== Done, human-readable information to follow... =====

[ERROR]   The program exited with a strange error code. Please report it at https://community.opendronemap.org

     
558 images processed with following settings:
[{"name": "build-overviews", "value": true}, {"name": "crop", "value": "4"}, {"name": "dem-resolution", "value": "2"}, {"name": "dsm", "value": true}, {"name": "feature-quality", "value": "ultra"}, {"name": "feature-type", "value": "orb"}, {"name": "gps-accuracy", "value": "10"}, {"name": "ignore-gsd", "value": true}, {"name": "matcher-distance", "value": "40"}, {"name": "matcher-neighbors", "value": "68"}, {"name": "mesh-octree-depth", "value": "8"}, {"name": "orthophoto-resolution", "value": "2"}, {"name": "pc-geometric", "value": true}, {"name": "pc-quality", "value": "ultra"}, {"name": "pc-sample", "value": "0,02"}, {"name": "resize-to", "value": "-1"}, {"name": "texturing-keep-unseen-faces", "value": true}, {"name": "texturing-tone-mapping", "value": "gamma"}, {"name": "use-hybrid-bundle-adjustment", "value": true}, {"name": "verbose", "value": true}]

Computer:
Ryzen 5 2600
32gig ram
1tb SSD

**Comment by pierotofy** [comment]
Does this error happen all of the times or just with some images/settings?

**Comment by APOS80** [comment]
> Does this error happen all of the times or just with some images/settings?

Happend when processing 558 images from a Mavic 2 Pro, Ultra high setting, ORB. Possible lack of memmory but I dont know.

**Comment by pierotofy** [comment]
Ok so not all of the times.

**Comment by pierotofy** [comment]
Feel free to re-open with a link to your dataset? Thanks.
