### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by mtaivalmaa** [OpenDroneMap/WebODM#109]
I have installed webodm using docker on my Macbook air i7 8gb ..

I have successfully run a project with 14 4K photos from my DJI Mavic no issues.

When I load a larger project 90 - 120 4K pics, I get the following after about 15mins. of processing.

Any help would be great.

DoG running...4231 dog done
4148 dog done
done
Killed
Traceback (most recent call last):
  File "/code/run.py", line 55, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/pmvs.py", line 73, in process
    (context.pmvs2_path, tree.pmvs_rec_path))
  File "/code/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137

**Comment by pierotofy** [comment]
Hi @mtaivalmaa, per https://github.com/OpenDroneMap/WebODM#common-troubleshooting if you see a `Killed` message it means you are running out of RAM.

See this link on how to increase it: http://stackoverflow.com/a/39720010

**Comment by mtaivalmaa** [comment]
I was wondering about that .. thank you!

**Comment by mtaivalmaa** [comment]
Per pierotofy.. 

Setting Docker from 2gig ram to 4 gig ram fixed my issue.

See this link on how to increase it: http://stackoverflow.com/a/39720010

Kind Regards,

Mike
