### ISSUE TITLE
Cannot launch WebODM

### ISSUE THREAD

**Issue by SCFred28** [OpenDroneMap/WebODM#1091]
### What's your browser and operating system? 

Chrome 95 on Windows 11

### The problem 
With the new 1.9.11 build 32 this error message at the launch is poping-up
![image](https://user-images.githubusercontent.com/83292330/140996650-4ef8ab08-82de-4c5d-8ef1-2a497cd9cb32.png)

### What should be the expected behavior?

No pop-up and complete launch of WebODM

### How can we reproduce this?

Click on the WebODM Icon and wait

**Comment by pierotofy** [comment]
Hey @SCFred28 :hand: Could you please attach the logs?

**Comment by pierotofy** [comment]
Build `37` is now online and should fix this; please re-download the setup and try again?

Thanks!
