### ISSUE TITLE
Ability to disable mesh creation.

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1094]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Chrome Win 10

### What is the problem?

I would like to disable the creation of the mesh, its of no use for me.

### What should be the expected behavior?

Would nice to disable via checkbox

**Comment by pierotofy** [comment]
This is not possible; a mesh is always required to perform orthorectification.
