### ISSUE TITLE
Possible Bug: geo.txt not being auto-detected nor loaded

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1096]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
NA

### What is the problem?
A properly named/structured geo.txt that is uploaded into WebODM alongside the referenced images does not appear to be used by WebODM.

### What should be the expected behavior?
The geo.txt should be auto-detected and used.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Community Post (with sample data/geo.txt):  
https://community.opendronemap.org/t/cannot-pass-image-geolocation-file-geo-txt-into-project/6368/20?u=saijin_naib

**Comment by pierotofy** [comment]
I found a separate issue, the file is detected, but is interpreted as a GCP if image resize is turned on, which obliterates its contents.

**Comment by gastgit** [comment]
hi.. Is this resolved?

**Comment by pierotofy** [comment]
I don't think it is.

**Comment by gastgit** [comment]
> I don't think it is.

Tnx @pierotofy 
Was it only pertinent to WebODM as far as you understood or a more general issue?

**Comment by pierotofy** [comment]
Should be fixed now!

**Comment by gastgit** [comment]
> Should be fixed now!

Tnx!
