### ISSUE TITLE
Add compression to GeoTIFF export outputs

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#1099]
We currently do not compress outputs when generating GeoTIFFs. This is not ideal.

**Comment by Saijin-Naib** [comment]
I think we've got some room to improve, especially with modern GDAL and other dependencies.

We should be able to do band interleaved with predictor 2, and maybe ZSTD+LERC for DEMs and maybe JPEG + transparency band for orthophotos...

https://github.com/OpenDroneMap/ODM/issues/1040
https://kokoalberti.com/articles/geotiff-compression-optimization-guide/
http://blog.cleverelephant.ca/2015/02/geotiff-compression-for-dummies.html

**Comment by pierotofy** [comment]
I would love to use the latest and greatest, just not sure if older/proprietary programs will be able to read the results afterwards. Needs to be balanced for interoperability.

**Comment by Saijin-Naib** [comment]
DEFLATE + Predictor 2 and ZLEVEL 12 or 9 should be about as good as we can get while keeping things bog-standard then.

**Comment by andrewharvey** [comment]
> We currently do not compress outputs when generating GeoTIFFs. This is not ideal.

I think this should be revisited. Different users would have different requirements around if they disk space, processing times, compatibility with other applications and tolerance for lossy compression.

**Comment by andrewharvey** [comment]
https://github.com/linz/elevation/blob/master/docs/research/tiff-compression.md has some analysis
