### ISSUE TITLE
Processing failed (4294967295)

### ISSUE THREAD

**Issue by studiosarchese** [OpenDroneMap/WebODM#1101]
### What's your browser and operating system? 

![Codice errore in processamento](https://user-images.githubusercontent.com/95164666/143739752-1daec6c3-46c6-4755-9eb7-3d19cb2aa504.jpg)
Edge 96 on Windows 11

### What is the problem?

In fase di processamento immagini restituisce codice errore: Processing failed (4294967295)

### What should be the expected behavior?

Dovrebbe processare le immagini e restituire i dati di elaborazione

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Ho caricato le immagini riprese con un drone Mavic Air 2 pro, le ho importate tramite il tool del software, in nodo elaborazione ho lasciato auto, in opzioni ho lasciato predefinito, ridimensiona immagini ho lasciato no e infine ho lanciato l'elaborazione. Ho provato su due pc è da lo stesso errore.

![Codice errore in processamento](https://user-images.githubusercontent.com/95164666/143736023-848da732-da8c-486e-bd9e-30a9da615282.jpg)

**Comment by pierotofy** [comment]
@studiosarchese can you please provide a copy of your images?

**Comment by Karanza** [comment]
Ciao,ho il tuo stesso problema.Sei riuscito a risolvere?

**Comment by Saijin-Naib** [comment]
@Karanza , Are you on the current version (v1.9.14 Build 64)? This should not be happening anymore on the latest releases.

**Comment by Karanza** [comment]
Si,ho la versione che dici te.Pero ho notato che se nelle opzioni metto model 3d fallisce,se invece messo personalizzato va a buon fine...non capisco il perché? Il voglio fare modello 3 d,ma come faccio?

**Comment by Saijin-Naib** [comment]
Apri una discussione sulla nostra Community poiché il tuo problema è diverso:
https://community.opendronemap.org/invites/DGsLLWf1tr

**Comment by pierotofy** [comment]
No input images, cannot reproduce. Closing.

**Comment by Karanza** [comment]
Si,ho quella versione...ho notato che se nelle opzioni metto modello 3d fallisce e da errore, mentre se metto personalizzato il processo va a buon fine.. Come mai?



Andrea



-------- Messaggio originale --------
Da: Saijin-Naib ***@***.***>
Data: 25/06/22 03:54 (GMT+01:00)
A: OpenDroneMap/WebODM ***@***.***>
Cc: Karanza ***@***.***>, Mention ***@***.***>
Oggetto: Re: [OpenDroneMap/WebODM] Processing failed (4294967295) (Issue #1101)


@Karanza<https://github.com/Karanza> , Are you on the current version (v1.9.14 Build 64)? This should not be happening anymore on the latest releases.
