### ISSUE TITLE
Cannot export surface model

### ISSUE THREAD

**Issue by MrMinecraft97** [OpenDroneMap/WebODM#1102]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 96 on Windows 10
Also does the same on
Chrome 95 on MacOS (Catalina)

### What is the problem?

Unable to export any surface model map any format, normal orthomap works correctly.

Error Message:

[Web Error.txt](https://github.com/OpenDroneMap/WebODM/files/7614540/Web.Error.txt)

### What should be the expected behavior?

Download the selected map to local machine.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

**Only seems to occur when using the same images for more than one project at a time.**

Used one set of images to create one map, downloaded correctly. Under the same project created a new task, did not work. Produced error in git bash terminal.
[Error.txt](https://github.com/OpenDroneMap/WebODM/files/7614535/Error.txt)

Going back to original task, exports correctly.

After clicking to export map, it loads for a while then produces error message in web browser. Full error above.
![Screenshot 2021-11-28 143413](https://user-images.githubusercontent.com/85265966/143784944-d20f95a4-8ebc-4fd1-b435-d7f337d00635.png)

Using same image set but reprocessing in another project and task yields the same. Normal map works, but surface model does not.

**Comment by pierotofy** [comment]
Should be fixed with the latest release :clinking_glasses: feel free to re-open if the issue persists?
