### ISSUE TITLE
Empty dashboard when opening tasks if cesium ion plugin is enabled

### ISSUE THREAD

**Issue by justgeekit** [OpenDroneMap/WebODM#1104]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

(https://whatismybrowser.com/w/52JCHDB)

### What is the problem?

V1.9.11 update WebODM dashboard goes blank when selecting task after update

### What should be the expected behavior?

When selecting a task it should expand the task options.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

When I go to the WebODM dashboard view tasks for a project and select a task the dashboard goes blank.

![View of tasks](https://user-images.githubusercontent.com/62150001/144091057-7cd547de-0d91-4b30-854c-86bda0a173d0.PNG)
![dashboard blank when a task is selected](https://user-images.githubusercontent.com/62150001/144091083-de3d3539-6d2a-4153-9854-4ea842aba372.PNG)

**Comment by pierotofy** [comment]
Hey @justgeekit thanks for the report! Are you running this with docker? (via `./webodm.sh start` ?)

**Comment by Minhom** [comment]
Maybe u can turn off cesiumION in Administration   
![0dcd905c4e251b9f4e1ebe191fa61d1](https://user-images.githubusercontent.com/25901729/144228689-7074c2f9-2515-4423-b998-82cd149e5cda.jpg)

**Comment by MrCare** [comment]
awesome! it works!!! @Minhom

**Comment by justgeekit** [comment]
Yes, I am using docker via ./webodm.sh start.

**Comment by pierotofy** [comment]
The Cesium Ion plugin has not been updated for years; I'm not sure why it broke (or when), but Cesium GS Inc. hasn't really been supporting this plugin, so I'm going to remove it at the next release.

If this plugin is important, I would urge people to get Cesium's team involved.

Archived plugins will now live on https://github.com/OpenDroneMap/WebODM-Plugins-Archive
