### ISSUE TITLE
Contour map not working

### ISSUE THREAD

**Issue by MrMinecraft97** [OpenDroneMap/WebODM#1105]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 96 on Windows 10

### What is the problem?

After clicking preview on the contour map, it loads for a while then gives and error. No output onto map.

### What should be the expected behavior?

Show the lines of the selected height on the map window.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Used dataset that seems to work well for everything else, default settings.
Error message:
![Screenshot 2021-12-01 171410](https://user-images.githubusercontent.com/85265966/144329337-7c8f438f-e930-4c43-892f-615023593ad5.png)

**Comment by pierotofy** [comment]
I think this should be fixed with the latest version. :clinking_glasses: Feel free to re-open if the issue persists?
