### ISSUE TITLE
Feature Request: Granular Progress Bar

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1106]
### How did you install WebODM (docker, installer, etc.)?
N/A

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
N/A

### What is the problem?
The current progressbar in WebODM only moves at pre-defined checkpoints, the processing times of which are not always represented well by the percentage of the bar they occupy. Further, if one is 99% through one stage, the progress bar will remain at the beginning of that checkpoint, belying the fact that progress has indeed occurred and is ongoing.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
This thread illustrates the problem nicely:  
https://community.opendronemap.org/t/checking-progress-on-a-fast-orthophoto-task/9736?u=saijin_naib

This post has some good potential approaches to consider:  
https://community.opendronemap.org/t/checking-progress-on-a-fast-orthophoto-task/9736/4?u=saijin_naib

**Comment by pierotofy** [comment]
I'm not going to implement this one; progress reporting is not an exact science. I'd welcome a PR of course.
