### ISSUE TITLE
Feature Request: Optional Task Completion Audio Notifications

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1107]
### How did you install WebODM (docker, installer, etc.)?
N/A

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
N/A

### What is the problem?
When one has long running task(s), they may not stay at a given machine with the monitor live, so they may not know if/when a task has completed/failed. Having the option to play back a distinctive audio chime when a task completes or fails may help someone monitor their tasks without having to maintain visual on the machine doing the processing.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
Use WebODM. Not sure if this carries too many dependencies, but I think it might be a safe approach without requiring special permissions in the browser (Notifications/Run in Background).

**Comment by pierotofy** [comment]
I'm going to close this one; I don't think the software should ping people via audio notifications. :pray: 

There might be a case to allow optional web notifications (opt-in).
