### ISSUE TITLE
Feature Request: Display Uncalibrated Camera Locations with Distinct Symbol

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1108]
### How did you install WebODM (docker, installer, etc.)?
NA

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
NA

### What is the problem?
Some images can be problematic for reconstruction so having an idea of which images were dropped can be very helpful for re-fly or possibly other adjustments. Having the uncalibrated camera locations displayed in WebODM  (using a distinct symbol) would allow folks to see which areas of their survey are being difficult and also to inspect the individual cameras image footprints and file names.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
Use WebODM with a dataset that doesn't fully calibrate.

**Comment by pierotofy** [comment]
No bandwidth for this. (PR most welcome though).
