### ISSUE TITLE
Holes in orthophoto and increased cropping with new version.

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1120]
### How did you install WebODM (docker, installer, etc.)?

Installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

I have a test dataset that im testing on and theres differences.

Theres holes in the orthophoto after installing latest version of WebODM.
It seams cropping has increased, several meters of orthophoto has gone missing.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Try processing with an old dataset that worked befour.

**Comment by pierotofy** [comment]
>> How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
