### ISSUE TITLE
Feature Request: Add the mozilla intermediate tls config to nginx-ssl.conf

### ISSUE THREAD

**Issue by aonwittawat** [OpenDroneMap/WebODM#1123]
### How did you install WebODM (docker, installer, etc.)?
Docker

git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input --depth 1
cd WebODM
./webodm.sh start 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

CentOS 8

### What is the problem?

A few outdated ciphers being offered when using enable SSL. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Apply the mozilla intermediate tls config in [nginx-ssl.conf.template](https://github.com/OpenDroneMap/WebODM/blob/master/nginx/nginx-ssl.conf.template) with installation docker version.
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

More details can be found [here](https://ssl-config.mozilla.org/#server=nginx&server-version=1.18.0&config=intermediate&openssl-version=1.1.1k)

**Comment by pierotofy** [comment]
It's my understanding that these will strengthen the SSL connection, but might drop compatibility with some older browsers? I'm not really sure of the exact impact these changes might do, but feel free to open a PR along with explanations of what these changes would do to benefit users. :pray:
