### ISSUE TITLE
Process exited with code 1 - GCP 

### ISSUE THREAD

**Issue by szulaikha** [OpenDroneMap/WebODM#1124]
### How did you install WebODM (docker, installer, etc.)?
I'm using the online version.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Chrome 97 on Windows 10

### What is the problem?
When I upload my images it can produce the map but not that accurate. So, I use the GCP. But everytime I upload the images with the GCP files it always give me "Process exited with code 1"

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
This is the task output.
[console.txt](https://github.com/OpenDroneMap/WebODM/files/7905307/console.txt)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: It's likely that the GCP is not formatted properly (please share a link to the images + GCP on the forum so people can try to help with that) :+1:
