### ISSUE TITLE
webodm.sh should respect the WO_DEFAULT_NODES env variable by default

### ISSUE THREAD

**Issue by gromain** [OpenDroneMap/WebODM#1131]
When starting WebODM with the command line (with `./webodm.sh start`) and after configuring the `.env` file, it appears that a node is started even if the variable `WO_DEFAULT_NODES` is set to 0.

Probably just adding `default_nodes=$WO_DEFAULT_NODES` after the `.env` sourcing [here](https://github.com/OpenDroneMap/WebODM/blob/6a16b1593c43d32d35edb802bed54e3aa1a0b4d7/webodm.sh#L39) would be enough.

**Comment by gromain** [comment]
damn gitissuebot you're annoying for such a simple issue.

### How did you install WebODM (docker, installer, etc.)?

docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

not relevant

### What is the problem?

See first post

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

See first post

**Comment by pierotofy** [comment]
Good point, would you be interested in opening a pull request @gromain ? :pray:

**Comment by gromain** [comment]
Sure can! Will look at it tomorrow! :-)
