### ISSUE TITLE
The Edit Task Options dialog is cut off when called from the cloudimport or dronedb import plugins

### ISSUE THREAD

**Issue by OKaluza** [OpenDroneMap/WebODM#1163]
### How did you install WebODM (docker, installer, etc.)?
Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Firefox 98 on Ubuntu Linux

### What is the problem?
The Edit Task Options dialog is cut off when called from the cloudimport or dronedb import plugins

### How can we reproduce this?
- Enable cloudimport or dronedb import plugins and set up username/pw etc
- Import using the plugin buttons
- Use the Edit button to open the Edit Task Options dialog
- The dialog is cut off when opened from a modal dialog and very hard to work with
![image](https://user-images.githubusercontent.com/6336397/160539658-394d1d17-8b41-4d65-926c-4dd6bdcc1f4a.png)

I have implemented a fix and will reference this issue in the pull request

**Comment by pierotofy** [comment]
Thanks for the detailed report (and the fix!). This can be closed now. :+1:
