### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by RPAS-Inspections** [OpenDroneMap/WebODM#1170]
### How did you install WebODM (docker, installer, etc.)?

installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

https://whatismybrowser.com/w/GQEDWGX

### What is the problem?

I am unable to log into lightning network, keeps giving me a Invalid Credentials error. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

I click on the lightning network tab, I input my email address and password and it returns an error message. I have confirmed the email and password work by logging in directly via the browser, but it doesn't work via the application.

**Comment by pierotofy** [comment]
Hi, make sure your username / e-mail address is the same as the one you registered with (check for uppercase/lowercase differences). If you still have issues, try logging out and resetting your password by visiting https://webodm.net/reset. If you still have issues, reach out to hello@uav4geo.com. I'll close this for now (this is a place to report bugs). :pray:
