### ISSUE TITLE
problems after update - no 3D models.

### ISSUE THREAD

**Issue by holoboss** [OpenDroneMap/WebODM#1173]
****************************************
### How did you install WebODM (docker, installer, etc.)?

[installer - update]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[windows 10 / 64   MS Edge]

### What is the problem?

[Hello, i used older version with Docker also from installer - without issues. But I recently updated to newest version and since then I can't see 3D model. nothing changed in my computer, same configuration. 2D maps are ok as before.  but 3D model does not show. Just a blank background. all tools on side are present, but i can't make 3D model appear. I checked project rendering options, made sure 3d model and other 3d options are ON (textured model, mesh, and so on). I tried several different configurations, various quality of Point Cloud rendering. i tried returning to default options too. Nothing. 3D model does not show up in any form. And when I upload same set of images to the DroneDB HUB online, i can create online 3D model without problem. Not sure what happens, and idea?
Many thanks!
Derek]

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

[Type answer here]
![Screenshot (2)](https://user-images.githubusercontent.com/104271400/164916990-71d0ee24-8ee5-4f50-90a9-71945fedaae4.png)

**Comment by pierotofy** [comment]
Hi @holoboss :hand: could you send us a copy of the `all.zip` (All Assets) archive to help us reproduce this? :pray:

**Comment by holoboss** [comment]
Thank you. Here is download link to all.zip   (valid 1 week). i picked a very small project to keep size to minimum. 
https://we.tl/t-sltj4OzbUH

checked again before upload - can't see 3D on my WebODM.
Appreciate your help! Cheers
Derek

**Comment by pierotofy** [comment]
Thanks Derek, this should have been fixed with and will be included in the next build/update.

In the meanwhile, if the model doesn't appear, try pressing the "Full Extent" button from the navigation menu:

![image](https://user-images.githubusercontent.com/1951843/167168414-4dfc3f1b-fbe2-49e5-bd7f-c21aeff1f234.png)

**Comment by holoboss** [comment]
the Full Extent worked! Thank you! Sorry to bother you, appreciate your help!
Derek
