### ISSUE TITLE
Possible Bug: DroneDB Integration Plugin needs update/fixing

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1176]
### How did you install WebODM (docker, installer, etc.)?
Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Alpine Linux Edge (3.15)

### What is the problem?
DroneDB Plugin can not populate any datasets:  
![image](https://user-images.githubusercontent.com/19295950/166060776-b8e1e43a-92ec-430e-bcb9-0c86ba09de54.png)
![image](https://user-images.githubusercontent.com/19295950/166060819-535c93ac-256f-4f2d-be60-0ed7b888fa28.png)

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
Properly sign-in to DroneDB plugin and attempt to list any datasets you have.

Behavior confirmed in Docker and Windows install, issue report from Community:  
https://community.opendronemap.org/t/dronedb-integration-no-datasets-found/11353?u=saijin_naib

**Comment by pierotofy** [comment]
Pinging @HeDo88TH

**Comment by HeDo88TH** [comment]
> Pinging @HeDo88TH

Fixed 🚀
