### ISSUE TITLE
Processing with cuda uses enormous amounts of ram

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1184]
### How did you install WebODM (docker, installer, etc.)?

Windows native 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

Processing with cuda eats upp ram.

At “undistorting image” stage cuda I involved and it eats more than my 64gigs of ram compared to just CPU that might use 20%.

**Comment by pierotofy** [comment]
The `undistorting images` step does not use CUDA (it's a step in OpenSfM which never uses the GPU). Perhaps something else is at play for the difference in RAM usage.

How did you measure this? How can we reproduce? Share your dataset, please.
