### ISSUE TITLE
The model generated produces a wrong direction of the slope

### ISSUE THREAD

**Issue by wladuk** [OpenDroneMap/WebODM#1185]
Apologies if I am doing (including reporting this) wrong, but I am a first time user. 

****************************************
### How did you install WebODM (docker, installer, etc.)?

installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 101 on Windows 10

### What is the problem?

I captured the images of a piece of land in Brazil and compared the model generated with WebODM and with the DroneDeploy. The one with DroneDeploy captures correctly the slope of the terrain, which goes from South to North. The model generated with WebODM produces a "crest" in the middle of the terrain, that would actually imply a divide in the way the waters run, which is not the case. I am pasting below two lateral views of the model as generated from those softwares for comparison. 

DroneDeploy (correct slope) 
![terreno Santa Barbara - DroneDeploy - Point Cloud - skyline](https://user-images.githubusercontent.com/10230269/169845456-10c771e2-27ea-48be-ab7a-726dc7e09349.png)

WebODM (wrong in the right (South) side of the figure - it shouldn't be sloping down towards the south)
![terreno Santa Barbara - WebODM - Point Cloud - skyline](https://user-images.githubusercontent.com/10230269/169846896-52773070-1a80-4b3e-b3ce-e71500f0ba4a.png)

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

As far as I can tell, I used the standard parameters. The original files of this mission can be found at https://drive.google.com/drive/folders/1eoXFrUIFvaqbwhItpZzMLJ4BX-jlcqHM?usp=sharing

Thank you

**Comment by pierotofy** [comment]
Try processing this dataset with `--feature-type dspsift` as well as `--use-hybrid-bundle-adjustment`, we've made significant improvements since this issue was opened.

If the problem persists, feel free to reopen 🙏
