### ISSUE TITLE
Front-end unit tests

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#119]
It would be nice to start testing some critical parts of the front-end, especially as the UI stabilizes.

**Comment by AnthonyCoughlin** [comment]
I'm not sure if I can help with anything but I'd love to try.  If you need me to be a beta guinea pig I'm down.  Least I can do after all the help you guys have given me.

**Comment by pierotofy** [comment]
Hey @AnthonyCoughlin thanks for volunteering! Unit tests are automated tests (it's code that checks other code), but we're always looking for manual testers as well. If you see something in the user interface that doesn't look right, or that could be improved, you could help us by opening an issue reporting the problem!
