### ISSUE TITLE
User interface modification 

### ISSUE THREAD

**Issue by mhmyzah** [OpenDroneMap/WebODM#1202]
### How did you install WebODM (docker, installer, etc.)?

I used docker 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome and windows 11

### What is the problem?

I want to edit the user interface. I want to add new buttons and change the buttons text 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

I tried to search for buttons' names and edit them in the jsx files and save it but it didn't change any thing

**Comment by pierotofy** [comment]
Hi :hand: check https://docs.webodm.org/#for-developers to setup a dev environment. (For all other questions, let's move the conversation over to https://community.opendronemap.org :pray:  )
