### ISSUE TITLE
Different synthesis results for the same task with the same parameters

### ISSUE THREAD

**Issue by LeeLulin** [OpenDroneMap/WebODM#1207]
### How did you install WebODM (docker, installer, etc.)?

docker

### What's your browser and operating system?

Edge 103 on macOS (Catalina)

### What is the problem?

There are about 160 images for orthophoto synthesis, and with fast orthophoto on with constant parameters, the synthesized orthophoto impact will be distorted with a high probability after each restart from the dataset, and the results will be different each time. There is a chance that it will work after several reboots.

![WechatIMG105](https://user-images.githubusercontent.com/27431274/179184055-45dbf8f7-6a76-4b10-9c55-69959a50ed46.png)
<br>
<img width="889" alt="WX20220715-162325@2x" src="https://user-images.githubusercontent.com/27431274/179184620-19c2c67b-7aed-4d7b-86e9-062ad0053728.png">

### How can we reproduce this? 

Open fast-orthophoto only, resturn from the dataset, and view the synthesis results

**Comment by pierotofy** [comment]
There's some randomness in the reconstruction process, so this would explain the different outputs.

> If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Please re-open this issue attaching a copy of your dataset? :pray:

**Comment by LeeLulin** [comment]
Dataset: https://hub.dronedb.app/r/lulin/test

**Comment by LeeLulin** [comment]
> There's some randomness in the reconstruction process, so this would explain the different outputs.
> 
> > If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
> 
> Please re-open this issue attaching a copy of your dataset? 🙏

Dataset: https://hub.dronedb.app/r/lulin/test
