### ISSUE TITLE
Normalize Assets Paths

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#121]
Right now assets are all over the place. node-opendronemap (or WebODM?) should create a strict standard of where assets should be placed before being downloaded.

For example:

`/pointcloud.las`
`/orthophoto.tif`
`/texturedmodel/model.obj`
`/texturedmodel/model.mtl`
`/dem.tif`
`/contours.shp`

This will make it easier to future proof paths and perhaps allow other photogrammetry engines to plug-in into WebODM.

**Comment by smathermather** [comment]
Agreed. I know @dakotabenjamin has given this some thought.

**Comment by pierotofy** [comment]
Albeit this was a good idea, it would add significant complexity. I'm going to take this off the TODO list as existing filename conventions seem to be holding pretty well. :clinking_glasses:
