### ISSUE TITLE
Feature Request: libcaesium integration

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1214]
### How did you install OpenDroneMap? (Docker, natively, ...)?
Native

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
NA

### What is the problem?
JPEGs coming out of most sensors are not well-optimized, and there are a host of lossless optimizations that can be applied to them to reduce file size. Typically, this is on the order of 20% or so.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.
I think looking at libcaesium for ingested images into ODM would be neat, as it could result in a smaller local database store, smaller upload to the cloud for Lightning, and smaller shuffling around for cluster/node operations.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Run Caesium Image Compressor against a dataset.
SOOC
![Screenshot 2021-08-09 161413](https://user-images.githubusercontent.com/19295950/128787026-ae2b70b9-08db-482f-b512-d106f56286a6.png)

Lossless Optimization with libcaesium
![Screenshot 2021-08-09 161422](https://user-images.githubusercontent.com/19295950/128787028-75f6802b-89b1-4da4-9834-c28b1bf6d40b.png)

**Comment by pierotofy** [comment]
Not enough bandwidth for this.

**Comment by Saijin-Naib** [comment]
It looks like libcaesium needs some work upstream to keep metadata when transcoding formats, so I will open this again later when that is addressed
