### ISSUE TITLE
WebOdm docker containers uses a huge amount of memory 

### ISSUE THREAD

**Issue by diegoaces** [OpenDroneMap/WebODM#1219]
### How did you install WebODM (docker, installer, etc.)?

Docker 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

### What is the problem?

Docker webodm container uses a huge amount of memory 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

When updated the webodm system with ./webodm.sh update  command  there is garbage left over from the old containers.

![telegram-cloud-photo-size-1-5147623033194785578-x](https://user-images.githubusercontent.com/45692265/183124404-a914c7df-8715-42f7-b4fc-44db41fe0f13.jpg)

![telegram-cloud-photo-size-1-5147623033194785579-y](https://user-images.githubusercontent.com/45692265/183124923-1c244bb5-951e-4163-a44c-e58d4167215f.jpg)

I know that running the docker image prune -a command frees up memory, but is there a way to automatically decrease the amount of space that docker uses?

**Comment by pierotofy** [comment]
Mm, not really; I mean, we could automatically run `docker image prune` for the user, but I'm afraid this is not what some end users would like, as WebODM might not be the only application that runs on docker.

**Comment by diegoaces** [comment]
Thanks @pierotofy, you are right, for those who have other containers running in docker it would cause problems.
But it is a point to consider.
