### ISSUE TITLE
More details in tasks admin list

### ISSUE THREAD

**Issue by diegoaces** [OpenDroneMap/WebODM#1224]
### How did you install WebODM (docker, installer, etc.)?

Docker (it does not matter)

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 104 on macOS (Monterey)](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

### What is the problem?

It is necessary to have more details in the list of tasks that is available in the task administration.
At this time we can only see the name of the task, if we want to know the status, the name of the associated project or when it was created, we must enter each record and review the task.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

http://[youiphere]/admin/app/task/

<img width="863" alt="image" src="https://user-images.githubusercontent.com/45692265/186013303-534acabe-aac7-47aa-8323-f2f501e07262.png">

@pierotofy  I made the change in my master branch and would like to include the project as an enhancement.

**Comment by pierotofy** [comment]
Hey @diegoaces ✋ thanks for opening this; to make the changes available you'll need to open a pull request. There's some guides on GitHub if you search with Google on how to open one, let me know if you need some direction 👍
