### ISSUE TITLE
Unable to view thermal imagery in multispectral project

### ISSUE THREAD

**Issue by duckblaster** [OpenDroneMap/WebODM#1236]
### How did you install WebODM (docker, installer, etc.)?

Docker WebODM 1.9.15

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 105 on Windows 11]

### What is the problem?

Whenever I select thermal from algorithm drop down it fails: 
```
Cannot find band "Lwir" from "BGRNLwir". Choose a proper band order.
```

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Try to view/download the thermal view of a multispectral orthoimage.

**Comment by pierotofy** [comment]
Hi :wave: thanks for the report; can you share your RAW orthophoto GeoTIFF?

**Comment by duckblaster** [comment]
Here's the whole project output: https://1drv.ms/u/s!AsY5aB0MpC2Dgd5vRRAJiF6zPtdxew?e=FJ8B6n

**Comment by pierotofy** [comment]
The logic to parse the LWIR band was incorrect;

This has now been fixed.

![image](https://user-images.githubusercontent.com/1951843/189719124-72eb4ab2-c652-478b-bd3f-d1115a52e06d.png)

**Comment by duckblaster** [comment]
Thanks, that fixed it!
Some of the functions are not setting the correct min and max values automatically though:
![image](https://user-images.githubusercontent.com/564067/190549582-674d80cb-610b-405f-a3e9-8d2483772222.png)

**Comment by pierotofy** [comment]
This should be improved with #1246
