### ISSUE TITLE
Elevation View trim outliers

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/WebODM#124]
When there's some noise in the elevation view, it makes it less useful:

![image](https://cloud.githubusercontent.com/assets/1847818/24118726/317cd344-0d85-11e7-92be-ea8e07b133bf.png)

It might be helpful to trim something like 2% of the max and min elevation points.

**Comment by pierotofy** [comment]
This could probably be done using the newer version of potree.

![image](https://cloud.githubusercontent.com/assets/1951843/24120863/8228e9ca-0d8c-11e7-8c37-fa4d46b3b9fd.png)

http://potree.entwine.io/data/st-helens.html

I think the source for the new version is here, https://github.com/potree/potree/tree/develop, but I'll have to verify. With the update we would get a lot more goodies as far as the interface goes.

**Comment by pierotofy** [comment]
Work in progress!

![image](https://cloud.githubusercontent.com/assets/1951843/24126648/74a27f50-0da5-11e7-91dc-76aeb445e467.png)

**Comment by smathermather** [comment]
Is that what I think... ?

**Comment by pierotofy** [comment]
Solved as part of #128
