### ISSUE TITLE
Max images count exceeded error message

### ISSUE THREAD

**Issue by diegoaces** [OpenDroneMap/WebODM#1248]
### How did you install WebODM (docker, installer, etc.)?

Docker and mounted on 200 gb volume to storage the processing output.  
WebODM Lightning Network - Unlimited.

### What's your browser and operating system?

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
Ram:   8 GB

### What is the problem?

```
[2022-10-07 13:24:30,616: INFO/ForkPoolWorker-2] worker.tasks.process_task[xxx-xxx-xxx]: Processing... Task [Constitución - 5/10/2022] (xxx)
webapp    | INFO Booting WebODM 1.9.15
[2022-10-07 13:42:10,983: ERROR/ForkPoolWorker-2] worker.tasks.process_task[xxx-xxx-xxx]: FAILURE FOR Task [xxx - 5/10/2022] (xxx): Max images count exceeded.
```

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Created at : 6/10/2022, 22:46:58
Node:  Nodo 1 (manual)
Options:  auto-boundary: true, dsm: true

![image](https://user-images.githubusercontent.com/45692265/194570464-401f1ff0-9868-43f0-a5aa-2ccc07aa3c63.png)

This problem does not occur for processes with less than 500 images.

**Comment by pierotofy** [comment]
Hey @diegoaces ✋ did you make sure your account has sufficient credits or an unlimited plan? Triple check that your node token matches that of your webodm.net account also.

**Comment by diegoaces** [comment]
Hi @pierotofy, yes I have an unlimited plan, in the image you can see another process carried out almost simultaneously with the one that causes problems. Also mention that there are two processes that I can perform in parallel.

![image](https://user-images.githubusercontent.com/45692265/194579647-e745d90c-02e3-41ac-ba78-8a5963d700e2.png)

**Comment by pierotofy** [comment]
Is your internet connection stable/reliable? @Saijin-Naib have you see this one before?

**Comment by diegoaces** [comment]
It is an ODM server running on a DigitaOcean droplet.
After many attempts it was able to process correctly.

**Comment by Saijin-Naib** [comment]
@pierotofy , yeah, once or twice with really flaky uplinks, usually from clients who do not have a DigitalOcean server in their geographic region. I think parts of the upload timeout or drop and the reconnecting messes with the image count somehow... Or that's what it feels like from the few times I saw it.

Similar to @diegoaces , one customer resolved it by just repeatedly re-trying, and another resolved it by traveling to a larger city with better connectivity.

**Comment by pierotofy** [comment]
Mm, I wonder if https://github.com/OpenDroneMap/ClusterODM/blob/c2c2e8f97b9518055f97e822cd5e5874dbc9be52/libs/taskNew.js#L170 is not being called in certain instances (e.g. connection timeout). I've opened https://github.com/OpenDroneMap/ClusterODM/issues/99
