### ISSUE TITLE
Add KML to downloadable assets for the Orthomosaic

### ISSUE THREAD

**Issue by basrijn** [OpenDroneMap/WebODM#126]
Loading the produced orthomosaic in Google Earth is a great way to review the output (and georeferencing accuracy). Most people have the standard Google Earth that does not support the direct loading of GeoTIFF's.

The addition of a KML file in the Assets download section would be very helpful.

It seems that gdal might already have this functionality (via gdal2tiles, https://developers.google.com/kml/articles/raster)

Bas

**Comment by smathermather** [comment]
Excellent idea. @pierotofy & @dakotabenjamin -- do you think this should be WebODM only, or should we put it in the upstream ODM?

**Comment by pierotofy** [comment]
I'd be cool if this was implemented upstream and then WebODM simply imported the resulting assets.

**Comment by smathermather** [comment]
Easy enough. Cool.

**Comment by pierotofy** [comment]
@basrijn are you still interested in implementing this feature? No pressure, just wanted to check the status 😄

**Comment by atoone** [comment]
This would really help sharing orthophotos with others...

**Comment by fentas** [comment]
Has anyone begun to work on this? :cat2:

**Comment by pierotofy** [comment]
Nop. Still looking for a contribution if you're intetested.

**Comment by pierotofy** [comment]
We can now raise funds to get this done using quadratic funding! https://fund.webodm.org/#/fund/2

**Comment by pierotofy** [comment]
Closing this as I don't think it's going to get implemented (unless we get a pull request).
