### ISSUE TITLE
Bump mapping might be excessive on small models

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#1260]
Especially on small scale models.

We either need a button to turn it on/off or a way to automatically tune it based on scale.

**Comment by Saijin-Naib** [comment]
It is rendered by PoTree, right?

Could we have a slider and checkbox like we do for EDL parameters? That way one can increase/decrease the intensity of the bumpmap like how iDTech game engines allow you to change bumpmap intensity

**Comment by pierotofy** [comment]
It might also be impacting memory usage. I'm turning this off until we have time to improve it. https://github.com/OpenDroneMap/WebODM/commit/3394365d4415fad9c61dabd5860a4765a7ca9f6b
