### ISSUE TITLE
Multispectral image processing fails with nodeodm:gpu if JPG images are included in data set

### ISSUE THREAD

**Issue by Johnny555555** [OpenDroneMap/WebODM#1267]
****************************************
### How did you install WebODM (docker, installer, etc.)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Mozilla Firefox 107
Ubuntu 20.04.1 LTS

System details:
WebODM 2.8.8
Docker 20.10.18
Ubuntu 22.04.1 LTS
Dual Intel Xeon 20-core CPU’s
512GB RAM
Nvidia K80 (dual 12GB GPUs)
1.8TB swap

### What is the problem?

If I process a set of multispectral images with the default multispectral settings, processing succeeds with nodeodm but fails 100% of the time with nodeodm:gpu. If the JPG images are excluded from the dataset then processing with nodeodm:gpu is successful.

When processing fails the WebODM task will display an error "Cannot process dataset. Processing failed because of strange values in the reconstruction". The detailed log shows it failed when "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/var/www/data/85e509c1-01fa-4300-ac81-926649975c78/opensfm/undistorted/images/DJI_0190.JPG.tif'", noting that the specific file it mentions changes with each re-processing attempt. 
I wonder if part of the issue is that it appears to be looking for a file with extension ".JPG.tif"...which doesn't make sense to me. It would be ".JPG" or ".tif" but not ".JPG.tif"...

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Steps to replicate specified in the problem description above.
Here's a link to the dataset (expires in 14 days):
https://1drv.ms/u/s!AnbQHcX3KX2dhbkBIiL9synMln2d4w?e=LG6StR 

Here's a link to the log files (expires in 14 days):
https://1drv.ms/u/s!AnbQHcX3KX2dhbkC85NfxHevtT2nkA?e=g0hQ5m
The log files where processing succeeded say "success" in the filename, all others were failures.

**Comment by pierotofy** [comment]
ODM as of the last few months should now be capable of handling mixed TIF/JPEG datasets without issues.
