### ISSUE TITLE
gdaladdo for downloadable TIFF

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/WebODM#127]
Should we be running gdaladdo to allow for fast viewing of geotiff for the downloadable assets from WebODM? We avoided this with ODM, as it bloats the file size, and perhaps shouldn't be default, but for an end user who is downloading the assets to a local machine, it might be nice to already have the overviews built.

**Comment by pierotofy** [comment]
I think this would be best implemented by adding a command line option in ODM (say, a boolean --build-overviews) and a user could choose it from the advanced options when starting a task.

**Comment by smathermather** [comment]
Good point.

**Comment by smathermather** [comment]
cc @dakotabenjamin

**Comment by pierotofy** [comment]
Looks like this was implemented in ODM.
