### ISSUE TITLE
Feature Request: Record GSD, Points, Area Of Reconstruction with --skip-report

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1277]
### How did you install WebODM (docker, installer, etc.)?
Docker
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Mozilla Firefox, Alpine Linux Latest-Stable
### What is the problem?
I've noticed that when using --skip-report alongside a bunch of other --skip-* parameters that the Task status after processing has completed does not show the GSD, the area of reconstruction, nor the points reconstructed.
### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
![image](https://user-images.githubusercontent.com/19295950/206962388-71137453-96d1-49ca-93e3-884e2fd747ba.png)
### Further Information
I'm making a big assumption that these metrics are available and calculated regardless of the Report generation, but I can't yet verify that as I've not followed the code through for everything successfully yet.

**Comment by pierotofy** [comment]
The current behavior is correct (although perhaps not so intuitive). The statistics that WebODM shows are part of `odm_report/stats.json`, and skip_report does not compute that file (to save time). I'd say that if one wants to see the metrics in WebODM, one should not use `skip_report`.
