### ISSUE TITLE
Area measurements wrong

### ISSUE THREAD

**Issue by A20N** [OpenDroneMap/WebODM#1281]
### How did you install WebODM (docker, installer, etc.)?

Dockerimage

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 108 Win10/11 x64

### What is the problem?

Area measurements are wrong despite correct side lengths.
Please refer to the picture below.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Measure an area

![15449 copy_clean (2)](https://user-images.githubusercontent.com/32432566/209405156-4f7cab24-06c9-4976-ba50-4e85b3fa6f44.jpg)

**Comment by pierotofy** [comment]
This should be fixed with #1435 🥂
