### ISSUE TITLE
installation issue with docker compose V2 (vs soon-to-be deprecated docker-compose)

### ISSUE THREAD

**Issue by emvollmer** [OpenDroneMap/WebODM#1295]
### How did you install WebODM (docker, installer, etc.)?

Manually - cloned the repository and ran ./webodm.sh start command

### What's your browser and operating system?

Firefox and Ubuntu 22.04

### What is the problem?

Docker Compose has been [upgraded to version 2](https://github.com/docker/compose/tree/v2), where the name is no longer hyphenated. Due to this, at minimum the bash script for starting webodm won't work, as it searches for (and tries to install) `docker-compose`. According to [docker's website](https://docs.docker.com/compose/), `docker-compose` will be deprecated as of June this year (2023) and removed from all docker desktop versions. Also, according to the Docker Desktop application itself, it now only ships with Docker Compose V2.

Additional versioning information:
```
$ docker --version
Docker version 23.0.1, build a5ee5b1
$ docker desktop --version
Docker version 23.0.1, build a5ee5b1
$ docker compose version
Docker Compose version v2.15.1
```

### How can we reproduce this?

(Re-)Install docker desktop and with it automatically docker compose. Then try to run `./webodm.sh` or alternatively, simply check `docker compose version` vs `docker-compose --version`, the second of which will return a "command not found" error.

**Comment by kikislater** [comment]
+1 
docker-compose is not availaible anymore in Debian 11 for example. PR is easy to do IMO ...
