### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/WebODM#130]
Perhaps this comes for free with Django, but we should start thinking about localization support for WebODM.

**Comment by pierotofy** [comment]
Django has a built-in localization support. We'll need to find something for React.

**Comment by smathermather** [comment]
👍

**Comment by pierotofy** [comment]
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/

https://github.com/yahoo/react-intl

**Comment by pierotofy** [comment]
Done! :clinking_glasses:
