### ISSUE TITLE
Record Video Button

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#1309]
Would be neat to have a "Record video" button to capture Potree visualizations.

https://github.com/spite/ccapture.js/

Maybe added as a plugin.

**Comment by pierotofy** [comment]
https://stackoverflow.com/questions/50681683/how-to-save-canvas-animation-as-gif-or-webm

**Comment by smathermather** [comment]
I love that your bot flagged this. 😆 

Love the feature. Super useful and commonly asked for.
