### ISSUE TITLE
Bug: Cloud Import Plugin Broken

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1325]
### How did you install WebODM (docker, installer, etc.)?
Docker Engine

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Alpine Linux latest-stable x86_64, Mozilla FireFox v109.0.1

### What is the problem?
The Cloud Import function (Github, can't test PiwiGo with no account) fails to import any data, throwing errors in the docker console and never progressing past Importing...

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Error log:  
```
worker      | INFO Will import 18 files
worker      | [2023-04-03 15:44:06,820: INFO/ForkPoolWorker-1] app.plugins.worker.eval_async[711a7af8-cb51-4a4a-95bc-06d71dc94432]: Will import 18 files
worker      | [2023-04-03 15:44:06,843: ERROR/ForkPoolWorker-1] Task app.plugins.worker.eval_async[711a7af8-cb51-4a4a-95bc-06d71dc94432] raised unexpected: NameError("name 'path_traversal_check' is not defined")
worker      | Traceback (most recent call last):
worker      |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 385, in trace_task
worker      |     R = retval = fun(*args, **kwargs)
worker      |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 650, in __protected_call__
worker      |     return self.run(*args, **kwargs)
worker      |   File "/webodm/app/plugins/worker.py", line 29, in eval_async
worker      |     return ns[funcname](*args, **kwargs)
worker      |   File "file", line 22, in import_files
worker      |   File "file", line 7, in download_file
worker      | NameError: name 'path_traversal_check' is not defined
```

Docker information:  
```
docker images
REPOSITORY                   TAG       IMAGE ID       CREATED         SIZE
opendronemap/webodm_webapp   latest    b51f469f0c23   10 hours ago    1.64GB
opendronemap/nodeodm         latest    bbae585e7ba3   29 hours ago    1.94GB
redis                        latest    31f08b90668e   11 days ago     117MB
opendronemap/webodm_db       latest    e40c0f274bba   19 months ago   695MB
```
![image](https://user-images.githubusercontent.com/19295950/229561175-ce1f732d-2986-40ba-a148-7d5d0718bc8b.png)

**Comment by pierotofy** [comment]
Nice catch, should be fixed with https://github.com/OpenDroneMap/WebODM/commit/4bd0e0f198a3a465612e34fc7f24186d76f0603d :+1:
