### ISSUE TITLE
addon: show CPU usage + Email notifications

### ISSUE THREAD

**Issue by pete1019** [OpenDroneMap/WebODM#1341]
Hi, would this be of interest? Should i provide a PR where the CPU Usage is also in diagnostic?

Had this issue where the CPU was at 3% but the project was still on working but it actually wasn't.
Think it was because there were pictures of a different project accidentally.

I thought of extending this with a plugin for email notification:

- on finish
- on error
- on low threshold CPU usage for quite some minutes.

Also, a checkmark in diagnostic to auto-refresh every X seconds.

What do you think?

**Comment by pierotofy** [comment]
It might be useful to have a CPU indicator, yes! But might be tricky to get an accurate value that is cross-platform without additional dependencies.

An e-mail plugin would be most interesting!

**Comment by Kathenae** [comment]
@pierotofy I'm working on the email notification plugin right now, I've managed to find the plugin signal for when a task has finished processing, but there doesn't seem to be one for when a task has failed? Any idea if such a signal exists if no, do you know the main points where a task may fail to process so i can send the plugin signal?

**Comment by pierotofy** [comment]
Yep, there's currently no "task_failed" signal. It could be added though. See `app.plugins.signals.py` and `app.models.task`.

**Comment by Kathenae** [comment]
Ohh alright, thanks!

**Comment by pierotofy** [comment]
Done with #1343, #1344 :partying_face:
