### ISSUE TITLE
Run WebODM natively

### ISSUE THREAD

**Issue by paulinK** [OpenDroneMap/WebODM#135]
Hello
I'am a ftench speaker.
I'am new on WebODM. I have try to run WebODM nativily but it failed. And I don't know why. My question is that:
Can I get a tutorial about running WebODM natively ?

**Comment by pierotofy** [comment]
Hi @paulinK,

did you try to follow the instructions written here? https://github.com/OpenDroneMap/WebODM#run-it-natively

**Comment by paulinK** [comment]
Thank you @pierotofy .
But it dosen't work . i triée it

**Comment by paulinK** [comment]
Can I get another link ?
Thank you

**Comment by pierotofy** [comment]
@paulinK where exactly do you get stuck in the process? There's no other documentation at the moment.

**Comment by paulinK** [comment]
Ah ok. I will post thé errors when i will on my computer.
Thank you again.

**Comment by pierotofy** [comment]
Will close this unless there are further questions.
