### ISSUE TITLE
Issue when mapping video footage with mavlink data.

### ISSUE THREAD

**Issue by 0578Tex** [OpenDroneMap/WebODM#1352]
### How did you install WebODM (docker, installer, etc.)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Edge 113 on Windows 11]
web odm is installed on ubuntu20 server

### What is the problem?

I'm trying to create a map with a drone feed, and separate provided geo data through MAVLINK which I supply to webodm though a geo.txt file. However, when I try to create a map, the image is blurry and offset +- 5 meters to the west, while the coordinates are correct (checked with google maps). What could be the issue? When making a map without the geo data, the image looks way better.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

The mavlink data looks like this: 

{"ATTITUDE": {"mavpackettype": "ATTITUDE", "time_boot_ms": 0, "roll": -0.017000000923871994, "pitch": 0.04699999839067459, "yaw": -0.028999999165534973, "rollspeed": 0.0, "pitchspeed": 0.0, "yawspeed": 0.0}, "POSITION": {"mavpackettype": "GLOBAL_POSITION_INT", "time_boot_ms": 0, "lat": 303179016, "lon": 780397796, "alt": 759799, "relative_alt": 74700, "vx": 0, "vy": 0, "vz": 0, "hdg": 0}, "CAMERA": {"mavpackettype": "CAMERA_FOV_STATUS", "time_boot_ms": 0, "lat_camera": 0, "lon_camera": 0, "alt_camera": 0, "lat_image": 303186259, "lon_image": 780397469, "alt_image": 665000, "q": [0.9999783635139465, -1.3762515891357907e-06, -0.006571117322891951, -0.0002094349911203608], "hfov": 6.489999771118164, "vfov": 0.0}, "Time": 1685701212.122587}
Which comes with a mp4 file, and a start time of the video. Right now I take a specific frame and supply it with the geo coordinates.

The geo.txt flie looks like this:
0.5800011157989502.PNG    78.0397644    30.3179016    74.8    1.576170669573772e-15    -0.01473057932977135    -0.00012217304569326373
Where I translated the q into yaw pitch roll.

The result:
![Screenshot 2023-06-14 130938](https://github.com/OpenDroneMap/WebODM/assets/104349767/7859f054-3b1a-4db9-9286-81e2b7bbcac3)

The result when not supplying geo data:
![Screenshot 2023-06-14 130952](https://github.com/OpenDroneMap/WebODM/assets/104349767/4ddfed9e-9761-4007-ad97-d9db69fe160e)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
