### ISSUE TITLE
Update the Docker compose installer to use Docker compose plugin

### ISSUE THREAD

**Issue by SnorreSelmer** [OpenDroneMap/WebODM#1359]
### How did you install WebODM (docker, installer, etc.)?

Docker compose

### What's your browser and operating system?

Chrome 114 on Windows 11

### What is the problem?

The installer-script currently uses the old `docker-compose` executable instead of the new `docker compose` syntax. While this doesn't break anything _yet_, it's likely to become a problem later. Might as well have the script try the new syntax and then fall back on the executable it that fails.

**Comment by pierotofy** [comment]
When you say "installer-script", which are you referring to? `webodm.sh` already uses `docker compose`.
