### ISSUE TITLE
node-odm-1 exited with code 1

### ISSUE THREAD

**Issue by gkconsulting** [OpenDroneMap/WebODM#136]
Hi, 
I have been trying to get Web ODM to run on a windows machine with Docker. 
I have followed the instructions and I can get into the interface however then I try to set a processing node I get a message saying "node-odm-1:3000 seems to be offline. "
On the terminal i get this error "error:Error during startup: Could not load list of options from OpenDroneMap. Is OpenDroneMap installed in /code? Make sure that OpenDroneMap is installed and that --odm-path is set properly: Unexpected token T in JSON at position 0"

Is there a step that I am missing? I have followed the instructions on this link "https://github.com/OpenDroneMap/WebODM"
Thanks in advance.
GK

**Comment by pierotofy** [comment]
Hi, our docker builds were broken yesterday due to a major update. Could you please try to run the following:

```
./webodm.sh update
./webodm.sh start
```

And see if that fixes the problem?

**Comment by gkconsulting** [comment]
Thanks, 
Will give it a try and let you know. 
Thanks so much for the quick response
GK

**Comment by gkconsulting** [comment]
Thanks that did the trick. 
Thanks for all the hard work :-)

**Comment by pierotofy** [comment]
Glad it worked! 😄 

Feel free to give us feedback once you are done checking out the project.
