### ISSUE TITLE
Cannot change the size of disk storage (default = 1TB)

### ISSUE THREAD

**Issue by jamescball55** [OpenDroneMap/WebODM#1360]
The issue can be found on the WEBODM forum. Here is the link.

https://community.opendronemap.org/t/still-cannot-change-disk-storage/16545

**Comment by pierotofy** [comment]
Hey @jamescball55 :wave: I've read the thread on the forum, and this really looks like a system issue with WSL/docker, so unfortunately there's not much we can fix on the WebODM side. (I know they pointed you to open an issue here, but unfortunately it's not a bug WebODM can solve). 🙏
