### ISSUE TITLE
Exif tags reading error

### ISSUE THREAD

**Issue by arpitpara** [OpenDroneMap/WebODM#1362]
HI
I have already discussed this issue about my dataset on community platform.
I've not get any solution for the same. I am sure this problem is particular to WebODM and EXIF reading python package.
Can you give me a solution of this?
https://community.opendronemap.org/t/processing-error-with-rfly/16683

**Comment by pierotofy** [comment]
Thanks for sharing a dataset @arpitpara 🙏 this should be fixed with https://github.com/OpenDroneMap/ODM/pull/1677

**Comment by arpitpara** [comment]
Should I update my webodm to get this fix?..
I bought windows license of it.

**Comment by pierotofy** [comment]
You'll need to wait until an update for the Windows native version is released. If you're in a hurry, you can always make the modifications to `photo.py` manually by seeing what changed here https://github.com/OpenDroneMap/ODM/pull/1677/files

**Comment by arpitpara** [comment]
Thanks for the update!
i know it's quite unprofessional way to ask to release a build early. But as a user I want to make request just consider it as ew need it quite soon.
