### ISSUE TITLE
Update checkout action on workflows

### ISSUE THREAD

**Issue by chris-bateman** [OpenDroneMap/WebODM#1379]
### Update actions/checkout from v2 to v3
This resolves this warning - 
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

https://github.com/OpenDroneMap/WebODM/blob/f1b358db44b7db2e87e90d6c9f0f2f7ef4ea6b92/.github/workflows/build-and-publish.yml#L15
PR - #1381

https://github.com/OpenDroneMap/WebODM/blob/f1b358db44b7db2e87e90d6c9f0f2f7ef4ea6b92/.github/workflows/build-docs.yml#L15
PR - #1380

https://github.com/OpenDroneMap/WebODM/blob/f1b358db44b7db2e87e90d6c9f0f2f7ef4ea6b92/.github/workflows/test-docker.yml#L10
PR - #1378

**Comment by pierotofy** [comment]
Thanks @chris-bateman !
