### ISSUE TITLE
ERROR: for webapp

### ISSUE THREAD

**Issue by ITPrincis** [OpenDroneMap/WebODM#138]
Hello,

I tried to start WebODM like Dennis shown in youtube video, however I ran into some problems:

terminal shows:
ERROR: for webapp  No such image: sha256:c7046a00c84fb4fc2f7d8faa9ebba55d88e7ae813e5e3dbf0231bbd964ba9df0
ERROR: Encountered errors while bringing up the project.
<img width="1423" alt="screen shot 2017-04-05 at 13 12 29" src="https://cloud.githubusercontent.com/assets/5454766/24700983/914a90d0-1a01-11e7-90a0-3a03ec469bf1.png">

**Comment by pierotofy** [comment]
Hi @ITPrincis , thanks for reporting the issue.

Have you ever been able to launch webodm? 

I would try to do a `docker-compose build --no-cache webapp` from the WebODM directory and try again.

**Comment by ITPrincis** [comment]
Hi,

no I'm new to this. I haven't launched it yet, but I'm about to do it.
Ok, so it created webodm_webapp image.

How can I run it?
Where can I see what ip is local server running on?

Big thanks!
<img width="749" alt="screen shot 2017-04-05 at 20 59 52" src="https://cloud.githubusercontent.com/assets/5454766/24719566/dcde4e2e-1a42-11e7-92f2-c7466f5aefdb.png">

**Comment by ITPrincis** [comment]
@pierotofy 
When I run ./devenv.sh start
then this shows again:
<img width="750" alt="screen shot 2017-04-05 at 21 09 51" src="https://cloud.githubusercontent.com/assets/5454766/24720002/645de494-1a44-11e7-8884-d392e3f15bea.png">

**Comment by pierotofy** [comment]
Something does not look right. I'm not sure what commands you've typed, but if you started from a fresh installation, all you need to type is:

```
git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input
cd WebODM
./webodm.sh start
```

I would try to clean things up and start over...

```
docker stop $(docker ps -q)
docker rm $(docker ps -aq)
./webodm.sh rebuild
./webodm.sh start
```

You don't need to use `devenv.sh` unless you plan to edit the source code.

**Comment by ITPrincis** [comment]
@pierotofy Started fresh and everything went well. No errors. Thanks!
