### ISSUE TITLE
ClusterODM with S3 output

### ISSUE THREAD

**Issue by rockliffelewis** [OpenDroneMap/WebODM#1385]
### How did you install WebODM (docker, installer, etc.)?

We have WebODM setup in a docker locally and its interacting with a ClusterODM backend running in AWS using automatic provisioning and storing the results on S3.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Chrome 116 on Windows 10

### What is the problem?

At the end of the processing workflow the WebODM task fails to complete, it looks like the actual processing completes and the job results are stored in the S3 bucket as configured.

Is this a supported workflow? or does WebODM expect the results to be handed back to the web interface to finish off the task.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

set up webodm with clusterodm storing results to s3, submit any job.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
