### ISSUE TITLE
One Click Installer

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#14]
Although this is something to do toward the end, the Docker command line is still too confusing for many GIS technicians; there's going to be a need for a graphical installer.

**Comment by Bavar2142** [comment]
To be honest with you while not as unfamiliar as I once was with the command line the fewer steps there are between the user and the end result the better. Ie the more parts a machine has the more parts that can break.

**Comment by pierotofy** [comment]
This is now available at http://www.webodm.org/download
