### ISSUE TITLE
Issue connecting browser to WebODM

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#140]
@pierotofy 

Long time Sir.  When I start WebODM via Docker then attempt to open via browser its not connecting.  I'm sure I'm missing something simple here...  I did see the "Starting development server at http://0.0.0.0:8000/???

Thanks,
Anthony

![webom_started](https://cloud.githubusercontent.com/assets/25381671/24831140/c7b243fc-1c59-11e7-8098-fc643d92a869.JPG)

![webom_started2](https://cloud.githubusercontent.com/assets/25381671/24831169/4633c3cc-1c5a-11e7-9e72-7c754021b074.JPG)

**Comment by pierotofy** [comment]
Hello Anthony,

What is the output of `docker-machine ip`?

Also perhaps an obvious thing to try, but have you tried to restart your computer?

**Comment by AnthonyCoughlin** [comment]
@pierotofy 

see below.  Yes restarted both the machine and the docker.

![docker_ip](https://cloud.githubusercontent.com/assets/25381671/24832781/0587a49c-1c7d-11e7-9e63-1bfb6c6b19fa.JPG)

**Comment by pierotofy** [comment]
I found this while searching online. http://www.hanselman.com/blog/FixedMicrosoftEdgeCantSeeOrOpenVirtualBoxhostedLocalWebSites.aspx

Does it help at all your case?

**Comment by AnthonyCoughlin** [comment]
Hmmm, testing Firefox now.  Thanks.

**Comment by AnthonyCoughlin** [comment]
@pierotofy 

Saved my life again my friend.  I was running the all powerful Microsoft Edge and it would not connect.

**Comment by pierotofy** [comment]
Glad it worked!

I've added a note in the readme for future reference. Thank you for reporting the problem!
