### ISSUE TITLE
exit with code 1

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#141]
@pierotofy 

I'm experiencing the 'exited with code 1' message.  Running a task with 118 photos trying to make a 3D model.  I also included the docker cmd line.  Is this a memory issue with docker?  Any ideas?

![webom_error](https://cloud.githubusercontent.com/assets/25381671/24834815/17bf0460-1cb5-11e7-809f-08cf30e327dc.JPG)

![webom_docker_error](https://cloud.githubusercontent.com/assets/25381671/24834902/70f79388-1cb7-11e7-8a75-3cf69ce96186.JPG)

**Comment by AnthonyCoughlin** [comment]
I'm getting the same errors listed above on three separate data sets.

**Comment by pierotofy** [comment]
Hard to say what the problem would be from just the error logs posted; yes please if you could upload the images that would be awesome!

**Comment by AnthonyCoughlin** [comment]
@pierotofy 

https://drive.google.com/open?id=0B4Tf0aIvxRLJTnpKOWlsU3ZaN2c

This is what I'm working with now.

**Comment by AnthonyCoughlin** [comment]
@pierotofy 

Just received this error.  Its as if its getting hung up...

![webom_nodeoffline_error](https://cloud.githubusercontent.com/assets/25381671/24839763/40bbee02-1d26-11e7-9ecc-aba4fd309880.JPG)

Hopefully this helps.

**Comment by pierotofy** [comment]
I was able to process the dataset without errors with the default settings.

![image](https://cloud.githubusercontent.com/assets/1951843/24839869/3f8c38b6-1d30-11e7-8231-11c200f4b259.png)

![image](https://cloud.githubusercontent.com/assets/1951843/24839871/43abebbc-1d30-11e7-8d1f-87318f5b5c53.png)

Have you allocated enough memory to your processing node? Is there enough disk space?

**Comment by AnthonyCoughlin** [comment]
Man...  Mine is still running.  I've got plenty of disk space.  Would you mind providing a link to documentation on the proper memory allocation for webodm.  Thanks for the help.

**Comment by AnthonyCoughlin** [comment]
Is is safe to manipulate the memory settings for the default docker machine from the VirtualBox UI?

**Comment by smathermather** [comment]
@AnthonyCoughlin -- modifying the memory settings is definitely recommended. Defaults tend to be too small.

**Comment by AnthonyCoughlin** [comment]
@smathermather 

Understood, thanks.  With that said, could you tell me where I can find documentation as to how one would set the memory, processors, etc. per the physical machine specs?  I've been reading but have been unable to find anything definitive.

Thanks again @pierotofy and @smathermather

**Comment by pierotofy** [comment]
Documentation for recommended settings is a work in progress. For now, you'll have to to a trial and error approach.

**Comment by pierotofy** [comment]
I'll close this for now unless there are further questions.
