### ISSUE TITLE
GPU not working during `DensifyPointCloud`

### ISSUE THREAD

**Issue by lupionpe** [OpenDroneMap/WebODM#1410]
### How did you install WebODM (docker, installer, etc.)?

Docker

### What's your browser and operating system?

Firefox 115 on Linux

### What is the problem?

I am running WebODM in a Debian Linux with a GPU installed (NVIDIA GeForce RTX 2080 Ti).

When running OpenMVS/DensifyPointCloud is showing `--cuda-device -1` what I am assuming from reading other posts that it should use the GPU, but as you can see, GPU is not working.

<img width="1438" alt="image" src="https://github.com/OpenDroneMap/WebODM/assets/65565211/9ed0065a-a70c-499d-8910-ef8d1ee17251">

I followed the installation of the GPU from **OpenDroneMap: The Missing Guide - Second Edition** and I ran `./webodm.sh --gpu`.

Is this an expected behavior or is something I missed?

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

- The data set I used is in this link: https://drive.google.com/drive/folders/1mLkKJqyFgJQshb01NPnwuu69SQrYhJ8W
- The parameters I used are:
```
auto-boundary: true, crop: 5, dsm: true, gps-accuracy: 0.2, matcher-neighbors: 200, mesh-octree-depth: 12, mesh-size: 300000, min-num-features: 80000, orthophoto-resolution: 1, pc-quality: ultra, pc-rectify: true, pc-sample: 0.05, rolling-shutter: true, rerun-from: dataset
```
cc: @felupion

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
