### ISSUE TITLE
Image Processing - problems related with memory.

### ISSUE THREAD

**Issue by Kalondepatrick** [OpenDroneMap/WebODM#1414]
****************************************
I am processing nearly 500 images using WebODM and the processing does not get completed on condition that there is not enough memory space (as in the screenshot below). I am not sure why this problem is popping up, and I need assistance. Below are the details of my system:

Computer: Dell Alienware (32 GB RAM)
Platform used for Running WebODM: Docker Desktop

<img width="646" alt="OpenDroneMap" src="https://github.com/OpenDroneMap/WebODM/assets/39599487/933cb088-3a84-47ed-8683-62c675fe91da">
](url)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
