### ISSUE TITLE
SQL exception when adding a user with a quota

### ISSUE THREAD

**Issue by argoopen** [OpenDroneMap/WebODM#1416]
### How did you install WebODM (docker, installer, etc.)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Client: Firefox latest (118.0.1); MacOS Ventura
Server: Alma Linux 9

### What is the problem?

I've tried installing twice on two separate servers via Docker, and under both instances whenever I add a new user account with a quote other than -1 I see an error: 500 Internal Server Error. Something happened. The server logs contain more information.

I see no issues when adding an account without a quota (quota = -1).

Updating a user's quote after adding the account works as expected.

In my logs I see a Postgres SQL exception:

ERROR:  duplicate key value violates unique constraint "app_profile_user_id_key" 
db                 | DETAIL:  Key (user_id)=(9) already exists. 
db                 | STATEMENT:  INSERT INTO "app_profile" ("user_id", "quota") VALUES (9, 500.0) RETURNING "app_profile"."id"

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

 - click 'Administration'
 - click 'Accounts'
 - click 'Add user'
 - enter username and password
 - enter any positive value for Quote (eg 500, or 1000)
 - click any of the Save buttons (Save and add another, Save and continue editing, or SAVE)

**Comment by pierotofy** [comment]
Thanks @argoopen :pray: this should be mitigated as part of #1559, we now hide the "quota" field during user creation (it can be edited after creating the user). The django admin's functionality doesn't seem able to handle editing of fields during user creation that have been setup the way we have (with a User <=> Profile 1:1 relationship).
