### ISSUE TITLE
Negative values in bands after calibration image?

### ISSUE THREAD

**Issue by ambarja** [OpenDroneMap/WebODM#1418]
Hello, I have recently been using images from the **Phantom 4 multispectral** with webodm, however when I perform the ND calibration to surface reflectance values with the :

 - Camera
 - Camera + sun

I have **negative value in the calibration bands**, this is very strange because the reflectance value is 0 - 1, right?
For this process I have been using [WebODM Lightning](https://webodm.net/)

Finally here put my image set used:
- [Set of P4M imagenes](https://drive.google.com/drive/folders/1piCcMsSKvpqWkcXIQ8Xp9IQ5OcTh7AT1?usp=share_link)

Here an example of the green band
![image](https://github.com/OpenDroneMap/WebODM/assets/23284899/16bfd786-f9d0-4d69-a7aa-9efce7868b8c)

**Comment by pierotofy** [comment]
Did you set `texturing-skip-global-seam-leveling` while processing?

**Comment by ambarja** [comment]
Hi @pierotofy , Thanks very much , I solved my error with this parameter. 
I close this issue for now.
![image](https://github.com/OpenDroneMap/WebODM/assets/23284899/1a7e14a1-ae7d-4b05-b7f9-4eee8d082967)
