### ISSUE TITLE
Wrong area measurement

### ISSUE THREAD

**Issue by Wilbodakwerken** [OpenDroneMap/WebODM#1421]
### How did you install WebODM (docker, installer, etc.)?

business installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[[Chrome 118 on Windows 11](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

### What is the problem?

area measurement is not correct

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

When vertrical erea measurement is taken the oudput is not correct. 
For example i have a maesurement of 6,80m wide with a hight of 3,70m. This should give 25,16m². the software give me only 0,4m².

second example, a sloped roof thats 10,64m wide and 8,01 lenght it should be 85,23m², software tells me 77,2m²

**Comment by Wilbodakwerken** [comment]
calculate the m² with the measurement and angels? 
below the screenshots, measurements are correct, m² isnt. 

![image](https://github.com/OpenDroneMap/WebODM/assets/148749278/5a9d173e-6fc0-42f1-a604-441e11cc7b3a)
![image](https://github.com/OpenDroneMap/WebODM/assets/148749278/e6dfe99a-7c48-43ea-9441-0c787ac28239)

**Comment by pierotofy** [comment]
Should be fixed with #1435, thanks for the report! 🙏 

Note that it might take a few weeks before an update is released for Windows, so this fix will not be available right away.
