### ISSUE TITLE
Orthophoto preview in quality report?

### ISSUE THREAD

**Issue by ambarja** [OpenDroneMap/WebODM#1422]
Hello WebODM community, lately I am trying to understand the meaning of the report, but I don't understand the meaning of the orthophoto preview.
Do you have any idea why it comes out all black and how I should understand this, is there a technical background? 
Regards

![image](https://github.com/OpenDroneMap/WebODM/assets/23284899/526361f2-5435-438e-bd8c-9b97ab12af87)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
