### ISSUE TITLE
shots.geojson

### ISSUE THREAD

**Issue by ac416** [OpenDroneMap/WebODM#1425]
I would like to know the meaning of the "rotation" parameter in the camera parameter file, or what it stands for.

<img width="699" alt="77d9213328d8ceda84cda20143e448d" src="https://github.com/OpenDroneMap/WebODM/assets/97585208/51662639-fcd8-4878-a2d2-142d8d99a990">

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
