### ISSUE TITLE
Possible Bug: Failure to import 9.3GB all.zip

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/WebODM#1428]
### How did you install WebODM (docker, installer, etc.)?
Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
FireFox 119.0, Alpine Linux Edge x86_64

### What is the problem?
Import of 9.3GB zip archive routinely fails at about exactly 2GB imported.

This is 100% repetable in the FireFox browser.

Underlying FS can handle large files, archive is consistent as reported by XArchiver, connection is stable, disk speed is good (550MBPS+).

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)
Link to file used:  
https://community.opendronemap.org/t/error-while-trying-to-apply-textures-to-model/18074/8?u=saijin_naib

Logs: Attached
[consolelog.log](https://github.com/OpenDroneMap/WebODM/files/13316599/consolelog.log)
[dockerlogs_webapp.log](https://github.com/OpenDroneMap/WebODM/files/13316602/dockerlogs_webapp.log)
[dockerlogs_worker.log](https://github.com/OpenDroneMap/WebODM/files/13316606/dockerlogs_worker.log)
[webodm_firefox_inspector.log](https://github.com/OpenDroneMap/WebODM/files/13316607/webodm_firefox_inspector.log)

**Comment by pierotofy** [comment]
Does this still happen? We now support chunked uploads on import, so this is *probably* fixed. 

Feel free to re-open if the issue persists.
