### ISSUE TITLE
To error report I mentioned, feel free to let me know where to upload the data so I can upload it. Thanks

### ISSUE THREAD

**Issue by duiveldoder** [OpenDroneMap/WebODM#1449]
Yeah I read it but how can I upload the dataset if everything is automatically blocked and banned?

Please let me know where to upload the data to my bug report.

**Comment by pierotofy** [comment]
When you open a bug report:

> If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app/)

Feel free to open a new one.
