### ISSUE TITLE
Uploading of images fails after around 4:30

### ISSUE THREAD

**Issue by Baptist01** [OpenDroneMap/WebODM#1455]
### How did you install WebODM?

Docker

### What's your browser and operating system? 

[Chrome 120 on Windows 11](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

### What is the problem?

I want to upload images to webODM from my own C# .net application using the [api](https://docs.webodm.org/) but after around 4:30 the uploading of the images fails with the error:
System.Net.Http.HttpRequestException: Error while copying content to a stream.
---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

Everything goes well and works perfectly till it hits the mark of ~4:30(4:30 is not perse a reference because I have times it at 4:10 but also at 5 min). When the uploading is done earlier everything will continue fine as expected.

I have excluded and investigated a few possible options of why it would fail:
- When I put a delay in uploading the images it still fails around ~4:30 min, so even when there are only 6 images uploaded because of a Delay I used.
- When uploading the same images directly from webODM it doesn't fail.
- When using fiddler in the background to check what goes wrong with the calls everything goes correct and there is NO problem even after 4 min 30 sec so this would solve the problem except I don't want to always have to use this. 
- After it fails to upload the calls, the call to start the processing does still work but it just doesn't upload the images anymore.
- When the images stop uploading to because of this error all the images that are uploaded can be mapped correctly so they are received correctly.

The hoped result would be that the uploading of the images continues also after the 4:30 mark.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

The main trigger is the time it takes to upload all the images to webODM
In my initial try to upload all the images I used all the documentation described here: https://docs.webodm.org/ But after that didn't work with the same issue I have now. I tried to use the calls that are used by the webODM frontend like in the images below.

This is the initial call I make to create a tasks:
<img width="386" alt="image" src="https://github.com/OpenDroneMap/WebODM/assets/99185216/4cc4ae8f-7256-4d88-8ad1-5564bc900e3f">

This is the call I make to 
<img width="434" alt="image" src="https://github.com/OpenDroneMap/WebODM/assets/99185216/895d4aed-532d-41dc-9650-0ed384252334">

This is the call I make to start the processing:
<img width="389" alt="image" src="https://github.com/OpenDroneMap/WebODM/assets/99185216/36ed6e11-7920-422e-b635-f1c35d07f946">

Has anyone experience with this issue? or do you know what causes this? I was also wondering if WebODM supports more advanced ways of uploading? instead of just using POST request.
Thank you so much for your help already! If you have any questions feel free to let me know!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
