### ISSUE TITLE
"DroneDB plugin error".

### ISSUE THREAD

**Issue by EFPDroneFootage** [OpenDroneMap/WebODM#1456]
### How did you install WebODM (docker, installer, etc.)?

Via windows install. Also WebODM Lightning. 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

 Chrome 120 on Windows 11

### What is the problem?

Everytime I try to use the "Share to DroneDB" in WeboDM it fails with "DroneDB plugin error".

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

By having the DroneDB plugin activated, then being in the WebODM dashboard, selecting the task drop down, and where we see options such as Open Map, we see the Share to Drone DB button, this when pressed begins an action, sends a few KBs of data over to DroneDB, then says it has an error which reads - Error uploading file odm_report\shots.geojson: Failed to upload file.
![DroneDB error](https://github.com/OpenDroneMap/WebODM/assets/155225266/b630b09e-6c05-42a2-91c4-6d77ae5fbf14)

Next is the DroneDB datasets that keep stopping after being uploaded via webodm

**Comment by EFPDroneFootage** [comment]
![dronedb](https://github.com/OpenDroneMap/WebODM/assets/155225266/7e5827a5-8774-4b94-9dbc-5f9c8118c381)

**Comment by pierotofy** [comment]
cc @HeDo88TH

**Comment by EFPDroneFootage** [comment]
Do I need to find WebODM Lighning desktop version 3 as I am on 2 now upgraded from 1.9 with the error and now I see the dev team has made a version 3 and ironed out the DroneDB issue but I can only find V2 in teh cloud site via WebODM.net somewhere but if you have a v3 where would I find it to install that and see if that works the DroneDB share button?

**Comment by EFPDroneFootage** [comment]
> Do I need to find WebODM Lighning desktop version 3 as I am on 2 now upgraded from 1.9 with the error and now I see the dev team has made a version 3 and ironed out the DroneDB issue but I can only find V2 in teh cloud site via WebODM.net somewhere but if you have a v3 where would I find it to install that and see if that works the DroneDB share button?



> cc @HeDo88TH


Do I need to find WebODM Lighning desktop version 3 as I am on 2 now upgraded from 1.9 with the error and now I see the dev team has made a version 3 and ironed out the DroneDB issue but I can only find V2 in teh cloud site via WebODM.net somewhere but if you have a v3 where would I find it to install that and see if that works the DroneDB share button?

**Comment by pierotofy** [comment]
The WebODM Lightning Desktop version hasn't been updated in a while. A workaround in the meanwhile could be to use the cloud platform at https://webodm.net/cloud.

**Comment by EFPDroneFootage** [comment]
When I buy the full install in January, will all my databases and links to
my client facing sharing server still be in place within it and if so I am
happy to wait to get to the updated version in Jan and then take it all
from there? Thank you for the advice and info. I love what you all do.

**Comment by pierotofy** [comment]
This *might* have been fixed with the latest version.

If not, contact https://dronedb.app/contact for a time estimate on a fix.
