### ISSUE TITLE
DJI M3E Multispectral - Blue orthophoto

### ISSUE THREAD

**Issue by danieldobosi** [OpenDroneMap/WebODM#1461]
### How did you install WebODM (docker, installer, etc.)?

both standalone on linux and lightning.
linux version: WebODM 2.4.1

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Edge 120 on Windows 10

### What is the problem?

When processing a full DJI M3E Multispectral dataset, the RGB orthophoto is blue

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

process these datasets to reproduce
https://e38surveysolutions.com/blogs/news/mavic-3-multispectral-data
https://www.pix4d.com/dji-mavic-3-multispectral-dataset/

parameters: “radiometric-calibration: camera” 

screenshots
![image](https://github.com/OpenDroneMap/WebODM/assets/86719789/e2022849-89d3-493f-8bdf-3755c7b316a5)
![image](https://github.com/OpenDroneMap/WebODM/assets/86719789/eea6b61d-6ee3-455d-8c41-c1def5f9c58d)

**Comment by pierotofy** [comment]
Seems the same issue as #1445

**Comment by pierotofy** [comment]
Yes, that's because ODM will currently drop the JPG images and only keep G, R, NIR and Re. 

I'm working on a potential fix, I will share in the upcoming days..

**Comment by pierotofy** [comment]
Ref: https://github.com/OpenDroneMap/ODM/pull/1740

**Comment by smathermather** [comment]
Let us know if this isn't resolved with https://github.com/OpenDroneMap/ODM/pull/1771 and we can re-open. Thanks for reporting!

**Comment by danieldobosi** [comment]
unfortuntately still blue:

<img width="526" alt="image" src="https://github.com/user-attachments/assets/2313f277-260e-4c66-a24c-731216c6ceb0">

I've also restarted two different datasets, same results

**Comment by pierotofy** [comment]
The JPGs are still being dropped. See discussion on https://github.com/OpenDroneMap/ODM/pull/1771#issuecomment-2197639872
