### ISSUE TITLE
Misalignment of NIR Bands (DJI 3M MS imagery)

### ISSUE THREAD

**Issue by usman-rind** [OpenDroneMap/WebODM#1462]
https://github.com/OpenDroneMap/WebODM/assets/60088877/3401e6b1-9c0a-4d00-b731-bf84ffea7ae1

We are using DJI Mavic 3 M and stitching multispectral images but the bands of the stitched image are not aligned as you can see in the attached video.

could you please help why this is happening and how can we fix that?

we further tested stitching on the Pix 4d Fields and there is no misalignment within the bands.

**Comment by funny000** [comment]
Hi@usman-rind ,
Can you solve the problem ?

**Comment by smathermather** [comment]
@funny000 -- alignment should be fixed as of a few weeks ago. Please update to the latest and test. Thanks!
