### ISSUE TITLE
OpenAerialMap Upload Bug

### ISSUE THREAD

**Issue by vdroners** [OpenDroneMap/WebODM#1464]
### How did you install WebODM (docker, installer, etc.)?

Linux Mint OS
Docker 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

odd plugin bug?

accessing the ODM i can share via directly with the ip connection. but using my dns connection it doesnt show up?

Also if i import a previous task from a zip file it doesnt show the share button as well.

Ip vs DNS address

It also hangs on uploading after i uplaod one or two maps to OpenAerialMap

I.E. after i upload one i have to refresh the key with a new one and clear the datum im the plugin manager to uplaod a new one. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

![Screenshot 2024-01-26 083757](https://github.com/OpenDroneMap/WebODM/assets/150982290/d7fe08b5-f25d-4501-8c6e-ab636c62da19)

if you need anything further let me know.

**Comment by pierotofy** [comment]
This should be now fixed. Thanks for the report!
