### ISSUE TITLE
3d page screen on smartphone 

### ISSUE THREAD

**Issue by kemaluzel** [OpenDroneMap/WebODM#1470]
When the webodm 3D model page is opened with the Chrome browser on the smartphone, the buttons such as share and 2D at the bottom right do not appear on the screen. The page cannot be scrolled down manually.

**Comment by kemaluzel** [comment]
![IMG_8393](https://github.com/OpenDroneMap/WebODM/assets/23246374/31bf4af7-cd89-44b4-8f74-c0d89465e39e)
this is a minor bug

**Comment by vdroners** [comment]
I also confirm this issue.

**Comment by pierotofy** [comment]
Please try the latest version :pray: 

We've made significant improvements on the mobile UI/UX since this was first reported. :clinking_glasses: 

If the issue persists, feel free to re-open :pray:

**Comment by vdroners** [comment]
Thank. You!


V/R

Daniel Sautter
Veteran Droners
(540) 848-7979
