### ISSUE TITLE
error processing oblique data that processed ok on 3 other software's. 

### ISSUE THREAD

**Issue by Rico195786** [OpenDroneMap/WebODM#1482]
### How did you install WebODM (docker, installer, etc.)?

[installer]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Edge 122 on Windows 11]

### What is the problem?

[stops processing with error. see attached screenshots.]

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

[process the attached data.

I used the default settings.

![Screenshot 2024-03-21 143334 error 1](https://github.com/OpenDroneMap/WebODM/assets/154537296/d35ddaf0-8a0d-4389-a15f-5a879e5ff1f7)
![Screenshot 2024-03-21 143334 error 2](https://github.com/OpenDroneMap/WebODM/assets/154537296/41c0f201-3843-4a53-89b2-d4171c70cc33)
![Screenshot 2024-03-21 143334 error 3](https://github.com/OpenDroneMap/WebODM/assets/154537296/2b78b536-bd88-446a-a4be-6bb156ae080b)

https://drive.google.com/open?id=1NQLTNc1C5XjZovaQeirQPL-ZtSQpYuN6&usp=drive_fs]

**Comment by Rico195786** [comment]
Has there been an update to this? Is it a software issue or something I'm doing wrong?  Thanks

**Comment by smathermather** [comment]
Uncertain, but the better place to troubleshoot this is at community.opendronemap.org. I'll close this issue for now, and we can re-open here if it is in-fact a bug. Thanks!
