### ISSUE TITLE
"Check for update" does not show current release

### ISSUE THREAD

**Issue by maphew** [OpenDroneMap/WebODM#1487]
### How did you install WebODM (docker, installer, etc.)?

Windows installer

### What's your browser and operating system? 

browser: not relevant
OS: Microsoft Windows 10 Pro for Workstations, Version 10.0.19045 Build 19045.

### What is the problem?

The in app _Tools > Check for updates_ menu item reports installed version is current, but there are 2 new major dot releases showing on Github. (Additionally, there is no place in the UI to see what the currently installed version is).

### How can we reproduce this? 

Reproduction: use _Tools > Check for updates_ menu item.

Installed Web ODM version: 2.2.0

![image](https://github.com/OpenDroneMap/WebODM/assets/486200/910e497d-77a6-4eaf-8ae8-e8601a654f26)

**Comment by pierotofy** [comment]
The Windows installer should be now updated to the latest version.
