### ISSUE TITLE
all ready have a Yemeni map and not my image.

### ISSUE THREAD

**Issue by jgv501** [OpenDroneMap/WebODM#1489]
### How did you install WebODM (docker, installer, etc.)?

Install with Windows installer yesterday

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Firefox 124 on Windows 10 pro / 64 bits and 200 Go HD available + nvidia with 4 Go

### What is the problem?

I have created a new project call it LF4555; I have added images set (a zip file of 1.2 Go) coming from MAVIC 3 T drone. When going to 'afficher la carte' button, I got a wonderfull map of Yemen and surroundings  but not corresponding to images that are in france. I have inserted a GCP, no change. I did it three times; I tested my set of image using Pix4Dreact and it works perfectly.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? 

File is here  a zip file and a jpg for CGP fixed on Open streetmap : https://hub.dronedb.app/orgs/lezard_21/ds/a8bq3kphihv235kw/download/DJI_202404120735_001.zip?inline=1

**Comment by smathermather** [comment]
I just saw this issue. If not resolved, please reach out at community.opendronemap.org and we can help troubleshoot there.
