### ISSUE TITLE
Is it possible to install and use WebODM on Hadoop ecosystem-based environment?

### ISSUE THREAD

**Issue by HeavenlyCommencer** [OpenDroneMap/WebODM#1495]
### How did you install WebODM (docker, installer, etc.)?

Not yet, but trying to figure out

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Have access to Hadoop ecosystem environment

### What is the problem?

I don`t know how to install and use WebODM on Hadoop system.
Is is possible? I`m really confuse of (what the cloud computer platform is) and (what the hadoop system is)

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Whether there is a way or not, please share your knowledge regarding this problem :(

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
