### ISSUE TITLE
Provide better help for task failures

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#152]
A lot of people are getting confused or don't know what to do when a task fails with the classic `process exited with error code 1`.

WebODM should provide some suggestions, along with tips on how to file a report.

**Comment by smathermather** [comment]
👍

**Comment by pierotofy** [comment]
Done!

![image](https://cloud.githubusercontent.com/assets/1951843/25599419/18ac5aba-2eaa-11e7-8996-5a5f65c07b68.png)
