### ISSUE TITLE
Stange Error

### ISSUE THREAD

**Issue by TechLHF** [OpenDroneMap/WebODM#1524]
I have been trying to use WebODM to run larger image processing. I have struggled with anything over 550 pictures. So I started splitting at 400 with an overlap of 100. This has given me a strange error every time I have attempted to split. For reference, some of my photos may also be out of order from where they were taken. I ran planar, with medium level features, on google chrome. I am processing with 32 gigs of ram, docker has 22, and swap space of 11 gigs. I have an 8 core Ryzen 7 5700X processer on windows 11. I also had fast orthophoto on, and skip 3d model on.

Here is the error: ===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 2
Traceback (most recent call last):
File “/code/stages/odm_app.py”, line 82, in execute
self.first_stage.run()
File “/code/opendm/types.py”, line 471, in run
self.next_stage.run(outputs)
File “/code/opendm/types.py”, line 450, in run
self.process(self.args, outputs)
File “/code/stages/splitmerge.py”, line 192, in process
system.run(" ".join(map(double_quote, map(str, argv))), env_vars=os.environ.copy())
File “/code/opendm/system.py”, line 112, in run
raise SubprocessException(“Child returned {}”.format(retcode), retcode)
opendm.system.SubprocessException: Child returned 2

Here are the pictures I used in a zip file. They worked when Ran in an unknown version of Metashape, with minor issues along south edge.Here are the pictures I used in a zip file. [Photo Link](https://drive.google.com/file/d/11BKLspTFtC2P2g2qAjsBTbzT-AmX9Uap/view?usp=drive_link)

**Comment by pierotofy** [comment]
I'll close this since it's already being discussed on https://community.opendronemap.org/t/error-reporting-strange-error/21021 🙏
