### ISSUE TITLE
ERROR IN PROCESSING 

### ISSUE THREAD

**Issue by hasan1846** [OpenDroneMap/WebODM#1529]
Traceback (most recent call last):
worker      |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 385, in trace_task
worker      |     R = retval = fun(*args, **kwargs)
worker      |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 650, in __protected_call__
worker      |     return self.run(*args, **kwargs)
worker      |   File "/webodm/worker/tasks.py", line 42, in update_nodes_info
worker      |     processing_node.update_node_info()
worker      |   File "/webodm/nodeodm/models.py", line 70, in update_node_info
worker      |     info = api_client.info()
worker      |   File "/usr/local/lib/python3.8/dist-packages/pyodm/api.py", line 182, in info
worker      |     return NodeInfo(self.get('/info'))
worker      |   File "/usr/local/lib/python3.8/dist-packages/pyodm/api.py", line 130, in get
worker      |     res = requests.get(self.url(url, query), timeout=self.timeout, **kwargs)
worker      |   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
worker      |     return request('get', url, params=params, **kwargs)
worker      |   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
worker      |     return session.request(method=method, url=url, **kwargs)
worker      |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 521, in request
worker      |     prep = self.prepare_request(req)
worker      |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 454, in prepare_request
worker      |     p.prepare(
worker      |   File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
worker      |     self.prepare_url(url, params)
worker      |   File "/usr/lib/python3/dist-packages/requests/models.py", line 381, in prepare_url
worker      |     raise InvalidURL(*e.args)
worker      | requests.exceptions.InvalidURL: Failed to parse: http://172.24.0.2:3000/info

i MADE A FEW CHANGES TO WEBODM AFTER WHICH I SHIFTED THE DEVELOPER BUILD TO PRODUCTION MODE BEFORE HOSTING. THEN I ADDED THE IP ADDRESS OF THE NEW PROCESSING NODE ON PORT 3000 (172.24.0.2:3000) AND HOSTED THE WEBSITE. ON PROCESSING I GET THE ABOVE ERROR IN TERMINAL.

ON THE WEBSITE IT SHOWS : 

There are no usable processing nodes.We tried to reach:

    [172.24.0.2:3000 (queue: 0)](http://172.24.0.2:3000/)

Make sure that at least one processing node is reachable and that you have granted the current user sufficient permissions to view the processing node (by going to Administration -- Processing Nodes -- Select Node -- Object Permissions -- Add User/Group and check CAN VIEW PROCESSING NODE). If you are bringing a node back online, it will take about 30 seconds for WebODM to recognize it.

BUT WHEN I ENTER THE IP ADDRESS (172.24.0.2:3000) IT SHOWS AN ACTIVE NODE .

**Comment by pierotofy** [comment]
> i MADE A FEW CHANGES TO WEBODM

Unless this error happens on a vanilla installation of WebODM, please don't use this issue tracker for reporting issues. If you have questions about WebODM development, the forum is the right place to start a conversation: https://community.opendronemap.org 🙏
