### ISSUE TITLE
instalação

### ISSUE THREAD

**Issue by saltogrande** [OpenDroneMap/WebODM#1534]
ola, fiz todo o procedimento de instalação, porem no git em seu ultimo comando ele deu o seguinte
 (time="2024-08-01T[10:12:14](https://www.youtube.com/watch?v=abEk1yyxLcY&t=36734s)-[03:00](https://www.youtube.com/watch?v=abEk1yyxLcY&t=180s)" level=warning msg="C:\\Users\\LIPE\\webODM\\docker-compose.yml: `version` is obsolete"
time="2024-08-01T[10:12:14](https://www.youtube.com/watch?v=abEk1yyxLcY&t=36734s)-[03:00](https://www.youtube.com/watch?v=abEk1yyxLcY&t=180s)" level=warning msg="C:\\Users\\LIPE\\webODM\\docker-compose.nodeodm.yml: `version` is obsolete")
o que é isso e o que eu faço ?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
