### ISSUE TITLE
Add presets

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#154]
Users should be able to manage option presets for processing images, and there should be a few default presets already included in WebODM (Standard, High Definition, Low Definition, etc.)

**Comment by smathermather** [comment]
This'd be really good to do in conjunction with the processing improvements due in June. (Sooner would be fine too, but we'll have some quality tracking that comes with the June improvements).

**Comment by pierotofy** [comment]
This has been implemented a while ago.
