### ISSUE TITLE
Mavic 3 Enterprise DTM height values incorrect

### ISSUE THREAD

**Issue by webmap-PS** [OpenDroneMap/WebODM#1540]
### How did you install WebODM (docker, installer, etc.)?

I use the installer version.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Microsoft Edge an Windows 10 Enterprise

### What is the problem?

I used the Mavic 3 Enterprise with the RTK-module for a survey. After checking the DTM I realized that the heights are completely off. I got a reference DTM and the values of my flight are off about 60 meters (thats about the height I flew with the drone). Is there some checkbox or something in WebODM that I missed? Maybe its a problem with the drone firmware? I checked other areas where I did the survey ant its the same issue, the dtm height values differ around the flight height. Vertical accuracy is outstanding in comparison, so I don't know where this came from. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

I can't provide data due to data security policy.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
