### ISSUE TITLE
Feature : Add project action button 

### ISSUE THREAD

**Issue by diegoaces** [OpenDroneMap/WebODM#1552]
I need to add a new functionality at the project level, but there is no way to add an action button in the projects. After researching, I found that a React component can be created and associated with the project list item, so I wrote the necessary code to implement it.

The PluginsAPI.Dashboard.addProjectActionButton method allows adding a view at the project level and is based on PluginsAPI.Dashboard.addTaskActionButton, which works at the task level. 

How to use with a custom plugin: 

`PluginsAPI.Dashboard.addProjectActionButton(['plugin-name/build/Example.js'], function (args, Component) {
        return React.createElement(Component, {projectId: project.id});
    }
);`

![Captura de pantalla 2024-09-06 a la(s) 9 54 06 a  m](https://github.com/user-attachments/assets/0c3f8d6d-f2ff-41e7-9a89-7b8fce0077ad)

**Comment by pierotofy** [comment]
This sounds like the `addNewTaskButton` endpoint which already exists: https://github.com/OpenDroneMap/WebODM/blob/b8b2e12980522ad7ee7cfb65ef6655ecf63b773c/app/static/app/js/components/ProjectListItem.jsx#L303

https://github.com/OpenDroneMap/WebODM/blob/b8b2e12980522ad7ee7cfb65ef6655ecf63b773c/app/static/app/js/components/ProjectListItem.jsx#L644

https://github.com/OpenDroneMap/WebODM/blob/b8b2e12980522ad7ee7cfb65ef6655ecf63b773c/coreplugins/dronedb/templates/load_buttons.js#L1

Have you tried using that one?

**Comment by diegoaces** [comment]
You are right, I made the changes pointing to addNewTaskButton, although I think addNewTaskButton is a bit confusing because it operates at the project level. 

![Captura de pantalla 2024-09-06 a la(s) 11 13 11 a  m](https://github.com/user-attachments/assets/077e2d40-1909-4cf3-bff4-fa722967725b)

Thanks!
