### ISSUE TITLE
Haze in ortho after map processed

### ISSUE THREAD

**Issue by Bwilder238** [OpenDroneMap/WebODM#1565]
## How did you install WebODM (docker, installer, etc.)?

Docker container

### What's your browser and operating system?

 Brave browser on unbuntu 24.04.1 LTS

### What is the problem?

New user here! Also limited in my tech knowledge but I have a great friend who is assisting in the matter and who built the computer and docker container. I've processed about 10 different maps that worked great prior to this issue using the same setup, however they were much smaller, less images to be processed, with no issues at all.

Problem set:
I uploaded multispectural photos to webODM to process and once complete there was a haze that populated in various areas of the map. Some areas were clear while others had this blur. Once I opened the tif in QGIS I check the pixel values, they were way lower than what is normally processed from a map. For example my red layer was .oo3 in various areas of interest when normally it is around .2.  I attempted to run raster calculations and they did not render layers appropriately. 

This happened post some memory issues I was having where webODM stopped processing because my RAM wasn't high enough. Luckily a good friend who has set this all up for me has been working to resolve these problems. I've got more ram coming and he increased my SWAP to 200gb and he installed 8tb ssds. This solved the memory issue for processing but now the models are hazy.

I've checked the raw data and there isn't a haze or cloudiness in them. The data capture lasted about 3 hrs so I'm not sure if that affected them or not. I used a DJI Mavic 3 Multispectural. 

The data sets are quite large, up to 230gb on import into webODM.

This happened with both regular ortho photo and MS maps.

I will attach photos of the images and what is happening. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

I will also make an attempt to upload the data on the Dropbox. There are a couple but I will use the one with the most apparent issues. 

![Screenshot from 2024-10-12 08-26-58](https://github.com/user-attachments/assets/f935ff54-1e10-4164-b972-7df3f14ea2df)
![Screenshot from 2024-10-12 08-23-06](https://github.com/user-attachments/assets/2fd6d4a6-8b37-4306-b2b8-79ce49a7b5c6)
![Screenshot from 2024-10-12 08-25-05](https://github.com/user-attachments/assets/75cb88f3-3b08-4805-bb9f-533af54b379c)
![Screenshot from 2024-10-12 08-25-38](https://github.com/user-attachments/assets/66bc6a60-f6cb-42fc-817f-9d505e8b8a54)

**Comment by pierotofy** [comment]
https://community.opendronemap.org/t/haze-in-ortho-after-map-processed/22141
