### ISSUE TITLE
eRROR in downloading my assets

### ISSUE THREAD

**Issue by Karogek** [OpenDroneMap/WebODM#1573]
System: macOS
****************************************
I use webodm through docker. Didn’t installed it manually.

I am using safari in Macbook with m2 chip.

eRROR in downloading my assets: "Safari could not download the file “DJI_202401190859_006_P1C3-orthophoto.tif” because the disk “Macintosh HD” doesn’t have enough free space.” But I have space in it.

**Comment by smathermather** [comment]
Please join us at community.opendronemap.org for support questions. Thanks!
