### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#16]
Once library requirements have been assessed, change Python version from 2 to 3.

**Comment by smathermather** [comment]
Should probably create a parallel issue / in OpenDroneMap/OpenDroneMap

see https://github.com/OpenDroneMap/OpenDroneMap/issues/349

**Comment by pierotofy** [comment]
All requirements so far seem to work on Python 3 (with some tweaks). I'm planning to bring the code to Python 3 in the next pull request.

**Comment by pierotofy** [comment]
Python 3 is now used in pierotofy/actions branch. Next PR will bring those changes in.
