### ISSUE TITLE
WARNING Not Found: /api/projects/2/tasks/1/tiles/1/1/1.png 

### ISSUE THREAD

**Issue by jackxieweiwu** [OpenDroneMap/WebODM#160]
WARNING Not Found: /api/projects/2/tasks/1/tiles/1/1/1.png
WARNING "GET /api/projects/2/tasks/1/tiles/1/1/1.png HTTP/1.1" 4

**Comment by pierotofy** [comment]
This is a normal warning message to inform that the top level tile (1/1/1) does not exist. Leaflet asks for it, but it's of no consequence if it's not found.

Thank you for reporting it. This is the expected behavior.

**Comment by jackxieweiwu** [comment]
![Uploading a.jpg…]()

**Comment by jackxieweiwu** [comment]
3D View ????
https://github.com/jackxieweiwu/LOG/blob/master/IMG_20170423_014400.JPG

**Comment by smathermather** [comment]
@jackxieweiwu -- does your browser support WebGL?
