### ISSUE TITLE
How to Increase Memory Allocation for WebODM Docker Image (step by step please :<)

### ISSUE THREAD

**Issue by ProjectNeurogenesis** [OpenDroneMap/WebODM#162]
Hi. I ran WebODM in a windows 10 home ed. laptop. It was working but can only process up to 40 images due to memory constraint. How can I easily increase memory allocation for the Docker image for WebODM particularly? I have 16gb ram laptop and stil 333gb remaining in my hard drive so..maybe it has to do with docker image. 

 Thank you.

PS: Has anyone tried using "Ubuntu Bash on Windows 10 subsystem" and tried installing ODM and/or WebODM in it? Does it work?

**Comment by pierotofy** [comment]
Hi,

See if this link helps: https://docs.docker.com/docker-for-windows/#advanced

From the system tray you should be able to access the memory configuration for your docker machine.

I have not tried using the Ubuntu subsystem, but I'm going to guess that it's not going to work. It would be cool if somebody tried or tweaked the configure script to make it work with it though.
