### ISSUE TITLE
Options display not scrollable and as a result changed options can't be saved

### ISSUE THREAD

**Issue by simonpoole** [OpenDroneMap/WebODM#165]
Running WebODM from the repo of today.

Run a task and then: Edit task -> Set Options 

The resulting list of options is (very very) long and does not fit on the screen and at the same time isn't scrollable, with the result the that save button is virtually something like a yard below my desk .

Observed with both current FF and Chrome versions on W10

**Comment by pierotofy** [comment]
Hi @simonpoole thanks for reporting the problem.

I confirm this is an issue. I've been able to scroll using the mouse wheel, but I realize that not everyone uses a mouse nowadays.

**Comment by pierotofy** [comment]
This is now fixed with the latest master.

![image](https://cloud.githubusercontent.com/assets/1951843/25596522/8319cfa8-2e97-11e7-91fe-61d20cff6e08.png)
