### ISSUE TITLE
old docker images being kept indefinitely

### ISSUE THREAD

**Issue by ctrl6DB** [OpenDroneMap/WebODM#167]
It seems that when running webodm.sh update, it builds a new image for webodm_webapp , but it keeps previous images.
Considering that the image size is in excess of 12GB (on Ubuntu, native docker engine), is it possible to remove previous images after a successful build ?
I use `docker rmi <IMAGE>` , but it would nice to have the option to automatically remove old builds.

Thank you.

**Comment by pierotofy** [comment]
Hi @ctrl6DB, yes this is a good suggestion, old images should be removed.

Thanks for pointing it out!

**Comment by pierotofy** [comment]
This should be now fixed: https://github.com/OpenDroneMap/WebODM/commit/83e176e70039041b7baf5057258e49f8b25a0fe0

**Comment by ctrl6DB** [comment]
Thank you very much ! Indeed, it works great.
