### ISSUE TITLE
No options to measure in metric units?

### ISSUE THREAD

**Issue by simonpoole** [OpenDroneMap/WebODM#171]
Minor nitpick: except if I'm dreaming there doesn't seem to be an option to measure in metric units (neither in the 2d view nor the point clouds).

**Comment by pierotofy** [comment]
Hey @simonpoole thank you for pointing this out.

It's definitely something that we should consider adding.

**Comment by pierotofy** [comment]
Linking this for future reference: https://github.com/ljagis/leaflet-measure#control-options

**Comment by pierotofy** [comment]
There's been a measurement tool in WebODM for a while now. Closing. :+1:
