### ISSUE TITLE
install issues 

### ISSUE THREAD

**Issue by boopathit98** [OpenDroneMap/WebODM#178]
i will install your WebODM my localhost machine pull fs layer stop not working how to solve 
Please help me how to solve 

![screenshot from 2017-05-23 19-32-13](https://cloud.githubusercontent.com/assets/10073974/26357958/9937022a-3fee-11e7-824a-bf98cefdf415.png)
![screenshot from 2017-05-23 19-32-29](https://cloud.githubusercontent.com/assets/10073974/26357959/995884ea-3fee-11e7-895c-f0926bd11414.png)

**Comment by pierotofy** [comment]
Hello,

I'm not sure I understand; is it just stuck? Try restarting the install process.

**Comment by boopathit98** [comment]
okay i will try fresh install 
any comes i will added here
