### ISSUE TITLE
Importing orthophoto into PostGIS causes overhead to the server process

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#187]
Since orthophotos need to be imported in EPSG:4326, and the transformation is done directly from django, this results in the WebODM process hanging for several minutes in the case of large orthophotos.

Possible workarounds:
 - Remove orthophoto from PostGIS, only leave reference to orthophoto extent
 - Create 4326 orthophoto in node-odm.

**Comment by djamajo** [comment]
@pierotofy is it a new way or a old way of doing that ?

**Comment by pierotofy** [comment]
I'm not sure I understand your question.

**Comment by pierotofy** [comment]
This will be solved as soon as #230 is merged in.
