### ISSUE TITLE
Niggles Gone

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#191]
Updated my WebODM today (it was only 2 weeks old)
170 images processed on 16GB with no issues before this would have caused me crashing into the top of swap space. Don't know what has changed but thanks.
CloudCompare was reading the las file and deliveiring slices rather than a uniform cloud, depite things looking good in the embedded potree viewer. This is gone also!
Remarkable!

**Comment by pierotofy** [comment]
Hey @KommandorKeen, yes we've finally pushed all the changes from OpenDroneMap into both node-odm and WebODM. 👏  👍 

Also check out the new `use-25dmesh` option for orthophotos. It's still experimental, but could produce better results (sometimes).
