### ISSUE TITLE
New install (02/06/2017) runing on only one core

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#192]
New installation today.
seems to be running on only a single cor (of 12) by default.

**Comment by pierotofy** [comment]
Yes, we've temporarily changed the `opensfm-processes` parameter default to `1` (https://github.com/OpenDroneMap/OpenDroneMap/pull/579). You can set it to something higher manually. Once the fault in opensfm is solved, we'll increase the default.
