### ISSUE TITLE
Add panel with disk usage statistics

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#197]
It would be useful for users to be able to see the amount of disk space remaining available, especially because people are often confused by the difference between the host disk space and the disk space allocated for docker.

**Comment by pierotofy** [comment]
We could also display things like the nginx error log, access log and other "debug" information.

**Comment by KommandorKeen** [comment]
![screenshot from 2017-06-08 10-59-51](https://user-images.githubusercontent.com/16811869/26907872-0e43c5d8-4c3a-11e7-859b-e710e36abbd5.png)

On the disk usage issue, any idea what the docker diff is? My webODM directory is big for the size of the data in it, but the diff appears 'suddenly and is 2 x the size.

**Comment by pierotofy** [comment]
They are intermediate images. Some of them might be old and could be removed via:

```
docker images -a|grep '^<none>'|tr -s ' '|cut -d' ' -f 3|xargs docker rmi
```

**Comment by AnthonyCoughlin** [comment]
@pierotofy, this would be a great addition!

**Comment by pierotofy** [comment]
This has been added a while ago.
