### ISSUE TITLE
Suggestion on Defaults

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#206]
As ODM is being used for multiple purposes it might be worth having 3 defaults.
1. Flat agriculture camera pointing down
2. Lumpy ground, trees, hills, cameras either down or tilted slightly forward
3. Full 3D with massively dense cameras with different angles and orientations.
 and of course the ability to save the parameters used on the last operation as 'custom'

I think this route will reduce the number of poor results created.

**Comment by pierotofy** [comment]
Related: #154

**Comment by pierotofy** [comment]
This has been done time ago. :clinking_glasses:
