### ISSUE TITLE
stripes on PMVS point cloud?

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#211]
I am having trouble making the georeferencing work with more than 1 SFM core operating, so resorted to PMVS. noticed this difference in the pointcloud LAS files

PMVS
![pmvs](https://user-images.githubusercontent.com/16811869/27217059-a7e328fa-52bb-11e7-8110-0e091b374928.png)
SFM
![sfm](https://user-images.githubusercontent.com/16811869/27217077-b6df5efa-52bb-11e7-9eb4-7ee09eae61ed.png)

NOte to get georef to work I have to leave the images at their fullsize i.e re-size to 3000x4000.
I am running a job at the moment where I have resized to 1000 and provided suitably scaled geroref points. will let you know how it goes.

**Comment by pierotofy** [comment]
This looks similar to https://github.com/OpenDroneMap/OpenDroneMap/issues/522.

**Comment by dakotabenjamin** [comment]
This should have been fixed in 0.3... why would it not work for PMVS?

**Comment by pierotofy** [comment]
Different input ply format? Not entirely sure. @KommandorKeen could you share the dataset you used to produce this result (along with the parameters used to run the task)?

**Comment by KommandorKeen** [comment]
will, do.....soon.  Thanks.

**Comment by KommandorKeen** [comment]
Images may be found at...
https://drive.google.com/open?id=0B9GCZwyI5K2yRHl2WVI2djZTekU
Options in WebODM were..
Options: resize-to: 4000, opensfm-processes: 6, use-pmvs: true

I did the full size option as I was /am getting a little doming on biggger areas.

**Comment by pierotofy** [comment]
I can't seem to reproduce this.

![screen shot 2017-07-07 at 3 39 21 pm](https://user-images.githubusercontent.com/1951843/27974125-8ec79408-632a-11e7-801e-871a4ad28897.png)

@KommandorKeen have you made sure to run the latest version of node-opendronemap?

**Comment by pierotofy** [comment]
(Sorry didn't mean to close this)

**Comment by KommandorKeen** [comment]
Tried a ./webodm.sh update today and completely trashed my install. :-(
Will have to start from scratch. Looks like I tried to do the update with a disk not mounted so stuff got placed in all sorts of strange places.
.......
later

**Comment by pierotofy** [comment]
@KommandorKeen I just pushed an updated in #236 to fix a problem with migrations. Before nuking everything, you should try to update one more time and see if you can bring the program back online. It shouldn't be necessary to start everything from scratch.

**Comment by KommandorKeen** [comment]
It does when the problem was the hard drive not liking the cold weather and becoming unusable. Not realising this and trying to update a docker install that wasn’t there. User error.

**Comment by KommandorKeen** [comment]
Cannot re-replicate this problem so closing it.
