### ISSUE TITLE
Orthophoto tiles download

### ISSUE THREAD

**Issue by jmprovencher** [OpenDroneMap/WebODM#215]
Since a tile folder is generated after processing everything, I would like to know if it's in the roadmap to allow user to download the tile folder as an asset. Thank you

**Comment by pierotofy** [comment]
Hi @jmprovencher, you should be able to download the folder (it's named `orthophoto_tiles`) if you go to "Download Assets -- All Assets". Is that what you were looking for?

**Comment by jmprovencher** [comment]
Yeah you're right I had not seen the content of the all assets Zip folder. Thank you!
