### ISSUE TITLE
./webodm.sh start

### ISSUE THREAD

**Issue by JUANVALENCIAMOREY** [OpenDroneMap/WebODM#216]
$ ./webodm.sh start
Checking for docker...   OK
Checking for git...   OK
Checking for python...   can't find python! Check that the program is installed and that you have added the proper path to the program to your PATH environment variable before launching WebODM. If you change your PATH environment variable, remember to close and reopen your terminal. https://www.python.org/downloads/

How do i fix it........

**Comment by pierotofy** [comment]
Hi Juan,

You need to install Python on your system. The installation process varies depending on what system you are currently using.

**Comment by JUANVALENCIAMOREY** [comment]
I always installed it and I do not know why the message appears

________________________________
De: Piero Toffanin <notifications@github.com>
Enviado: viernes, 23 de junio de 2017 08:27 a.m.
Para: OpenDroneMap/WebODM
Cc: JUANVALENCIAMOREY; Author
Asunto: Re: [OpenDroneMap/WebODM] ./webodm.sh start (#216)


Hi Juan,

You need to install Python on your system. The installation process varies depending on what system you are currently using.

**Comment by pierotofy** [comment]
What operating system are you on?

**Comment by JUANVALENCIAMOREY** [comment]
Windows 10


I have python installed and<https://sourceforge.net/projects/pyscripter/> PyScripter<https://www.google.com.pe/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjgweT379TUAhWC6CYKHa52C70QFggnMAA&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpyscripter%2F&usg=AFQjCNHTjy3qE-tlM0pyprHN6rW_n0REJQ><https://www.google.com.pe/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjgweT379TUAhWC6CYKHa52C70QFggnMAA&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpyscripter%2F&usg=AFQjCNHTjy3qE-tlM0pyprHN6rW_n0REJQ><https://www.google.com.pe/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjgweT379TUAhWC6CYKHa52C70QFggnMAA&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpyscripter%2F&usg=AFQjCNHTjy3qE-tlM0pyprHN6rW_n0REJQ><https://sourceforge.net/projects/pyscripter/>




________________________________
De: Piero Toffanin <notifications@github.com>
Enviado: viernes, 23 de junio de 2017 03:42 p.m.
Para: OpenDroneMap/WebODM
Cc: JUANVALENCIAMOREY; Author
Asunto: Re: [OpenDroneMap/WebODM] ./webodm.sh start (#216)


What operating system are you on?

**Comment by pierotofy** [comment]
You need to make sure that the path to your python.exe executable is in your PATH environment variable.

Note that there's also an installer available for Windows, which makes the installation a lot easier: https://webodm.org/installer

**Comment by JUANVALENCIAMOREY** [comment]
Gracias
