### ISSUE TITLE
Task will not process

### ISSUE THREAD

**Issue by brookjason** [OpenDroneMap/WebODM#217]
I'm having a issue processing my images here is the output [task_output.txt](https://github.com/OpenDroneMap/WebODM/files/1097681/task_output.txt) I have also tried a subset (10 images) just to see and it still fails, I have also had a look to see if the images are geotagged and they seem to be. any help would be appreciated.

images are located here: https://drive.google.com/drive/folders/0B5Tip351FAkRdVZBNVc2QXV1bE0?usp=sharing 

it has previously worked in the command line when using it about a month ago images are from the same drone running the same route.

**Comment by pierotofy** [comment]
Since the area has a lot of vegetation (grass), it's difficult for opendronemap to find enough matching features.

Did you try increasing the `min-num-features` to something like 12000?
