### ISSUE TITLE
WebODM in docker - Can I access the orthomosaic tiles as served in QGIS on host? 

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#227]
Title says it all....

**Comment by pierotofy** [comment]
Hi @KommandorKeen,

what do you mean by "as served in QGIS on the host"?

I think you should be able to load the TMS tiles using https://github.com/minorua/TileLayerPlugin

See the TMS url details here: http://docs.webodm.org/#orthophoto-tms-layer

**Comment by KommandorKeen** [comment]
Running ODM natively so now can access all files
