### ISSUE TITLE
Expose rerun-from parameter and allow restarted process to reuse intermediate results

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#229]
Right now a task is reprocessed from scratch.

**Comment by KommandorKeen** [comment]
Agree, this would be a very valuable addition.
Let me learn docker and how to work in and out of docker and I will try to help here.

**Comment by KommandorKeen** [comment]
A great example of this would be re running after from the georeferenced point cloud I f the point cloud has been cleaned in another app and put back in the right place. A few mandraulic deletions in CC perhaps.

**Comment by pierotofy** [comment]
This is now implemented, cheers!
