### ISSUE TITLE
Question: Is it possible to change default port?

### ISSUE THREAD

**Issue by macsee** [OpenDroneMap/WebODM#235]
Hi,
I have WebODM installed on a Ubuntu machine and I would like to use it from internet. I would usually do it from a PC that's in firewalled network, so I was wondering since 8000 port is blocked on this network, if it's possible to change it for another that's not blocked, like 80.
Thanks!

**Comment by pierotofy** [comment]
Hi @macsee, yes, you just need to change this `docker-compose.yml` line:

From:

```
ports:
  - "8000:8000"
```

To:

```
ports:
  - "80:8000"
```

Then restart WebODM.

**Comment by macsee** [comment]
Great! Thanks @pierotofy!

Cheers.

**Comment by deviirmr** [comment]
Hi,
I have a similar issue, I have change the default port to some port (8001:8000) as per @pierotofy but still the application is not opening in new port but  active in the old port.
![image](https://user-images.githubusercontent.com/10088434/51927948-10f59380-23f5-11e9-9f9b-1c92efeca5c2.png)
I restart the application but seems no impect
![image](https://user-images.githubusercontent.com/10088434/51928107-69c52c00-23f5-11e9-84df-64fdc33498c9.png)
Any sugustion.
Thanks.

**Comment by pierotofy** [comment]
I would suggest not to modify the docker-compose.yml file and instead use the `--port` param when launching WebODM:

`./webodm.sh restart --port 8001`

**Comment by deviirmr** [comment]
Finally, it is working.
Thank you so much and thanks for the quick response.
![image](https://user-images.githubusercontent.com/10088434/51933260-2a044180-2401-11e9-9d85-90f9d0c3198e.png)
