### ISSUE TITLE
Orthophoto upside down.

### ISSUE THREAD

**Issue by marioriverachavarria** [OpenDroneMap/WebODM#238]
The orthophoto is turned upside down.
This is the result:
![image](https://user-images.githubusercontent.com/30131417/28143696-40497f64-6724-11e7-9de0-9457ae89fe45.png)
And this is the one should be:
![image](https://user-images.githubusercontent.com/30131417/28143751-83958b82-6724-11e7-94c3-336566e86821.png)
Where could be the problem?.

This is with the latest version of WebODM

**Comment by dakotabenjamin** [comment]
It might occur if the photos don't have altitude data but I don't know without seeing the data

**Comment by marioriverachavarria** [comment]
Hello,

Photos do have the height info , the problem is that this is interpreted wrongly
Heres an example dataset.

https://www.dropbox.com/sh/wd3dkzdhjrs0xia/AAAYHgZu_F_AOex8-3hRorHfa?dl=0

Thank you

**Comment by marioriverachavarria** [comment]
:)

**Comment by KommandorKeen** [comment]
What did you change to go to the :)  ?
I ask because I have had exactly the same problem in an area with big trees and the drone flying at a single height. All photos have altitude data.

**Comment by marioriverachavarria** [comment]
its really a :( haha. No results yet. I maen everything appears to be fine but its just the inverse.

Weird.

**Comment by KommandorKeen** [comment]
I solve the problem with mine. I had one extra image which I had taken at an angle, and a different altitude and bang it all flipped and fitted.
So my work around is to, from now on, capture an extra image or two on the drone descent with the camera at -70 deg from horizontal and th put them in the data set.
Simon

**Comment by pierotofy** [comment]
Could you try to reprocess the dataset by increasing the `min-num-features` option to 8000 (up from the 4000 default)?

**Comment by marioriverachavarria** [comment]
Same results.
![image](https://user-images.githubusercontent.com/30131417/28241763-f2f4aba4-6957-11e7-95a7-1ebda9503d8b.png)

Problem is that is getting the height data as negative. Is there a way to change the sign of the operation?


![image](https://user-images.githubusercontent.com/30131417/28241785-59d71316-6958-11e7-9eff-60f8a7e5c9fb.png)

**Comment by pierotofy** [comment]
Something does not look right with your EXIF tags. For example, YUN00095.jpg gives me:

```
#exiftool YUN00095.jpg
GPS Altitude                    : 5 m Below Sea Level
```

But I have a feeling that that's not correct. Check the validity of your altitude values, as they are probably incorrect, fix the exif tags or use a GCP file. The model will come out OK afterwards.

**Comment by marioriverachavarria** [comment]
This happens also without using exif.

**Comment by marioriverachavarria** [comment]
Is it possible to make the software ignore this attribute GPSAltitudeRef?

**Comment by marioriverachavarria** [comment]
else:
            altref = '1'
        key = 'Exif.GPSInfo.GPSAltitudeRef'
        metadata[key] = pyexiv2.ExifTag(key, altref)

        # write values
        metadata.write()
