### ISSUE TITLE
Free Processing Nodes Volunteer Network

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#24]
At some point it could be beneficial to create a basic infrastructure for allowing people to donate server resources to process maps.

It could be as simple as having volunteers install the processing software, having a sign-up form, a web page with the list of volunteers, and some code to check which nodes are online.

**Comment by Bavar2142** [comment]
Righto. Ill have a look at boinc to see how theyve organised it and get back to you.

**Comment by Bavar2142** [comment]
Boinc itself is under the ​Lesser General Public License (LGPL), version 3 or there abouts and i've managed to find links to their git repository and source code.

https://boinc.berkeley.edu/trac/wiki/SourceCodeGit

**Comment by pierotofy** [comment]
This idea would require:
 - Central endpoint to maintain a list of active nodes
 - Modification to node-OpenDroneMap to add an `advertise` or `broadcast` or `public` flag that automatically notifies the central list
 - Addition of a sponsor name, other metadata to node-OpenDroneMap
 - Code that fetches the list of public nodes in WebODM

**Comment by skypuppy** [comment]
Not sure if BOINC can do this automagically, but it would be ideal if we could distribute the work load over a number of systems.  Yeah, I know, distributed processing is a whole 'nother can of worms.

**Comment by smathermather** [comment]
We’re working on solving some of the distributed problems anyway, it’d just be a different network to distribute on, so distribution isn’t too much of an issue, or won’t be once we’re done with it :D

**Comment by pierotofy** [comment]
I'm going to take this off the TODO list. There's too many unresolved difficulties:
 - Unsustainable economic costs of running and managing such network
 - Data privacy and security concerns
 - Impossibility(?) of guaranteeing QOS 

I'd welcome proposals and coding efforts from the community to solve this.
