### ISSUE TITLE
Loading Processing Nodes in IE does not work

### ISSUE THREAD

**Issue by bobbyturk** [OpenDroneMap/WebODM#244]
I have installed WebODM and I get this message that it is loading processing nodes. That is as far as I get. I had this installed on my mac and I didn't have this problem. I think that the processing node is supposed to load quickly.
![capture 2](https://user-images.githubusercontent.com/30244573/28287747-a8b43032-6af1-11e7-98c8-ec16d2b3c7c9.PNG)
![capture](https://user-images.githubusercontent.com/30244573/28287746-a88fb4fa-6af1-11e7-8111-ee43c26056eb.PNG)

**Comment by pierotofy** [comment]
Hey @bobbyturk, yes it should load quickly.

If you expand the "Processing Node" menu on the right and click on "node-odm-1", does the processing node appear online?

Also, what happens if you try to open WebODM with a different browser (say, Firefox)? Maybe this is a browser compatibility issue.

**Comment by bobbyturk** [comment]
Hi,

I switched to Firefox and it worked! Just made my first model!

thanks,

bobby

**Comment by bobbyturk** [comment]
Hi,

I switched to Firefox and it worked! Just made my first model!

thanks,

bobby

**Comment by pierotofy** [comment]
Awesome!! 👍 Definitely a browser compatibility issue then. Would you mind sharing what version of Internet Explorer you were using so that we can have somebody try to fix it?

https://www.lifewire.com/what-version-of-internet-explorer-do-i-have-2617990

**Comment by pierotofy** [comment]
Older browsers are now receiving a warning from WebODM to upgrade. This should be fixed.
