### ISSUE TITLE
upload folder path change webodm webapp

### ISSUE THREAD

**Issue by boopathit98** [OpenDroneMap/WebODM#247]
good afternoon sir,
sir i have doubt how to change save image folder and view map json assets url 
i have local machine process image files 
how to configuration to live server sir any possible sir
any one help me please sir please sir

**Comment by pierotofy** [comment]
Hi,

I'm not sure I understand the question. Could you try explain it in different terms?

**Comment by boopathit98** [comment]
good evening sir 
i used WebODM script i will upload some image processing and how to find that images and tiles image and geotiff and obj files where it stored

**Comment by pierotofy** [comment]
All results are stored in a docker volume. They are not available on the host file system. If you want to change the mapping, you need to change `docker-compose.yml` to a different path, example:

https://github.com/OpenDroneMap/WebODM/blob/master/docker-compose.yml#L21

From:
```
    volumes:
      - appmedia:/webodm/app/media
```

To:
```
    volumes:
      - /path/where/to/store/files:/webodm/app/media
```

Then restart WebODM.
