### ISSUE TITLE
When ortho gen fails, view map button on dashboard still exists

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/WebODM#248]
Minor aesthetic bug but I thought it worth documenting. As the title says, the View Map button on the dash for each project leads to a blank map for unfinished projects. It could be hidden/greyed out or link to the successful point cloud for certain datasets.

**Comment by pierotofy** [comment]
Thanks for reporting this!

**Comment by pierotofy** [comment]
This has been fixed long ago! :clinking_glasses:
