### ISSUE TITLE
update fails 

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/WebODM#251]
when i run ./webodm.sh update
i get the error below, yet I have not consciously changed any files.
any suggestions?

From https://github.com/OpenDroneMap/WebODM
 * branch            master     -> FETCH_HEAD
Updating df2ac4f..55749dd
error: Your local changes to the following files would be overwritten by merge:
	.travis.yml
	README.md
	VERSION
	app/admin.py
	app/api/tasks.py
	app/api/urls.py
	app/boot.py
	app/models.py
	app/static/app/bundles/.gitignore
	app/static/app/js/MapView.jsx
	app/static/app/js/ModelView.jsx
	app/static/app/js/classes/AssetDownloads.js
	app/static/app/js/classes/Utils.js
	app/static/app/js/components/AssetDownloadButtons.jsx
	app/static/app/js/components/EditProjectDialog.jsx
	app/static/app/js/components/EditTaskDialog.jsx
	app/static/app/js/components/EditTaskForm.jsx
	app/static/app/js/components/EditTaskPanel.jsx
	app/static/app/js/components/ErrorMessage.jsx
	app/static/app/js/components/FormDialog.jsx
	app/static/app/js/components/Map.jsx
	app/static/app/js/components/Paginated.jsx
	app/static/app/js/components/ProcessingNodeOption.jsx
	app/static/app/js/components/ProjectListItem.jsx
	app/static/app/js/components/Standby.jsx
	app/static/app/js/components/SwitchModeButton.jsx
	app/static/app/js/components/TaskListItem.jsx
	app/static/app/js/css/EditTaskForm.scss
	app/static/app/js/css/EditTaskPanel.scss
	app/static/app/js/css/MapView.scss
	app/static/app/js/css/TaskListItem.scss
	app/static/app/js/vendor/leaflet/Leaflet.Autolayers/leaflet-autolayers.js
	app/templates/app/base.html
	app/templates/app/map.html
	app/templatetags/processingnode_extras.py
	app/tests/test_api_task.py
	app/views.py
	db/Dockerfile
	docker-compose.dev.yml
	docker-compose.nodeodm.yml
	package.json
	slate/source/includes/reference/_task.md
	webpack.config.js
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by pierotofy** [comment]
To check what you have changed, from the WebODM directory type:

```
git status
```

If you are OK discarding any changes you might have made, just type:

```
git reset --hard
```

Note that this will undo any changes you might have made. Then you should be able to do a ./webodm.sh update without issues.

**Comment by KommandorKeen** [comment]
Thx
