### ISSUE TITLE
easy_install: command not found ./webodm.sh: line 71: sudo: command not found

### ISSUE THREAD

**Issue by lutjanus** [OpenDroneMap/WebODM#255]
$ ./webodm.sh start
Checking for docker...   OK
Checking for git...   OK
Checking for python...   OK
Checking for pip...  not found, we'll attempt to install
easy_install pip || sudo easy_install pip
./webodm.sh: line 71: easy_install: command not found
./webodm.sh: line 71: sudo: command not found

**Comment by wasi** [comment]
seams like pip is not installed and / or the paths are not set correctly. Try to install pip before running webodm.sh (https://pip.pypa.io/en/stable/installing/)
