### ISSUE TITLE
Webapp error for db

### ISSUE THREAD

**Issue by stiward** [OpenDroneMap/WebODM#259]
Greetings,
Yesterday I was testing the WebODM, I had some mishaps but everything worked correctly (link of the problem that I surged https://github.com/OpenDroneMap/WebODM/issues/258). Today when I try to start the webodm.sh I get this error (image 1).

Restart the virtual machine and still give the same error.

image 1
![webapp error](https://user-images.githubusercontent.com/10813238/29031252-9eeb506a-7b5b-11e7-859a-8c775f595e31.PNG)

**Comment by pierotofy** [comment]
Mm, do any of these recommendations help your situation? https://github.com/shipping-docker/php-app/issues/19
