### ISSUE TITLE
ODM Flight Planner

### ISSUE THREAD

**Issue by wildintellect** [OpenDroneMap/WebODM#265]
In order to ensure you get a good flight and enough gcp per part (if splitting) we should have some sort of flight planning. Something implemented in QGIS would be most useful as you'll have access to a full gis/layers as needed, and the ability to export a variety of formats for different flight controllers.

For inspiration, see this R Shiny implementation. https://github.com/byzheng/missionplanner

**Comment by pierotofy** [comment]
Relevant #6

**Comment by smathermather** [comment]
Closing as duplicate to #6
