### ISSUE TITLE
No usable processing nodes. 

### ISSUE THREAD

**Issue by uasimagery** [OpenDroneMap/WebODM#274]
Hi All,

I'm hoping someone can point me in the right direction. I have OpenDroneMap working with Docker and everything goes well until I upload images for processing. It seems there are no usable processing nodes. I have changed permissions for the "admin" user but this hasn't seemed to have changed anything. Is there any chance some one could walk me through fixing this issue? I have provided some screenshots which show current settings.... System specs are below in case that all helps. Any help would be much appreciated.....

Windows 10 Home
Intel Core i7-4790 CPU @ 3.60 GHz
32.0GB RAM
64 Bit OS x64 based processor

VirtualBox 5.1.26 r117224(Qt5.6.2)
Docker Version 17.06.0-ce build 02c1d87
![docker](https://user-images.githubusercontent.com/31360590/29737959-157e722e-8a6c-11e7-8ca4-400b02b255a8.png)
![permissions](https://user-images.githubusercontent.com/31360590/29737957-157afc70-8a6c-11e7-9a1b-35a0985c987e.png)
![processingnode](https://user-images.githubusercontent.com/31360590/29737958-157e1e3c-8a6c-11e7-84c2-a9e845a8e310.png)
![webodm](https://user-images.githubusercontent.com/31360590/29737960-1580af80-8a6c-11e7-9210-1c4c4bbf7640.png)

![cmdprompt](https://user-images.githubusercontent.com/31360590/29738979-739777ce-8a86-11e7-9bde-befc7b4dfd4e.png)
![newnode](https://user-images.githubusercontent.com/31360590/29745314-748fa680-8b0b-11e7-9629-8612e735ffc0.png)

**Comment by pierotofy** [comment]
Hi, sorry you're having issues.

Could you try to delete the processing node from the admin interface and restart webodm? It should be recreated automatically when you restart (does it appear in the menu on the right under "Processing nodes"? Also did this problem occur from a fresh install, or did you change some settings before it stopped working?

**Comment by uasimagery** [comment]
Thanks for the advice, I ended up having to uninstall and reinstall docker, VB and then re-clone from Github. All seems to be working now :) 

Is there a facility to add nodes yet?

**Comment by pierotofy** [comment]
Yay, glad it worked!

Could you expand on the "is there a facility" question? I'm not sure I understand it fully.

**Comment by uasimagery** [comment]
Sure, as I understand it, it might be possible to run multiple nodes at once while processing several jobs at on time... is this the case?

**Comment by pierotofy** [comment]
Yes adding more processing nodes will allow you to run multiple jobs in parallel. See https://github.com/OpenDroneMap/node-OpenDroneMap on how to setup new nodes.
