### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by smitch41** [OpenDroneMap/WebODM#283]
Hi
Trying to get WebODM running and all seems well until it gives me an Error stating "No Containers to Start". Perhaps I've missed something in the install..?
![screenshot from 2017-09-10 03-03-18](https://user-images.githubusercontent.com/31804885/30243090-1b58f484-95d5-11e7-91bf-ff5e7ffb2bc4.png)

**Comment by pierotofy** [comment]
Nop, nothing wrong. Just wait for the downloads to finish and you'll be up and running. 😄

**Comment by smitch41** [comment]
Thanks....unfortunately I'm stuck on a vessel in the middle of the ocean...very slow download...will have to wait til I'm back on land.

**Comment by pierotofy** [comment]
@smitch41 did you manage to get it working? Can I close this?

**Comment by smitch41** [comment]
Yes...all working...thankyou.
