### ISSUE TITLE
Issues with orthophoto

### ISSUE THREAD

**Issue by viks2015** [OpenDroneMap/WebODM#288]
The generated image is not patched properly and has lots for gaps in it, the same is applicable for the generated 3d mesh 
Also how to I import the orthophoto in google earth
![odm_orthophoto](https://user-images.githubusercontent.com/14228623/30495494-d211348c-9a69-11e7-9260-9eed9377373d.png)

**Comment by pierotofy** [comment]
Hi and welcome! 😄 

You could try to increase the `min-num-features` parameter in the task settings (set it to 8000) and see if that makes a difference.

To import the orthophoto in Google Earth you could use `gdal2tiles` http://www.gdal.org/gdal2tiles.html.

We also have plans to automate KML/KMZ export functionality into WebODM, but that feature hasn't been implemented yet. See #126

**Comment by viks2015** [comment]
Ok thanks for the help I haved increase the min-num-features parameter and have to wait to see the results. 
I webodm the final orthophoto is placed over google map automatically, now if I take take that photo and try to place on Google Earth Pro it does to get placed at the correct location, how can I do that.
I am able to place orthophoto generated by Agisoft Photoscan over Google earth Pro correctly

**Comment by KommandorKeen** [comment]
Looks like the holes are outside the footprint of the drone flight.
You cannot expect to get a map of places the software cannot see and match in multiple images. from multiple angles.

**Comment by pierotofy** [comment]
This issue was moved to http://community.opendronemap.org/t/issues-with-orthophoto/47
