### ISSUE TITLE
Error while processing - Could not start process (spawn /code/run.sh ENOENT)

### ISSUE THREAD

**Issue by Marcuzzo77** [OpenDroneMap/WebODM#289]
Goodmorning everyone,
I happened on a pc with windows 10 an error when i start the startup for the processing of the pictures of which I attached screenshots.
Says "Could not start process (spawn /code/run.sh ENOENT)"
![schermata 2017-09-16 alle 17 25 09](https://user-images.githubusercontent.com/26044319/30513478-324e0a2e-9b04-11e7-98d2-eb7b614b4fe6.png)

**Comment by pierotofy** [comment]
Hi, sorry to hear that you're experiencing issues.

How did you install WebODM (did you use docker, did you use the installer from webodm.org, ... )?

**Comment by Marcuzzo77** [comment]
I downloaded the packet from included docker toolkit github etc .. It went all right, it worked, then I wanted to expand virtualbox 5.1 virtual disc as it was not the default 20GB ...
Unfortunately some passes have not been successful, so I thought I would start from scratch reinstalling everything.
Now that's the problem ...

**Comment by pierotofy** [comment]
I rolled back some changes, if you run:

`./webodm.sh down && docker pull opendronemap/node-opendronemap && ./webodm.sh start`

Does it work now?

**Comment by Marcuzzo77** [comment]
No Piero, it does not work yet

**Comment by pierotofy** [comment]
Could you try starting from a fresh install?

**Comment by Marcuzzo77** [comment]
I tried to delete everything, the Webodm folder, the virtualbox virtual machine created by the docker, downloading packages from the git, then I followed the procedure

https://github.com/OpenDroneMap/WebODM

Nothing to do ... I continue my tests

**Comment by Marcuzzo77** [comment]
Ok I finally solved ....
I followed your advice, uninstalled everything, bought virtual machines, and reinstalled everything. Finally it works.
Thanks Piero for your support

**Comment by pierotofy** [comment]
Great! 👍 Thank you for reporting the problem!
