### ISSUE TITLE
[WARNING] Could not find ccd_width in file. Use --force-ccd

### ISSUE THREAD

**Issue by sellinios** [OpenDroneMap/WebODM#304]
Hi, 

I have a phantom Pro 4 drone and I am getting the following message, 

[WARNING] Could not find ccd_width in file. Use --force-ccd 

How do I set up the ccd manually ? 

Could you please help me ?

**Comment by pierotofy** [comment]
Hi, if you know the value for your camera sensor, you can set it by modifying the default preset before submitting a task for processing:

![image](https://user-images.githubusercontent.com/1951843/31742691-62287956-b426-11e7-8ff2-331f26604221.png)


![image](https://user-images.githubusercontent.com/1951843/31742647-3b0c4668-b426-11e7-84ef-65a9d7f39d5f.png)

**Comment by pierotofy** [comment]
This issue was moved to http://community.opendronemap.org/t/warning-could-not-find-ccd-width-in-file-use-force-ccd/39
