### ISSUE TITLE
Generation Surface Model failed

### ISSUE THREAD

**Issue by Marcuzzo77** [OpenDroneMap/WebODM#306]
I have a problem with the generation of the surface model. After processing I can not generate it. I attach pictures
![1](https://user-images.githubusercontent.com/26044319/31717223-588b3638-b40b-11e7-8f31-2e0a8f27466e.png)
![2](https://user-images.githubusercontent.com/26044319/31717233-5d90f910-b40b-11e7-859a-1c7270748a2a.png)

**Comment by pierotofy** [comment]
Hi, did you pass the "--dsm" option when processing the task (should be in the "Default" preset)?
Also, could you copy/paste the output of your processing task? How did you install WebODM (docker, native install, etc.)?

**Comment by Marcuzzo77** [comment]
Hi Piero,

actually use WebODM on different operating systems. On Windows 10 Pro I use the docker with the virtual Hyper V machine by default and I have no problem with Ubuntu 17.04 instead ...
When I go to select DSM + DTM, the option you choose is not preserved when you save the options, but always use the "Default" option automatically.
Some parameters such as dsm check and dtm check are missing from the options list on Ubuntu 17.04 ...

**Comment by Marcuzzo77** [comment]
Hi Piero,

I fixed the problem with an update (./webodm.sh update) at the latest available version. Thank you for your usual collaboration
