### ISSUE TITLE
Processing error when I try over 151 pictures, the first 101 work fine

### ISSUE THREAD

**Issue by LRDquarry** [OpenDroneMap/WebODM#307]
I have tried to increase virtual box memory to just under 6 meg (and 2 for my windows 10 home host).
I have read and also tried various options to process the full set (218 I think);
Force_CCD (is 8.8 correct for a Phantom 4 Pro), Min_Num_Features 10000, and use PMVS because it is heavy forest.

Here is the process info:
[Uploading task_output.txt…]()

and the first few pictures
![dji_0405](https://user-images.githubusercontent.com/32936691/31782303-993dbf4e-b4c8-11e7-8a8e-97a5f35f71f3.JPG)
![dji_0406](https://user-images.githubusercontent.com/32936691/31782305-99638148-b4c8-11e7-8af5-2a7537d6d6ae.JPG)
![dji_0407](https://user-images.githubusercontent.com/32936691/31782306-997a7bf0-b4c8-11e7-9fab-74e62e56c04e.JPG)
![Uploading DJI_0408.JPG…]()
![Uploading DJI_0409.JPG…]()
![Uploading DJI_0410.JPG…]()
![Uploading DJI_0411.JPG…]()
![Uploading DJI_0412.JPG…]()
![Uploading DJI_0413.JPG…]()
![Uploading DJI_0414.JPG…]()
![Uploading DJI_0415.JPG…]()
![Uploading DJI_0416.JPG…]()
![Uploading DJI_0417.JPG…]()
![Uploading DJI_0418.JPG…]()
![Uploading DJI_0419.JPG…]()
![Uploading DJI_0420.JPG…]()
![Uploading DJI_0421.JPG…]()
![Uploading DJI_0422.JPG…]()
![Uploading DJI_0423.JPG…]()
![Uploading DJI_0424.JPG…]()
![Uploading DJI_0425.JPG…]()
![Uploading DJI_0426.JPG…]()
![Uploading DJI_0427.JPG…]()
![Uploading DJI_0428.JPG…]()
![Uploading DJI_0429.JPG…]()
![Uploading DJI_0430.JPG…]()
![Uploading DJI_0431.JPG…]()
![Uploading DJI_0432.JPG…]()
![Uploading DJI_0433.JPG…]()
![Uploading DJI_0434.JPG…]()
![Uploading DJI_0435.JPG…]()

**Comment by pierotofy** [comment]
Hi, unfortunately 6GB is not a whole lot of memory for the number of images you are trying to process, especially with PMVS. I would try to modify your VirtualBox settings to decrease the number of CPUs to one. This will slow down processing, but should reduce memory usage as well.

**Comment by LRDquarry** [comment]
On first look, it appears to be set to 1.
Btw, should the Virtualbox interface remain open after i shut down WebODM? I always need to restart the computer to make it clear out.

**Comment by pierotofy** [comment]
You can safely close the Virtualbox interface.

If you remove the pmvs flag, are you able to process the images? Is it just that the trees look "bulky" with the default?

**Comment by pierotofy** [comment]
This issue was moved to http://community.opendronemap.org/t/processing-error-when-i-try-over-151-pictures-the-first-101-work-fine/41

**Comment by LRDquarry** [comment]
I was trying only with defaults for 101 and 150. Have since run on 125 but
it fails too.

Ultimately I am trying to use drone pics to identify and locate trees for
forestry application. I tried dronedeploy and precision hawk, decided I
need more control and access.

Is there a better way that you (or anyone else) know of?
I am even prepared to pay for tutoring or coding the workflow.
