### ISSUE TITLE
Endless restarts on initial startup

### ISSUE THREAD

**Issue by taudronis** [OpenDroneMap/WebODM#309]
### How did you install WebODM? (Docker, natively, ...)?
Followed the PDF to the letter.  No steps skipped

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
whatismybrowser.com/w/LZJAEJK

### What is the problem?
Initial startup of WebODM says it needs to disconnect my network momentarilly.  Then I get a success message with a restart required.  After restart, and startup of WebODM it says the same thing all over again.

### What should be the expected behavior?
Actually be able to use the software

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Haven't gotten as far as processing.  Just trying to start the software.

![image](https://user-images.githubusercontent.com/10343653/31974834-26ec7d3e-b8f3-11e7-8734-429175b69b8a.png)
![image](https://user-images.githubusercontent.com/10343653/31974846-368960c2-b8f3-11e7-9c43-0c717c1ca8ac.png)
![image](https://user-images.githubusercontent.com/10343653/31974854-49b4cf60-b8f3-11e7-93ce-b4c35f79984e.png)
![image](https://user-images.githubusercontent.com/10343653/31974880-7c056dda-b8f3-11e7-8760-890d57d77a63.png)

**Comment by pierotofy** [comment]
Hi @taudronis thank you for the detailed report. I e-mail you a few minutes ago in response about the same inquiry.
