### ISSUE TITLE
Feature request: Photo camera locations map

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#312]
http://community.opendronemap.org/t/feature-request-photo-camera-locations-map/66

**Comment by KommandorKeen** [comment]
Not sure we need this, if I load the files into cloud compare I can see image locations.

**Comment by pierotofy** [comment]
Yeah this feature would be to include them directly in the WebODM interface.

**Comment by pierotofy** [comment]
This is done!

**Comment by smathermather** [comment]
So cool, too.
