### ISSUE TITLE
Can't start WebODM

### ISSUE THREAD

**Issue by Yes21** [OpenDroneMap/WebODM#313]
I've installed WebODM on Ubuntu 17.04 with Docker.

When I try to start it (./webodm.sh start), I have the following output : 

Checking for docker...   OK
Checking for git...   OK
Checking for python...   OK
Checking for pip...   OK
Checking for docker-compose...   OK
Starting WebODM...
docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml start || docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up
Starting db         ... 
Starting node-odm-1 ... 
Starting webapp     ... error

ERROR: for db  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for node-odm-1  ('Connection aborted.', error(13, 'Permission denied'))
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Could you help me to solve this problem ?

YveS

**Comment by pierotofy** [comment]
Hi @Yes21, this is probably a problem related to how you setup docker. Is your user part of the `docker` group? Also, make sure you log-in and out after you've added the group to your user.

**Comment by pierotofy** [comment]
`sudo adduser <youruser> docker`

**Comment by Yes21** [comment]
That was the problem. Now all is ok, and after a lot of downloads, I can now start WebODM in my browser. I will test it with my own georeferenced pictures to create orthomosaic.
Many thanks for tour help.
YveS
