### ISSUE TITLE
About GCP file and "Skip-resize" option

### ISSUE THREAD

**Issue by kirby031** [OpenDroneMap/WebODM#320]
Hi, i am trying to run some images and i used to have the problem with GCP, I used to resolve it with skip-resize, so i have two questions:

- What happened with the skip-resize option? I have problems with the shape of the results, it is in the correct place but the image is smaller than the reality.

- When I use GCP files, do i have to put it in projected coordinates or it could be in geographic( EPSG:4326), and i read that it is better putting ESPG:XXXX than WGS 84 XXN/S?

**Comment by pierotofy** [comment]
Good questions, could we move this conversation over to https://community.opendronemap.org/c/webodm (open a thread there?)

Thank you!
