### ISSUE TITLE
Operational Error attempting to Login

### ISSUE THREAD

**Issue by uasimagery** [OpenDroneMap/WebODM#321]
Hi everyone,

I have received this error just today. I updated the webodm.sh file to include brand and theme additions then processed about 500 images yesterday and all was working well. I tried to log back in today and was presented with some sort of problem. Was hoping someone could help me out.  Screen shots and log attached. Thanks in advance.

Tim
![docker-machine](https://user-images.githubusercontent.com/31360590/32695264-7f966996-c7bb-11e7-9d42-4e431dae918f.png)
[log.txt](https://github.com/OpenDroneMap/WebODM/files/1464319/log.txt)
![operationalerror](https://user-images.githubusercontent.com/31360590/32695265-7ff8758c-c7bb-11e7-8207-24cde4f339e0.png)

**Comment by pierotofy** [comment]
Try restarting your computer.

If that doesn’t fix it, issue a ‘./webodm.sh down’ followed by start.
