### ISSUE TITLE
Hard to understand installation directions

### ISSUE THREAD

**Issue by dalearn** [OpenDroneMap/WebODM#323]
As someone unused to docker, can you update the installation directions please?  Do I need to set up a new docker container first?  If so how would I go about doing that on Linux and after that, how would I run this program?  I just want to stitch together my images using this awesome program

**Comment by pierotofy** [comment]
Hi @dalearn, have you followed the README? What parts are not clear?

**Comment by dalearn** [comment]
I downloaded docker and after much struggle finally got the config file to run but it appears to be downloading hundreds of files.  What are these files for?

**Comment by jupeuav** [comment]
I am also having issues with the install. I followed the instructions got 'Getting Started'. Entered the command into terminal and everything seems to run fine until I get to the below:

Starting webapp     ... error

**Comment by dalearn** [comment]
make sure you log out and log back in...   I saw "ERROR: No containers to start" in there somewhere but now all I see is a bunch of downloads.

**Comment by dalearn** [comment]
It has almost entirely used up my disk storage and is still going!

**Comment by dalearn** [comment]
I finally figured out the problem, I was getting the error: `standard_init_linux.go:195: exec user process caused "exec format error"` which appears that I was using an X86 image.  How could I obtain an ARM image?

**Comment by pierotofy** [comment]
@dalearn your first step would be to compile OpenDroneMap from sources. I'm not sure this has been attempted before, but could be worth a try. Unfortunately I don't have precise guidelines on how to do this, start from https://github.com/OpenDroneMap/OpenDroneMap#diving-deeper and see if you can make it work.

**Comment by pierotofy** [comment]
Might also be worth to open a discussion on http://community.opendronemap.org to see if anybody else has done it before.

**Comment by dalearn** [comment]
How would I compile it from sources?  After I pull it from Github, what do I do?  Where do I go to compile it?

**Comment by dalearn** [comment]
As a web developer who usually stays within the confines of my IDE, I am trying to run this on a Raspberry Pi and I just want it to run instead of having to install all sorts of things.  I am going to a high profile conference soon and would like to use this and promote this because it is open source.

**Comment by pierotofy** [comment]
Mm, I would discourage using a Raspberry PI, I doubt you'll have enough memory to process any meaningful dataset size. Use a build similar to this if you're looking for portability: http://posm.io/getting-a-posm/

**Comment by dalearn** [comment]
could I chain two raspberry pis or use a mac?

**Comment by pierotofy** [comment]
You could use a Mac (if it's Intel-based). You cannot chain two raspberry pis.

**Comment by dalearn** [comment]
Would 8GB of RAM be enough?  How would I install it on MacOS without using the terminal a bunch?

**Comment by pierotofy** [comment]
Yes 8GB will get you up and running. Just follow the instructions here: https://github.com/OpenDroneMap/WebODM#getting-started

**Comment by dalearn** [comment]
It says something about node-opendronemap, Could I use an army of Pis running that or would it again be too big?

**Comment by pierotofy** [comment]
Unfortunately no, you couldn't use an array of PIs. The processing is too memory intensive.
