### ISSUE TITLE
Memory issues with Docker - Help with Native install Mac OS High Sierra

### ISSUE THREAD

**Issue by kaaspad** [OpenDroneMap/WebODM#338]
### How did you install WebODM? (Docker, natively, ...)?

First with Docker - was having memory problems (exited with processing error 1) due to trying to process about 500 Hi Res images - when lowered resolution and number of images significantly then didn't have problem. Unfortunately I need to run it at hi res and a large amount of images for Search & Rescue operations. Therefore trying to switch to native install on Mac OS High Sierra - but having many issues installing.

### What's your browser and operating system? 
Chrome 62 on Mac OS X 10
macOS High Sierra - Version 10.13.1
2.8 Ghz Intel Core i7
16GB 1600 Mhz DDR3

### What is the problem?

After running many trials with Docker it seems that after passing a certain threshold of number of images combined with high resolution the system exits - "Exited with Processing Error 1" - when reducing the number of images or lower the resolution significantly or in some cases removing certain flags it would process with the docker. 
The problem is that I need it to run with all the images and hiRes so I tried going down the native route that way I would not be memory bound by docker (16gb native with hoards of memory available from system cache).
The problem is the native install is foobar'd on Mac because of requirements....
1. Python - 2.7 is native on mac, of course installed python3 which gives me python 3.6.3 but doesn't seem to be available to all the other dependancies install (via home-brew)
2. GDAL on home-brew is 1.11 - there is a package of GDAL 2 via a third party source on home-brew (GDAL 2.2.2) which I have installed but it seems that both python and postgis still try to use GDAL 1.11 - which cannot be installed because of the internal hombrew postGIS dependency.
3. The default dependancies on unsupported versions are creating a very complex issue trying to export the correct PATH as well as symlinking the correct versions within the brew environment under /usr/local/bin.

So essentially my question is has anyone installed this natively on a mac and if so is there some easy doc I can follow that will fix the version dependancies and still keep it clean (meaning using everything under /usr/local/bin

### What should be the expected behavior?

umm easy native installation on mac? or figuring out how to have docker not run out of memory... (although that is not a webODM problem - what is, is having a more elegant handle for when memory gets low)

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

1. Regarding the docker problem use about 300 images from a Mavic Pro at hi res and you will for sure run in to the memory problem.
2. try installing natively on macOS...

**Comment by pierotofy** [comment]
Hi @kaaspad, unfortunately even though you could run WebODM natively, node-OpenDroneMap still requires docker on a Mac (that's where processing happens). If you are running in memory issues and you want to squeeze as much memory as possible from your machine, you'll need to install Linux (Ubuntu 16.04 is recommended).

I'll close this as for now, as it's not a software fault.
