### ISSUE TITLE
Automated Undistortion and Camera Calibration (and public database)

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#340]
People are often getting distorted results because they do not undistort camera images before feeding them into WebODM (nor should they have to).

WebODM should offer an intuitive way to:
 - Undistort images based on camera parameters
 - Extract camera parameters based on a chessboard pattern
 - Create a public database of camera parameters and allow users to easily contribute their results

**Comment by pierotofy** [comment]
A workflow could be similar to that of Agisoft Lens. http://downloads.agisoft.ru/lens/doc/en/lens.pdf

**Comment by pierotofy** [comment]
Note also that opensfm already does camera calibration, and perhaps it's just a matter of tuning the configuration better there.

**Comment by dakotabenjamin** [comment]
What can we glean from the lensfun database?

**Comment by pierotofy** [comment]
Lensfun is a good starting point, but the process to add new cameras in the database is painful.

**Comment by juvinski** [comment]
Hi @pierotofy and @dakotabenjamin  how are this issue ? How can I help ?

**Comment by pierotofy** [comment]
Closing this due to infeasibility; the benefits of such system would be minimal and the burden of creating a database would be large.

**Comment by smathermather** [comment]
Agreed: consensus is that arguably for any commodity cameras, this would provide 0 benefit. For fixed lens, calibrated cameras, the user should be bringing their own. Anecdotally, even a $20k Hasselblad can have variations between cameras in focal distance and principle point of 10%.

**Comment by pierotofy** [comment]
Yep.

**Comment by kf4mot** [comment]
I'm a very new user to ODM, but I come with a astro-imaging background.
In that world it's normal for a user to shoot calibration images (flats, bias, darks) that are used to take care of things like dust motes, vignetting, distortion . I was a little surprised to see a similar calibration wasn't needed for ODM.

**Comment by smathermather** [comment]
It surprised me too and flew in the face of everything I knew about photogrammetry.

The challenge for most drone users (the higher end DJI, some Sensefly and other exceptions perhaps withstanding) is that he cameras are so small and light, so subject to vibration and temperature variation, that it isn't that ODM wouldn't benefit from calibration information, but that one would probably have to calibrate for each flight, or worse. 😄 

So, we recommend instead good flight planning to allow for good self-calibration.
