### ISSUE TITLE
Uploading images gets stuck

### ISSUE THREAD

**Issue by thomas-bamford** [OpenDroneMap/WebODM#344]
### How did you install WebODM? (Docker, natively, ...)?

Docker with SSL on Ubuntu 16.04 LTS Desktop. Updated to latest version. Installation steps taken available upon request.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 57 on Linux, Chrome 62 on Linux

### What is the problem?

Stops uploading images (only reaches 5-10% before stopping) when adding new task when computer is on wifi. The dataset is only 492 Mb in size with 74 images but the upload size reports 34 Gb (See screenshot [here](https://goo.gl/djHVyL)).

### What should be the expected behavior?

Two days ago (prior to updating to SSL support) the same dataset was able to be uploaded with no issue (when computer is on wifi).

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Remote computer connected to wifi with latest webodm installed on host. Default parameters except skipping resize. If resize is selected same result (stops uploading after resize). Dataset available upon request.

**Comment by thomas-bamford** [comment]
Sorry forgot to check for similar issues - see #343

**Comment by pierotofy** [comment]
Hi @thomas-bamford, thank you for reporting the problem! This is definitely a software fault, I opened a PR that should address this problem #345. I will likely merge this by EOD and rebuild the docker containers.

**Comment by pierotofy** [comment]
@thomas-bamford could you try to update and confirm that this is now resolved?

**Comment by thomas-bamford** [comment]
@pierotofy updated and can confirm that this issue is now resolved.
