### ISSUE TITLE
I tried to process an image set and got an error in the middle

### ISSUE THREAD

**Issue by cppriyankara** [OpenDroneMap/WebODM#346]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 57 on Windows 8.1

### What is the problem?

I tried to process an image set and got an error in the middle.

### What should be the expected behavior?

Help me to solve the issue.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

https://www.dropbox.com/sh/u8bdmxyeux8kkot/AAAUhwwCeCK2rxnvDQHLoLeVa?dl=0

The folder contains,
Images (all .JPG)
GCPs list (gcp_list.txt)
Task output (task_output.txt)

**Comment by pierotofy** [comment]
Code 137 means that your process was killed, so you basically ran out of memory!

See http://support.divio.com/local-development/docker/managing-disk-space-in-your-docker-vm and https://www.howtogeek.com/124622/how-to-enlarge-a-virtual-machines-disk-in-virtualbox-or-vmware/
