### ISSUE TITLE
Failed at setting up development environment

### ISSUE THREAD

**Issue by Pratyush1991** [OpenDroneMap/WebODM#351]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 57 on Windows 10
Installed Webodm on OS: Ubuntu 16.04.03 LTS on AWS with t2.micro instance

### What is the problem?

![image](https://user-images.githubusercontent.com/28738918/33444998-520ff2b8-d62e-11e7-9596-76d3073a7e7c.png)

### What should be the expected behavior?

Need help

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I did follow the development guide as mentioned in webodm docs. Before staring the development mode I ran in normal mode it worked without any error.

**Comment by pierotofy** [comment]
Hi @Pratyush1991, could you make sure that you are running `./devenv.sh` from a clean git clone?

I have tried to replicate the problem but things seemed to work OK.

**Comment by Pratyush1991** [comment]
Hello, 
As you mentioned I did clone the repository in a new directory. Still I am getting the same error. 
![image](https://user-images.githubusercontent.com/28738918/33508770-29dfad0e-d72f-11e7-82b6-613fe7d0025b.png)

Sorry I am a bit new to development so may be I am missing something. And I am also getting this deprecation warning is that a problem or is it normal..?
![image](https://user-images.githubusercontent.com/28738918/33508942-1e2ea3e2-d730-11e7-9c2c-9f3328672230.png)

**Comment by pierotofy** [comment]
Deprecation warnings are normal. Are you able to open the web interface at localhost:8000?

**Comment by Pratyush1991** [comment]
No I am unable to load the web interface.

**Comment by pierotofy** [comment]
Just as a heads up, I don't think you'll be able to run WebODM on a `t2.micro` instance, you need more RAM than 1GB. I wonder if the errors are related to that. Could you try to run this on a machine with more memory?

**Comment by Pratyush1991** [comment]
But when I am running ./webodm.sh start in my t2.micro instance it is running fine. Even i can access the web interface. Images attached below
![image](https://user-images.githubusercontent.com/28738918/33511254-fafbcbf6-d749-11e7-9dcd-1e605cb9e569.png)

Web interface
![image](https://user-images.githubusercontent.com/28738918/33511341-b18ece62-d74b-11e7-89fa-253374b2b965.png)

As you said I also scaled up my instance to t2.large and tried to run ./devenv.sh but was unsuccessful. Image below is the error when I tried to access the web interface

![image](https://user-images.githubusercontent.com/28738918/33511675-a08898e0-d751-11e7-8455-87e53a33b957.png)

**Comment by pierotofy** [comment]
There's no build step involved when running WebODM normally, so I would expect memory usage to be lower then.

That error happens because you probably started from a non-clean clone? Make a clean clone, then try again.

**Comment by Pratyush1991** [comment]
Thanks a lot its working now. The problem was with RAM and non-clean clone.

And Is it ok if I use ctrl+z to move back to dir to make some changes. Because I am not sure how to run the script in background as once I run ./devenv.sh I'm stuck inside inside it.

**Comment by pierotofy** [comment]
No CTRL+Z will probably pause the process. Use `screen`:

```
# screen
<press enter>
# ./webodm.sh start
<press CTRL+A followed by CTRL+D> to detach
```

**Comment by Pratyush1991** [comment]
Thanks a lot again.
