### ISSUE TITLE
Task killed at end of processing

### ISSUE THREAD

**Issue by CrileNZL** [OpenDroneMap/WebODM#363]
### How did you install WebODM? (Docker, natively, ...)?

Run via Docker on a 64-bit Win7 laptop with 8 Gb RAM.  I've allocated 5 Gb of RAM to the VM and resized storage to 100 Gb.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 56 on Windows 7

### What is the problem?

After two hours processing 40 images, task was killed.  A subset of the first five images in the dataset ran to completion though results weren't great (orthophoto was very patchy and data layers were offset from true location)

### What should be the expected behavior?

Task runs to completion

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

dataset [here](https://drive.google.com/drive/folders/1sbncW_TZ5mJ9jBiGhfUv4RpS30XOs6az?usp=sharing)

Parameters were set to:

- min-num-features: 100000
- resize-to: 2048
- dem-terrain-type: FlatNonForest
- dsm: true
- opensfm-processes: 1
- use-pmvs: true

It seemed like it was getting to the end of the processing - console output showed multiple variations of:  "webapp    | WARNING Run time of job "background.<locals>.wrapper <trigger: interval[0:00:05], next run at: 2017-12-11 05:52:17 UTC>" was missed by 0:00:03.27742".

task_output.txt attached.
[task_output.txt](https://github.com/OpenDroneMap/WebODM/files/1546770/task_output.txt)

I've had a difficult time getting WebODM configured properly and hadn't seen "Killed" in any outputs previously.  Any suggestions are welcome.

Crile

**Comment by pierotofy** [comment]
Hi @CrileNZL, WebODM should have showed a message like this:

```
It looks like your processing node ran out of memory. If you are using docker, make sure that your docker environment has enough RAM allocated.```

And the suggestion is accurate, you need more memory to process that dataset at the resolution you are trying to process it. Note that something is off because you say you passed the `resize-to` parameter, but your images are being processed at 6000 x 4000. Make sure you've updated your node-opendronemap and WebODM docker images to the latest version.

`./webodm.sh update`

**Comment by CrileNZL** [comment]
Thanks Peiro,

I’m struggling to see how I can increase my RAM – the virtual box has been allocated 5 of my 8 Gb and I have ensured the resize is at 2048 x 1365 as well as resetting the orthophoto-resolution from 20 to 5.  If I understand that parameter correctly, it’s the number of pixels per metre so 5 should be a lower resolution than the default, correct?  I’ve also reduced the number of images from 30 to 40.  Before this set of runs I ran ./webodm.sh update so I should be up to date with the latest versions.

Still crashing out of memory.

Thanks –

C

**Comment by pierotofy** [comment]
5GB about the max you'll be able to assign to a 8GB host. Also reduce `min-num-features` (leave the default, unless you're not getting good results), 100000 is probably way too high.

**Comment by CrileNZL** [comment]
A quick follow up. I’ve rerun WebODM with the following parameters as suggested:

·         Min-num-features: 6000

·         Orthophoto-resolution: 5

·         Dem-resolution: 1

·         Dem-terrian-type: FlatNonForest

·         Use-pmvs: true

Task_output.txt attached.

While running this I had a resource monitor open and while it ran (for 00:01:48) I had between 3 and 3.5 Gb free in working memory.  Is there somewhere else I could be getting tight on memory?

Thanks –

C

**Comment by pierotofy** [comment]
If there are further questions about this subject,  according to the [guidelines](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md) please let's move them to the forum. http://community.opendronemap.org/c/webodm
