### ISSUE TITLE
Ability to stream/access lower resolution models

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#383]
Necessary for #316 https://github.com/pierotofy/webodm-ar/issues/2

Could also be nice to speed up WebODM's built-in 3D viewer.

**Comment by pierotofy** [comment]
Thanks @smathermather! I'm having a hard time finding the multi-resolution extension you mentioned. This is the closest I found in their docs: http://vtsdocs.melown.com/en/latest/reference/server/cmdline-tools/encoders.html

Maybe it's not documented?

**Comment by smathermather** [comment]
They should be here at FOSS4G. Let’s ask!

**Comment by pierotofy** [comment]
Possibly relevant: https://github.com/cnr-isti-vclab/corto

**Comment by pierotofy** [comment]
We could use https://github.com/DroneDB/libnexus or the novel `--3d-tiles` outputs for meshes.

**Comment by pierotofy** [comment]
Also another option could be to display better compressed GLTF/GLB models. Most of the weight is due to the large textures which are mostly in PNG format. Some JPEG compression could go a long way.

**Comment by smathermather** [comment]
Yes, switching to JPEG compression would fix 90%+ of these cases.

**Comment by Saijin-Naib** [comment]
How about AVIF textures? We'd have very advanced compression that would outperform other lossy compression, support for arbitrary band numbers, and support for lossless alpha as well as optional lossless encoding. Plus, browser and OS support is good and it is open and actively improving constantly.

**Comment by pierotofy** [comment]
Not enough bandwidth for this at the moment, plus GLB models now mitigate this issue quite well.
