### ISSUE TITLE
Access-Control-Allow-Origin header contains multiple values '*, *' 

### ISSUE THREAD

**Issue by ligai322** [OpenDroneMap/WebODM#389]
### How did you install WebODM? (Docker, natively, ...)?
Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 63 on Windows 10

### What is the problem?

my website remote call webodm api ,  like  https://demo.webodm.org/api/projects/?format=json

my code:
![image](https://user-images.githubusercontent.com/3262486/35856173-22e9165a-0b70-11e8-8466-2b05173683aa.png)

the response:
![image](https://user-images.githubusercontent.com/3262486/35856219-498dfbae-0b70-11e8-9750-f2f2b2161cfc.png)

error infomation:
![image](https://user-images.githubusercontent.com/3262486/35856239-5e2510a2-0b70-11e8-982b-3a387647356f.png)

**Comment by pierotofy** [comment]
This looks like it's caused by both Django and nginx are adding their headers (duplicated in this instance).

This could likely be solved by modifying `/nginx/nginx.template.conf` by removing the appropriate header directives.

**Comment by pierotofy** [comment]
These changes will be reflected once we update the webodm_webapp image on docker hub, or when somebody rebuilds the image from scratch.

The demo site might continue to have the issue until next time we update it.

**Comment by ligai322** [comment]
Thanks
