### ISSUE TITLE
Option to discard images after processing

### ISSUE THREAD

**Issue by dirceup** [OpenDroneMap/WebODM#392]
My use of WebODM is through the API.
Users uploads images in my application then can execute a processing. Uploaded images are stored in my application folder as well "thumbnail" versions I generate to display a "Image gallery". Images names are stored in database.

When user ask for a processing I create a task in WebODM and upload users uploaded images there. WebODM stores the images in media/project/x/task/y/ folder.

I do allow re-processing but this is for when there is changes in the image list (more uploads or deletions), and which I treat removing the old WebODM task and creating a new one.
So after processing images in media/project/x/task/y/ folder became useless for me and I'm doing a ```rm *.{jpg,JPG}``` in the task folder when I get a processed task (failed ou completed).

I asked in gitter if there is a option to discard images after processing and it looks like it's something that could exist.

In fact node-opendronemap is also keeping their copy of images. But that is another history.
Thank you.

**Comment by pierotofy** [comment]
Closing in favor of #671  (same issue)
