### ISSUE TITLE
3D Model Display

### ISSUE THREAD

**Issue by mojodna** [OpenDroneMap/WebODM#4]
ODM-generated 3D models should be browsable using a Cesium-like interface.

Needs display and manipulation of the following:
- Point clouds
- Textured Mesh

**Comment by pierotofy** [comment]
It is possible to display both 3D models and Point Clouds using Cesium, some research and development needs to be done to convert the resulting models to 3D tiles, but it should be feasible: https://cesiumjs.org/Chappes/index.html http://cesiumjs.org/2015/08/10/introducing-3d-tiles/

**Comment by smathermather** [comment]
3D tiles don't scale well. See http://speck.ly or http://potree.org/ for really well scaled point clouds. I agree Cesium may be the best option for textured meshes. This I know much less about.

**Comment by pierotofy** [comment]
potree.org looks pretty good! Nice find.

**Comment by smathermather** [comment]
potree has implemented the octree optimizations necessary for rapid and beautiful viewing of point clouds, which I think is also in the pipeline for what you see at speck.ly.

The ecosystem around https://speck.ly (including https://plas.io, etc.) solves the data storage and delivery end of things, plus some of the display issues.

@hobu -- can you point @mojodna and @pierotofy to best resources here?

**Comment by hobu** [comment]
> 3D tiles don't scale well

3D tiles scale just fine. It's just they aren't done yet for point clouds.

**Comment by spatialhast** [comment]
Using https://threejs.org/ possible display Textured Mesh using direct loading data (example https://threejs.org/examples/webgl_loader_obj_mtl.html). Example textured mesh data viewer using three.js available on https://spatialhast.github.io/tmviewer/ link. In this example used textured mesh from 'odm_data_toledo' and three.js templates from https://github.com/kaisalmen/WWOBJLoader by @kaisalmen. On viewer https://spatialhast.github.io/tmviewer/index_geo.html displayed data 'black' color - there is used Georeferenced textured mesh.

**Comment by smathermather** [comment]
Whoa! This is great info @spatialhast!

**Comment by pierotofy** [comment]
Currently looking at http://osgjs.org/, which is the library that's being used by sketchfab for their 3d model viewer.

**Comment by pierotofy** [comment]
This has been added as part of #78, thanks everyone for your input!

**Comment by smathermather** [comment]
w00t!
