### ISSUE TITLE
[QUESTION] Can I get the GPS coords of a particular vertex from the 3D model?

### ISSUE THREAD

**Issue by FarhadG** [OpenDroneMap/WebODM#404]
I haven't had much experience working with Geo referenced models. I'm curious how I can incorporate GPS coords into the 3D previewer by being able to reference them to do accurate measurements or mapping out to real world actions based on those coords.

**Comment by pierotofy** [comment]
@FarhadG could we move this question to the forum? http://community.opendronemap.org/c/webodm

Thank you! I'll close this for now.
