### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by s6mastra** [OpenDroneMap/WebODM#409]
Hi,

[task_output.txt](https://github.com/OpenDroneMap/WebODM/files/1810748/task_output.txt)

### How did you install WebODM? (Docker, natively, ...)?
installed Docker Toolbox on Windows 7, and then ODM over the Terminal

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 58 on Windows 7

### What is the problem?

Processing images results in the following error message: Process exited with code 1
The full log is wihtin the task_output.txt 

### What should be the expected behavior?
 
Pointcloud/3D Image Output

**Comment by pierotofy** [comment]
Hi @s6mastra this should have been fixed now. Please update and let us know if the problem still occurs. :clinking_glasses:
