### ISSUE TITLE
Could not upload all files. An error occurred. Please try again.

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/WebODM#434]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system?

Chrome 65 on Windows 10 is what it reveals as, but really it's Brave.

### What is the problem?

Upload of images to WebODM fails with the message "Could not upload all files. An error occurred. Please try again."

### What should be the expected behavior?

Upload of files, and start of processing.

**Comment by pierotofy** [comment]
Does it work on other browsers (Firefox)? Do you get any error messages if you open the web console in Brave?

**Comment by smathermather** [comment]
As far as I can tell, Brave doesn't have a web console. That doesn't seem possible, but I can't find it.

**Comment by pierotofy** [comment]
@wondo2 if you open the Chrome console (press F12) and go to the Console tab, do you see any error messages?

**Comment by pierotofy** [comment]
Will look into it, thanks.

**Comment by pierotofy** [comment]
@smathermather do you get the same problem is you use Firefox or Chrome?

**Comment by smathermather** [comment]
I haven't had the issue with Firefox or Chrome.

**Comment by DelphiR** [comment]
I got such type of errors several times but it was during dowloading for me.
So I introduced in the bug and see that the sometimes attempt to download a big file set (all asset) cuase to get more 2Gb of Ram to task. So the kernel may kill the task. so after that I get the 500 error

**Comment by pierotofy** [comment]
WebODM now implements chunked uploads, which should have fixed these errors. If there are still problems, please re-open. :clinking_glasses:
