### ISSUE TITLE
Remove reset password link

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#446]
Users are getting confused because the "reset password" link actually cannot send e-mails. Better to instruct them on how to reset the password via terminal.

**Comment by Bornlove** [comment]
Hello @pierotofy 
have tried to reset password but when trying to log in it still rejects, does this cmd ./webodm.sh resetadminpassword yournewpass changes Username as well?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by Bornlove** [comment]
> Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍

Thanks for kindly reply @pierotofy. Appreciate
