### ISSUE TITLE
Add support / visualization for COG (Cloud Optimized Geotiffs)

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#449]
It would be interesting to explore COGs as an alternative/complement to tiles: https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF#HowtogenerateitwithGDAL

http://www.cogeo.org/

https://github.com/geotiffjs/geotiff.js

https://geotiffjs.github.io/cog-explorer/

**Comment by smathermather** [comment]
This is a great idea, and would make distribution of the data products so much better.

**Comment by pierotofy** [comment]
This one looks REALLY promising. https://github.com/DHI-GRAS/terracotta

Will do some research.

**Comment by pierotofy** [comment]
Note to self: to access api docs use http://localhost:5001/apidoc

**Comment by pierotofy** [comment]
This is now implemented as part of #746 :clinking_glasses:
