### ISSUE TITLE
Very long lag in browser responding to user input in the webODM interface.

### ISSUE THREAD

**Issue by DaveSprague** [OpenDroneMap/WebODM#483]
How did you install WebODM? (Docker, natively, ...)?

I did a manual docker install of WebODMr according to the instructions provided.

What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 67 on Windows 10 Pro version 1803, build 17134.112
I also experience the same problem with using Microsoft's Edge browser

### What is the problem?

The browser hangs for a many seconds to several minutes when you select any of the task related functions such as "Download Assets", "View map", etc.

This occurs both when a task other tasks are running but also when no task is running.

I believe this is happening because the client is waiting to fill in very long logs into the scrollable log text box.

### What should be the expected behavior?

The web interface should be more responsive.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I don't think there's anything special I'm doing that's causing this to happen but I'm not sure.  It might be exacerbated by very lengthy error/warnings I'm getting (see issue [#482 ](https://github.com/OpenDroneMap/WebODM/issues/482)

**Comment by pierotofy** [comment]
Thanks for pointing this out @DaveSprague. This is definitely an area that requires improvement. At some point we're going to hide the full log in favor of #398, so that should improve performance.

**Comment by pierotofy** [comment]
Fixed with #571
