### ISSUE TITLE
E-mail notifications

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#49]
Users should be notified via e-mail when processing has finished.

**Comment by pierotofy** [comment]
Difficulty of setting up e-mail servers, plus nobody has asked for this. Closing.

**Comment by TheDiscordian** [comment]
Hey I was just about to ask for this, any chance it could be on the table again? Otherwise, I'll just look into getting the feature into a plugin :).

**Comment by pierotofy** [comment]
Hey @TheDiscordian :hand: we'd welcome a contribution for this. We closed it because there wasn't sufficient interest and none stepped in to develop it. But I'm sure it would be useful to others if built.
