### ISSUE TITLE
Killed after merging depthmaps

### ISSUE THREAD

**Issue by xmutantson** [OpenDroneMap/WebODM#491]
### How did you install WebODM? (Docker, natively, ...)?

WebODM was installed through the manager, which is running docker-machine on virtualbox.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

https://whatismybrowser.com/w/T68G4Q9

### What is the problem?

Even though I have 15 GB (!) of ram allocated to docker-machine, I still get 'Killed' after merging depth maps. I watched the process closely. RAM reporting is difficult with virtual machines, so I watched the total. At rest, OS uses 6-7 GB. i have 24 GB. For 'Killed' to be a RAM capacity issue, I would expect the RAM usage to jump to 22 GB, but it was at 16 GB total, about 9 or 10 of which I expect to be docker. This leads me to suspect another root cause. I'm trying to process 300 images with about 80% overlap for 3d.

[code]
Killed
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/run_opensfm.py", line 157, in process
(context.pyopencv_path, context.opensfm_path, tree.opensfm))
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception
: Child returned 137
[/code]

### What should be the expected behavior?

If it was a RAM error I expect that it would at least try to use all the available ram before killing itself.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Options: force-ccd: 6.16, use-exif: true, verbose: true, rerun-from: dataset

[console out]
https://drive.google.com/file/d/1zteKykKYaX-a03RdMnp5q-Oj1ByuLLlY/view?usp=sharing

[VBox.log]
https://drive.google.com/file/d/1VRWIaxqsibRnKgGri1utKok9v__utvsn/view?usp=sharing

[VBoxHardening.log]
https://drive.google.com/file/d/1VmfsBEEeITwdoRWr3HLeKZjawU3hzuSu/view?usp=sharing

**Comment by pierotofy** [comment]
Hey @xmutantson :hand: unfortunately this is not another error, you simply didn't have enough memory to continue processing. Something you can try is to lower the `opensfm-num-processes` value (start from 1), which will lower the memory requirements for the step where it failed.

Measuring RAM usage of a virtual environment is not as straightforward as opening the task manager. https://serverfault.com/questions/19935/virtual-machine-memory-usage-not-appearing-in-taskmanager

If you have further questions, please let's move the conversation over to https://community.opendronemap.org

Thank you!
