### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mojodna** [OpenDroneMap/WebODM#5]
WebODM should implement the following endpoints:
- authorization
- list projects (`Project`) :ballot_box_with_check:
  - [filtered by `User`] :ballot_box_with_check:
  - [filtered by `Group`]
  - [filtered by geographic extent]
- list tasks (`Task`) :ballot_box_with_check:
- create tasks (`Task`) :ballot_box_with_check:
- update tasks (`Task`) ☑️ 
- list/add/change processing nodes ☑️ 
- ability to start/stop processing a `Task`☑️ 
- get project info :ballot_box_with_check:
  - TileJSON / equivalent
  - 3D model stuff
- create project :ballot_box_with_check:
- create mission
- get mission info
- ...

**Comment by pierotofy** [comment]
I would add:

- ability to start/stop processing a Map / Task

**Comment by mojodna** [comment]
Do you have the ability to edit the first comment? We can treat that as a living doc.

**Comment by pierotofy** [comment]
Yes, done! Good idea.

**Comment by pierotofy** [comment]
I've started working on this, since most of the UI will need to use this.

**Comment by pierotofy** [comment]
This can probably be closed, we have a good starting set of APIs.
