### ISSUE TITLE
Easily Deployable Field Machine (no internet)

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#507]
It has been suggested at the drone panel that there should be a way to easily deploy an opendronemap machine in the field. This could be in tbe form of a small computer with enough RAM with a USB live image with WebODM pre-installed.

**Comment by mojodna** [comment]
I'm in the process of incorporating WebODM with POSM for offline use (and intend to include cluster-awareness so that supplemental machines can be provisioned with node-odm).

**Comment by danbjoseph** [comment]
see `superposm` and `posm-aux` in https://github.com/posm/posm-build/tree/master/live
and the [releases link](https://github.com/posm/posm-build/releases)
