### ISSUE TITLE
Always show a button to download or copy to clipboard task outputs

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#511]
This can be useful for debugging.

**Comment by aaj013** [comment]
I'd like to work on this!

**Comment by pierotofy** [comment]
I don't think anyone is currently working on this, so go for it :+1:

**Comment by aaj013** [comment]
Please check the buttons positioning in UI (screenshot below)
![copy-download-task-outputs](https://user-images.githubusercontent.com/5847582/47155341-23463880-d302-11e8-892f-a6421654a65b.png)

**Comment by pierotofy** [comment]
PR merged. Thanks!!

**Comment by pierotofy** [comment]
@aaj013 The current webodm docker image does not have the PR as of yet. We'll include it soon. No action required on your part.
