### ISSUE TITLE
JavaScript exceptions on view map: "TypeError: Cannot create property '_leaflet_id' on string 'Google Maps Hybrid'"

### ISSUE THREAD

**Issue by DarylWM** [OpenDroneMap/WebODM#515]
### How did you install WebODM? (Docker, natively, ...)?

Docker - macos installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

https://whatismybrowser.com/w/BGTEXBP

Issue is also on Safari Version 11.1.2 (13605.3.8).

### What is the problem?

Since upgrading today to the latest release using WebODM Manager 1.1 (WebODM is version 0.6.1), all my maps are completely blank when I 'view map'. 
<img width="1277" alt="screen shot 2018-09-06 at 4 54 50 pm" src="https://user-images.githubusercontent.com/1016303/45140285-a0f03200-b1f5-11e8-898d-ea7d66e3d099.png">

These exceptions appear in the JS console:
<img width="547" alt="screen shot 2018-09-06 at 4 51 06 pm" src="https://user-images.githubusercontent.com/1016303/45140245-83bb6380-b1f5-11e8-96d6-6bd5be631af4.png">

### What should be the expected behavior?

I should see my map.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I'm using the default processing settings. This was working fine a week ago.

**Comment by pierotofy** [comment]
Seems like a problem introduced in #514. A workaround for now is to use Google Chrome instead of Safari. We'll have a fix for this by today.

**Comment by pierotofy** [comment]
This should be now fixed.

**Comment by DarylWM** [comment]
Yes that has resolved the issue. I really appreciate the fast fix!
