### ISSUE TITLE
Help users understand TerminatedWorkerError (display low memory warning)

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#524]
Currently a process killed because of low memory will not ask a user to take action (decrease the number of threads), pointing instead at the generic "increase min-num-features" message which confuses people.

Reference: http://community.opendronemap.org/t/min-num-features-veg/1114

**Comment by smathermather** [comment]
I’ve been meaning to open this issue...

**Comment by pierotofy** [comment]
You could be the first to make a PR and close it :)

It would be similar to https://github.com/OpenDroneMap/WebODM/pull/512/files

**Comment by pierotofy** [comment]
This is now fixed

**Comment by smathermather** [comment]
w00t! Thanks.
