### ISSUE TITLE
File uploads don't work when using Brave browser

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#529]
I'm not sure this can be classified as a bug since it looks like Brave's fault?

The reason file uploads don't work on Brave is because `document.cookie` always returns empty string, even though the document clearly has some cookies (which can be seen from Brave's dev tools). We need Django's CSRF token value to do file uploads!

**Comment by pierotofy** [comment]
Doesn't work even on Mozilla's MDN page about document.cookie (try the example N.1 "Simple Usage"): https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by smathermather** [comment]
😂 Fair enough.

**Comment by pierotofy** [comment]
Seems like this has been fixed in Brave.
