### ISSUE TITLE
WebODM Ignoring Images due to Lighting?

### ISSUE THREAD

**Issue by daramolloy** [OpenDroneMap/WebODM#534]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox/Chrome & Windows Pro 64-bit
https://whatismybrowser.com/w/KBN7RRL

### What is the problem?

Not all uploaded images are being used.
I have a dataset of images from F1 - F16, each "F" being a different grid of photos taken, some on different days.
All shots taken on Phantom 3 Standard.
In F6 the photos were taken on an overcast day whereas in F7 it was more of a sunny day so it has more shadows and highlights.
I can generate a model of dataset F1-6 and F7-16 but any model I try to generate using F6 and F7 will only generate up to F6 images or from F7 images onwards.

Map using F4 - F6:
https://imgur.com/a/NqdfB5v

Map using F7 - F9:
https://imgur.com/a/oGUWhYU

Map using F4 - F9 (Only uses F7 - F9) :
https://imgur.com/a/qEKoYwx

Map using F1 - F14 (Only uses F1 - F6):
https://imgur.com/a/1qtpFVh

I have tried increasing/decreasing image size, only using F6 & F7 (Only uses F7 images), increasing min-num-features.

I think a clue to this issue might be the terrain model, below is an image showing F4-6 and F7-9 generated separately but shown on the same terrain model and the two models aren't even remotely the same colour. 
https://imgur.com/a/PxWjUxX

Did the difference in lighting cause ODM not to be able to find points across the two image sets or did the difference in lighting make ODM calculate height differently across the two and hence not be able to merge them?

Both F6 and F7 were taken at 35m.

### What should be the expected behavior?

Generating model using all images.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Any use of F6 and F7 in the same model has caused this issue so it should be easy to replicate.
Link to OneDrive containing F4 - F9 provided, including my LOG when attempting to generate model using F4-F9.
https://nuigalwayie-my.sharepoint.com/:f:/g/personal/d_molloy13_nuigalway_ie/EjR-w111MSpNoWhrvyrlWRYBWUjosY2xrB9SpGDHEzv3eA?e=6mUtDh

**Comment by pierotofy** [comment]
> Did the difference in lighting cause ODM not to be able to find points across the two image sets or did the difference in lighting make ODM calculate height differently across the two and hence not be able to merge them?

Possible. This is more of a question to bring to the community forum I think. Could you open a topic on https://community.opendronemap.org ?
