### ISSUE TITLE
Elevation Model

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#54]
It would be cool to have the ability to display an automatically generated elevation model along with the orthophoto.

@smathermather how would you go about generating an elevation model from the current outputs of opendronemap (lastools come to mind, but they aren't OSS)?

**Comment by dakotabenjamin** [comment]
Probably PDAL would be the way to go, since we've already got that package in ODM

**Comment by pierotofy** [comment]
Oh nice, I did not know PDAL supported that. Found this after more digging: http://www.pdal.io/workshop/exercises/analysis/dtm/dtm.html

**Comment by smathermather** [comment]
I haven't finished documenting:

https://smathermather.com/2016/10/21/filtering-buildings-and-vegetation-from-drone-derived-surface-models/

You can use PDAL to filter with vector data (e.g. building footprints) and also shape-based filtering or both combined.

**Comment by smathermather** [comment]
The trick is getting PDAL installed with all the appropriate dependencies (easy with docker, difficult otherwise).

**Comment by pierotofy** [comment]
@smathermather know what you mean. I built it time ago on Windows!

**Comment by andrespias** [comment]
I want to generate a only-vegetation map, applying some kind of filter on the DSM generated by ODM.
ODM, generates a point cloud as a ply file (pmvs/recon0/models/option-0000.ply) right?
I've been trying to run something like this with no results:
`docker run -v /srv/torreap:/datos pdal/pdal:1.3 pdal ground /datos/odm_data/caliterra/pmvs/recon0/models/option-0000.ply -o /datos/tierra.ply --filters.ground.classify=true`
How can I convert the ODM output format into a allowed format by PDAL?

**Comment by pierotofy** [comment]
@andrespias could you please open a separate issue in the OpenDroneMap repository? This isn't related to WebODM. https://github.com/OpenDroneMap/OpenDroneMap/issues

**Comment by andrespias** [comment]
@pierotofy ok i will do that.

**Comment by smathermather** [comment]
I'm thinking of working on this and full PDAL integration (ODM, not WebODM, but nonetheless relevant) at the code sprint in February.

**Comment by pierotofy** [comment]
This has been completed a while ago.
