### ISSUE TITLE
3D warping issue

### ISSUE THREAD

**Issue by xmutantson** [OpenDroneMap/WebODM#559]
### How did you install WebODM? (Docker, natively, ...)?

Docker w/manager application

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

https://whatismybrowser.com/w/YKMMW7D

### What is the problem?

3D isn't producing good results as I expected. Even with 95% overlap and over 700 photos the orthophoto has distortion and the walls look really strange.

### What should be the expected behavior?

I would expect with 95% overlap and 300 feet up and mapping over a 3 story building that it would be able to render the walls properly.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Here's the dataset. The processing options are in the attached image. I know they're strenuous to process like this but I had time and wanted to give it a fighting chance to be of good quality. I'm not sure if it's the software or the operator. Hopefully if it is me I can be taught.
![image](https://user-images.githubusercontent.com/29498365/48690321-e086b300-eb82-11e8-8748-cf55e4fc3da5.png)
https://drive.google.com/open?id=1j5IEWEFJ3I0kzKpVgnFHfb5ymbt_rfHK

**Comment by smathermather** [comment]
Hi @xmutantson, http://community.opendronemap.org is a better place for these kind of queries.

Before I close this issue (please post on community for more feedback) there are a few things I see. The better choice these days for dense point clouds is to use the defaults with the new dense point cloud approach with SMVS, not OpenSfM's dense point cloud. The other thing that stands out with this dataset is structure from motion is dependent upon feature extraction, and feature extraction requires contrast for the features of interest. The roof in question is extremely bright in all the images I reviewed, so bright that there are no features to match.

![dji_0183](https://user-images.githubusercontent.com/1174901/48744929-58161a00-ec37-11e8-855e-8b78cd597fb7.JPG)

Please do post on community so we can continue this conversation. I will close this for now. And thanks for flying such a cool looking dataset!
