### ISSUE TITLE
WebODM Processing Node error: Connection Aborted, Broken Pipe

### ISSUE THREAD

**Issue by xmutantson** [OpenDroneMap/WebODM#577]
### How did you install WebODM? (Docker, natively, ...)?
WebODM Manager for windows and community script for ubuntu 16.04 LTS 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

https://whatismybrowser.com/w/KQEPWMS

### What is the problem?

When uploading a images to a processing node running on Ubuntu it fails with the following error: "('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))". The machine is remote, over a tunneled conection, but the processing node status page says it is reachable. 

### What should be the expected behavior?

Images should upload with no errors.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Processing parameters are irrelevant becuase it cannot start processing. The dataset has run before with no issues.

**Comment by pierotofy** [comment]
Hi @xmutantson :hand: the tunnel might be at fault here. Is there a timeout on the connections? Large file uploads could last for several minutes, and if the tunnel has a timeout, the connection will abort.

This will be probably go away once we implement https://github.com/OpenDroneMap/NodeODM/issues/60 but for the time being, check your tunnel configuration.

**Comment by xmutantson** [comment]
The timeout takes effect instantly, before data is transferred. I was watching a realtime network map. The specific tunneling software is a logmein hamachi group, and it seems to work ok for ssh and teamspeak.

**Comment by pierotofy** [comment]
This should have been fixed long ago with https://github.com/OpenDroneMap/NodeODM/issues/60 :tada:
