### ISSUE TITLE
GRASS Algorithms Editor

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#583]
We should provide users with a way to run, create, edit and share additional algorithms with the basic products (ortho, dsm, dtm, point cloud) as input. This would solve the outstanding requests for displaying contours, VARI index and make it future proof for any other type of computation supported by GRASS.

**Comment by smathermather** [comment]
Love it. @petrasovaa will like this too.

**Comment by pierotofy** [comment]
Closing in favor of the new dynamic tiling system which includes plant health algorithms and the grass engine included in the plugin system.
