### ISSUE TITLE
Display Elevation / VARI Scale

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#591]
Even though VARI is not implemented, a useful feature to have would be to show a component next to the map that allows for the tweaking of the color scale. This could be applied to elevation as well. Currently the color values are static.

This is probably part of a bigger change, because it requires a dynamic tiler component and possibly further work.

**Comment by merkato** [comment]
Bigger change is coming ;) #241

**Comment by pierotofy** [comment]
This is now implemented! #746 :clinking_glasses:
