### ISSUE TITLE
Display Quality Report

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#594]
It should include area, georeferencing accuracy, flight time, see #282.

**Comment by smathermather** [comment]
Related:
https://github.com/OpenDroneMap/ODM/issues/911
https://github.com/OpenDroneMap/ODM/issues/883
https://github.com/OpenDroneMap/ODM/issues/179

**Comment by NicholasK7** [comment]
I have evaluated accuracy/quality metrics across several platforms (ArcGIS Pro, PIX4D, DroneDeploy, MapsMadeEasy, PrecisionAnalytics) See examples [here](https://drive.google.com/drive/folders/1gY2SJllNF5tLHBY9X0l5JDD9e-qs09g4?usp=sharing)

Only common metric across all is gsd. PIX4D is the most comprehensive and they have extensive [help documentation](https://support.pix4d.com/hc/en-us/articles/202558689-Quality-Report-Help) on their quality report.

I'm rather new to odm, so wondering if there has been some preliminary workflow developed on this...and how I might contribute.

**Comment by ChipwizBen** [comment]
Is there any update on this, or anything that I can do to assist (UI perhaps)? I've found that people doing volumetric surveys are discounting ODM produced results because their customers need an error margin defining, and details on how that margin was calculated.

**Comment by pierotofy** [comment]
I don't think anyone has started working on it (but we would welcome help).

The first step would be to add support for this in ODM (see the issues linked by smathermather). Python and C++ skills are needed for that (UI not so much unfortunately).

**Comment by pierotofy** [comment]
This is done! :clinking_glasses:
