### ISSUE TITLE
[Feature] Ability to upload previous processed data  

### ISSUE THREAD

**Issue by sann1432** [OpenDroneMap/WebODM#609]
it would be good if we could upload previously processed data from other WebODM instances.

this would mean that data could be stored locally and only uploaded when customers/users needed to see that data.

Saving space on cloud servers 

Thoughts?

**Comment by nixxet** [comment]
I would be nice to be able to duplicate tasks without having to upload images again to be able to test other processing methods and compare which would be most effective and have the best output.

**Comment by pierotofy** [comment]
Thanks @nixxet, that would be an interesting feature. Could you open a new feature request since it's separate from this one?

**Comment by nixxet** [comment]
will do!

**Comment by epurnell** [comment]
+1 this a desperately needed. When running on a server the resources consumed by repeatedly uploading the images is huge. There is not an easy way of managing them once loaded either. If this could be in the March sprint that would be a huge bonus.

**Comment by pierotofy** [comment]
Hey @epurnell :hand:, that's an interesting idea. It should probably get its own feature request. Perhaps you could open one?

I will close this one as this has been implemented.

![image](https://user-images.githubusercontent.com/1951843/53208058-7c511080-3603-11e9-915a-f53e757a28b2.png)

**Comment by epurnell** [comment]
New request raised #630 thanks Piero 👍🏻
