### ISSUE TITLE
Merge devenv.sh with webodm.sh and allow --media to be used during development

### ISSUE THREAD

**Issue by NicksonYap** [OpenDroneMap/WebODM#616]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 72 on Linux
Ubuntu 16.04
https://whatismybrowser.com/w/L9HHM9Q

### What is the problem?

Cloned latest repo at 3d3c6164f618c5ee452013f593b8ee9e278b59af

After running successfully: ./devenv.sh start

Error in webpage:

![image](https://user-images.githubusercontent.com/5380731/52376627-87e9f680-2a9d-11e9-9364-a3b5cf9e6b62.png)

Console output/steps:
[consoleoutput.txt](https://github.com/OpenDroneMap/WebODM/files/2838451/consoleoutput.txt)

### What should be the expected behavior?

Should be a normal login page

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Just clone new repo, run:

```
./webodm.sh start (works normally)
./webodm.sh stop 
 ./devenv.sh start
```

Produces the  error shown in screenshot above

The following is my SSD partitioning
![image](https://user-images.githubusercontent.com/5380731/52376943-676e6c00-2a9e-11e9-8e04-a803bd17a3ab.png)

I had issue when using exFAT (unable to create symlink)

**Comment by NicksonYap** [comment]
I found the way to fix

I was aware this issue is related with the fact that  `envdev.sh` does not work well with `webdom.sh start --media_dir XXXXX`

So when resetting docker I have deleted containers and images, but forgot to delete volumes.

```
docker volume rm webodm_appmedia 
docker volume rm webodm_dbdata
```

So the actual issue is that `envdev.sh` should work with` --media_dir XXXXX `or that
the development should be able to be activated with `webdom.sh start --media_dir XXXXX --dev`

**Comment by pierotofy** [comment]
Hey @NicksonYap :hand: thanks for sharing your findings! Admittedly the `devenv.sh` script could probably be merged with `webodm.sh` via a `--dev` flag. I will leave this issue open and leave it as a an improvement.

**Comment by pierotofy** [comment]
This is now done (in `febspring` branch).
