### ISSUE TITLE
[Feature Request] Reuse images to create new task within same project

### ISSUE THREAD

**Issue by nixxet** [OpenDroneMap/WebODM#628]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

varies, ubuntu

### What is the problem?

It would be nice to be able to duplicate tasks without having to upload images again to be able to test other processing methods and compare which would be most effective and have the best output.

### What should be the expected behavior?

Create new task, recycling the same uploaded images for project.

**Comment by pierotofy** [comment]
Closing in favor of #522 (duplicate). This is a good feature that we should implement as it keeps being asked for. :+1:
