### ISSUE TITLE
Server Installer script should check for files, not a directory

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/WebODM#641]
### How did you install WebODM? (Docker, natively, ...)?

Natively, Server Installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

The existing installation check design is to search for /www, /code and /webodm. However, when these are required to be externally mounted (such as via NFS or Cephfs) these directories exist _before_ the installation occurs. Due to the fact that these directories are also at the root level, it makes it difficult to work around this problem without having to either edit the installer script or move the directories after the installation.

### What should be the expected behaviour?

Instead of checking that the directories exist, it would be better to check for the existence of a file (or even the .git directory).

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

mkdir /webodm
./webodm_install.sh

**Comment by pierotofy** [comment]
Note taken! :+1:
