### ISSUE TITLE
Elevation\SurfaceModel Not an option

### ISSUE THREAD

**Issue by DykstraJosh** [OpenDroneMap/WebODM#646]
### How did you install WebODM? (Docker, natively, ...)?

Followed the Directions from Github page(Docker)

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 73 on Windows 10

### What is the problem?

When view the map of the processed image, the surface model\elevation button aren't options. 

### What should be the expected behavior?

Looking for the elevation map

**Comment by pierotofy** [comment]
Make sure your task has either the `--dsm` or `--dtm` option checked (or choose the DSM+DTM preset). The `Default` preset should also give you a DSM.

**Comment by DykstraJosh** [comment]
Thanks!
