### ISSUE TITLE
Make volume measurements async

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#649]
Currently the calculation needs to return within the browser timeout limits, instead of pooling for status updates (like the contours plugin does).

**Comment by ChipwizBen** [comment]
Are these able to be multithreaded also?

**Comment by pierotofy** [comment]
Maybe, but not easily. GRASS GIS functions are mostly single threaded (I think that includes the ones we use for volume measurements). One would have to split the polygon area by the number of threads available and run the sum of volumes independently and add up the results.

But we would welcome contributions!

**Comment by pierotofy** [comment]
This is fixed.
