### ISSUE TITLE
latest: Pulling from opendronemap/webodm_webapp

### ISSUE THREAD

**Issue by patrickharvey333** [OpenDroneMap/WebODM#650]
### How did you install WebODM? (Docker, natively, ...)?

Docker. 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Microsoft Edge 44 and Windows 10 pro 64 bit

### What is the problem?

Process hangs on latest: Pulling from opendronemap/webodm_webapp
It then says: Gracefully stopping... (press Ctrl+C again to force)

The image attached shows the whole process stream. 

![Hanging on process then exiting](https://user-images.githubusercontent.com/39748353/56009710-1855e900-5d24-11e9-9c0b-155775c3a7cb.png)

### What should be the expected behavior?

unsure. It should complete the pull process and allow me to open webodm 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I am not sure. I have tried using the WebODM manager too and it gives the same issue.

**Comment by pierotofy** [comment]
Hey @patrickharvey333 :hand: sorry for the late reply; this is probably a connection issue (a network configuration problem) with the machine and docker. It's probably not WebODM's fault per-se. If that's OK with you I'll close this issue as it's not a WebODM bug.

**Comment by patrickharvey333** [comment]
Not a proble

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
