### ISSUE TITLE
Segmentation fault with bad parameter/dataset combo

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/WebODM#665]
### How did you install WebODM? (Docker, natively, ...)?

Natively 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

When processing this dataset:
https://drive.google.com/open?id=1g9IQ_caq9sVVeE6N0MuievcDWzqii27x
From this post:
https://community.opendronemap.org/t/drone-recorded-incorrect-elevation-value-in-the-exif-data-having-difficulty-building-3d-model/2188

With the following options:
Options: fast-orthophoto: false, use-hybrid-bundle-adjustment: false, use-fixed-camera-params: true, resize-to: -1, dsm: false, dtm: false, crop: 10, use-3dmesh: true, dem-resolution: 2, orthophoto-resolution: 2, depthmap-resolution: 2000, opensfm-depthmap-min-patch-sd: 1, min-num-features: 18000, matcher-neighbors: 0, texturing-data-term: area, use-opensfm-dense: true, mesh-size: 600000, mesh-octree-depth: 11, texturing-nadir-weight: 16

OR

Options: fast-orthophoto: false, use-hybrid-bundle-adjustment: false, use-fixed-camera-params: true, resize-to: -1, dsm: false, dtm: false, crop: 10, use-3dmesh: true, dem-resolution: 2, orthophoto-resolution: 2, depthmap-resolution: 2000, opensfm-depthmap-min-patch-sd: 1, min-num-features: 25000, matcher-neighbors: 0, texturing-data-term: gmi, use-opensfm-dense: true, mesh-size: 800000, mesh-octree-depth: 12, texturing-nadir-weight: 16

A seg fault is produced. Webodm still believes that the process is still running, presumably because it didn't see "error" or "exit":

```
Generating texture patches: Running... done. (Took 12.647s) 133740 texture patches. Running global seam leveling: Create matrices for optimization... done. Lhs dimensionality: 831428 x 831428 Calculating adjustments: Color channel 2: CG took 171 iterations. Residual is 9.89748e-05 Color channel 0: CG took 172 iterations. Residual is 9.99061e-05 Color channel 1: CG took 176 iterations. Residual is 9.91488e-05 Took 4.508 seconds Adjusting texture patches 100%... done. (Took 2.16s) Running local seam leveling: Received signal SIGSEGV (segmentation fault) 
```

### What should be the expected behavior?

No seg fault, or WebODM should gracefully handle seg faults as errors. 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Try the dataset with one of the above option sets.

**Comment by pierotofy** [comment]
Hey @ChipwizBen :hand: it's been a while since this was reported. We've made lots of improvements to ODM since. See if the dataset still gives you troubles and feel free to re-open this if it does. I'm going to close it in the meanwhile. :pray:
