### ISSUE TITLE
Image groups are not supported in WebODM

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#675]
There's currently no way to use image groups in split merge via WebODM.

**Comment by pierotofy** [comment]
Hi @pierotofy,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-06-16 13:25) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by smathermather** [comment]
Hmm, good point.

**Comment by astrogazer63** [comment]
Has this changed or been updated with more recent versions???

**Comment by smathermather** [comment]
It has not yet been addressed in more recent versions.

**Comment by pierotofy** [comment]
This is being addressed in https://github.com/OpenDroneMap/NodeODM/pull/143 :clinking_glasses:

**Comment by pierotofy** [comment]
Done!
