### ISSUE TITLE
Native install script fails silently, reports success

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/WebODM#679]
### How did you install WebODM? (Docker, natively, ...)?

Native

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

The install script does not handle errors well from sub tasks, which leads people to believe that the install/update was successful when one or more lines failed.

### What should be the expected behavior?

Check for command success ($? == 0).

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Update native install.

**Comment by ChipwizBen** [comment]
Traced this to /webodm:

```
Updating 0d485fc..abc555c
error: Your local changes to the following files would be overwritten by merge:
	package.json
Please, commit your changes or stash them before you can merge.
```

I haven't modified that file so it must have been WebODM. The updater doesn't halt on $? != 0 errors (it reports a successful update at the end). I fixed it with a `git reset --hard`, but I guess the better fix would be to update the script to halt on errors otherwise they become silent in the noise of the 10,000+ lines of output from the update script.

**Comment by pierotofy** [comment]
Thanks @ChipwizBen for the report.

**Comment by pierotofy** [comment]
Took note of this a while ago, so this can be closed.
