### ISSUE TITLE
Download to File console log sometimes does not work

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#686]
Seems to affect some Chrome users in certain cases. No reproducible test case available as of yet.

**Comment by pierotofy** [comment]
Hi @pierotofy,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2019-06-22 21:55) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by danbjoseph** [comment]
<img width="375" alt="Screen Shot 2019-06-20 at 9 54 37 PM" src="https://user-images.githubusercontent.com/4806884/59892016-70087480-93a5-11e9-81a9-09de8005bf1a.png">
<img width="995" alt="Screen Shot 2019-06-20 at 9 55 09 PM" src="https://user-images.githubusercontent.com/4806884/59892018-70a10b00-93a5-11e9-860a-41512fbfb588.png">
<img width="886" alt="Screen Shot 2019-06-20 at 9 55 36 PM" src="https://user-images.githubusercontent.com/4806884/59892019-726ace80-93a5-11e9-8e3d-5ada8867988a.png">

is there other info i can provide?

**Comment by pierotofy** [comment]
Yes please, length of the task log (in number of lines, you can see the full task log from the "Administration" -- "Application" menu by navigating under "Tasks") and operating system could help reproduce this.

Thanks!!

**Comment by danbjoseph** [comment]
<img width="287" alt="Screen Shot 2019-06-20 at 10 05 01 PM" src="https://user-images.githubusercontent.com/4806884/59892371-c0cc9d00-93a6-11e9-8868-ca15659e2368.png">
(WebODM is running on an Intel NUC via POSM)

-----------

[Lipata_1.txt](https://github.com/OpenDroneMap/WebODM/files/3312721/Lipata_1.txt) is the text log saved using Firefox

**Comment by pierotofy** [comment]
This is fixed in #688. Thanks for reporting!

**Comment by danbjoseph** [comment]
Thanks for fixing it!
