### ISSUE TITLE
live reload doesn't initiate in --dev

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/WebODM#695]
### How did you install WebODM? (Docker, natively, ...)?

I made a clone of the repository and ran `./webodm.sh start --dev`.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

macOS High Sierra 10.13.6 (17G7024)
Docker Desktop Community 2.0.0.3 (31259)

### What is the problem?

`Live Reload listening on port 35729` is logged
and then shortly after, a series of `Live Reload disabled: listen EADDRINUSE :::35729`

`lsof -nP -i4TCP:35729 | grep LISTEN` doesn’t output anything

@pierotofy [is aware of the issue](https://community.opendronemap.org/t/live-reload-not-working-in-dev-mode/2502/2) and thinks it might be solved by editing the docker-compose.dev.yml file. 

perhaps by setting [expose](https://docs.docker.com/compose/compose-file/compose-file-v2/#expose) or [ports](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports)?

### What should be the expected behavior?

The [documentation](https://docs.webodm.org/#development-quickstart) says "You can modify any of the files, including SASS and React.js files. Changes will be reflected in the running WebODM instance automatically."

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Run WebODM in development mode.

**Comment by pierotofy** [comment]
Fixed in #723 (to the extent possible, see PR for details).

Thanks for reporting it!
