### ISSUE TITLE
Cluster Management

### ISSUE THREAD

**Issue by mojodna** [OpenDroneMap/WebODM#7]
[What does Cluster Management mean in the context of WebODM?]

From #1:

By "cluster management" (there's probably a better term for this) I mean the management of distributing image processing tasks across multiple server instances.

This image might clarify a bit:

<img src="https://cloud.githubusercontent.com/assets/1951843/17680196/9bfe878e-6304-11e6-852e-c09f1e02f3c0.png">

The Web Manager is WebODM.

The REST API is https://github.com/pierotofy/node-OpenDroneMap, http://nodeodm.masseranolabs.com/

**Comment by mojodna** [comment]
@pierotofy the audience for this piece is system administrators?

**Comment by pierotofy** [comment]
Yes (only users with admin permissions will get to manage the clusters).

**Comment by pierotofy** [comment]
New name for "cluster". `ProcessingNode`. Seems more intuitive.

**Comment by pierotofy** [comment]
This can be closed, there's nothing to add here.
