### ISSUE TITLE
Make permissions management easier

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#722]
Currently the only way to manage permissions is to use Django's complicated admin UI. This should be improved.

**Comment by anwaysomani** [comment]
Hey...are you expecting a Django (HTML) template UI-based permission management system, or do you want the admin layout to be refurbished for UI...?

**Comment by pierotofy** [comment]
Hey @anwaysomani :hand: ideally we'd love to have the React components in the dashboard to include a UI for handling permissions (without using the Django admin pages).

![image](https://user-images.githubusercontent.com/1951843/65832248-1dd1cc00-e28f-11e9-851e-3a2ce326989f.png)

Not a quick task for sure. But we're also open to other suggestions (that perhaps require less effort)!

**Comment by pierotofy** [comment]
Perhaps something as simple as a button to link the Dashboard UI to the Django admin permission page might work (or open the Django admin permission page in a popup). :+1:

**Comment by anwaysomani** [comment]
Well, @pierotofy , I shall like to give it a try with React & Django. Will get back to you with an update.

**Comment by pierotofy** [comment]
This has been implemented.
