### ISSUE TITLE
WebODM processing error, child returned 1

### ISSUE THREAD

**Issue by a0364** [OpenDroneMap/WebODM#726]
### How did you install WebODM? (Docker, natively, ...)?

Docker Desktop 2.1.0.2

### What's your browser and operating system? 
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Windows 10 Pro

### What is the problem?

When I upload and try to process imagery (taken with a DJI drone), WebODM fails with "Exception: Child returned 1". 

Looking further up in my logfile, I also get this error:
"Error in Georef:
Error while loading point cloud: writers.las: Unable to convert scaled value (1.14198704e+10) to int32 for dimension 'Z' when writing LAS/LAZ file"

Camera settings (using DJ GS PRO app):
- Camera model: Mavic 2 Zoom Camera 24mm
- Shooting angle: Parallel to main Path
- Capture mode: Hover & capture at point
- Flight Course Mode: Inside mode
- Front overlap ratio: 75%
- Side overlap ratio: 60%
- Course angle: 0 degrees
- Margin: 0.0 FT

### What should be the expected behavior?

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I'm using default settings in WebODM (dsm:true). Attached logfile and link to Dropfox with imagery. I've tried with both the whole dataset and just a few of the images but I get the same error in both cases.

[console.txt](https://github.com/OpenDroneMap/WebODM/files/3600601/console.txt)
[Dropbox](https://www.dropbox.com/sh/klffm24chcf3vfm/AACfSAYxJDtzhpPLxYK3ur4la?dl=0)

Help would be greatly appreciated, thank you for an awesome project!

**Comment by smathermather** [comment]
Hi @a0364, this would be a better thing to post at https://community.opendronemap.org. If it turns out to be a bug, we can re-open this issue. Thanks!
