### ISSUE TITLE
Missing Images in the Ortomosaic

### ISSUE THREAD

**Issue by alenc09** [OpenDroneMap/WebODM#731]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 69 on Windows 10

### What is the problem?

Some images in the final ortomosaic are missing. It seams to complet the task perfectly fine, but when i view it at the map (View Map option in WebODM), some images at the corner of the ortomosaic are missing (missing parts are at the red circles in the picture below).  I'm sure that i uploaded all necessary images. I made it using the default option.

### What should be the expected behavior?

A complete ortomosaic with all uploaded images

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Images used are at this link: https://1drv.ms/u/s!AmqVkOdbs1Sqhe904cDLiHvLRip3sA?e=HVsaJv
Just try to create the ortomosaic

![orotomosaic_default_missing](https://user-images.githubusercontent.com/55501872/65166960-0a656c00-da18-11e9-8394-853c4c4a2c64.jpg)

**Comment by pierotofy** [comment]
There might be some settings that can be tweaked to improve the reconstruction. It's probably not a bug in WebODM, but rather a difficult dataset to stitch at the edges.

The forum would be the right place to ask suggestions about what parameters to tweak: https://community.opendronemap.org :+1:
