### ISSUE TITLE
Volume calculation returns Invalid response: [object Object]

### ISSUE THREAD

**Issue by uresplatform** [OpenDroneMap/WebODM#732]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 76 on Windows 10

### What is the problem?

I am unable to obtain volume measurement, I keep getting the following error: Invalid response: [object Object]

No error appeared on the console, and I could not find any log files.

In the web console, the returned object is: {"error":""}

![Capture](https://user-images.githubusercontent.com/2326557/65308228-e5910600-db89-11e9-90f3-4610694e9add.PNG)

### What should be the expected behavior?

One of the two:
- volume of the selected area
- clear error message

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I have tried processing the images with both profiles: Volume measurement, High Resolution. I then selected the area for which I would like to calculate the volume.

![Capture_1](https://user-images.githubusercontent.com/2326557/65308342-29840b00-db8a-11e9-9204-030b3d78e285.PNG)

**Comment by pierotofy** [comment]
Hey @uresplatform :hand: thanks for reporting this! Does this happen with every dataset or just on some? Does selecting another area (perhaps a smaller polygon) work or do you get the same error?

**Comment by pierotofy** [comment]
Should be fixed as soon as #735 is rebuilt and pushed to docker (in a few hours). :+1:

**Comment by uresplatform** [comment]
Hello @pierotofy ! Thanks for looking into this. Just updated to the latest version and works perfectly!
