### ISSUE TITLE
Processing quits when no GPS in exif

### ISSUE THREAD

**Issue by BKLronin** [OpenDroneMap/WebODM#74]
I tried to stich a sample dataset with no GPS coordinates in the exif. I have seen the appropiate entry in the JSON file configuring the node but I can´t edit it or find it within the folders. 

[DEBUG]   running /code/build/bin/odm_extract_utm -imagesPath /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/images_resize/ -imageListFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/opensfm/list_r000.out -outputCoordFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/odm_georeferencing/coords.txt -logFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/odm_georeferencing/odm_georeferencing_utm_log.txt
Error in OdmExtractUtm:
No valid GPS position found
For more detailed information, see log file.
[ERROR]   quitting cause: 
	/code/build/bin/odm_extract_utm -imagesPath /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/images_resize/ -imageListFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/opensfm/list_r000.out -outputCoordFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/odm_georeferencing/coords.txt -logFile /var/www/data/a9f0cfb9-ee28-40ae-a256-d1f9936bf71e/odm_georeferencing/odm_georeferencing_utm_log.txt
returned with code 256.

An error occurred. Check stdout above or the logs.

**Comment by dakotabenjamin** [comment]
There is currently a fix on the way at https://github.com/OpenDroneMap/OpenDroneMap/pull/440

**Comment by BKLronin** [comment]
Excellent, can be helpful when capturing buildings from the ground with no GPS attached.

**Comment by pierotofy** [comment]
Closing this since a fix will be available.
