### ISSUE TITLE
Where does WebODM do it's file processing? Locally or on a cloud?

### ISSUE THREAD

**Issue by TheMrRandomDude** [OpenDroneMap/WebODM#740]
### How did you install WebODM? (Docker, natively, ...)?

 Docker, on Windows.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome, Windows 10.

### What is the problem?

I can't figure out where it processes maps and why my CPU usage isn't spiking up massively. It's also quite slow, takes a while to process data. Is it doing it on some kind of cloud?

If it is, can I do it strictly locally? I have quite a powerful machine, so I think it'll be faster than a cloud solution.

Also, it possible to share your processing power with other users? Can I open WebODM to internet? I'd like to share my computer with other ODM users, because I don't use it 24/7, while it's powered on 24/7, so sometimes it just sits and does nothing.

### What should be the expected behavior?

//

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

//

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
