### ISSUE TITLE
Volume Calculating volumes using Volume leangth area

### ISSUE THREAD

**Issue by MontanaVDS** [OpenDroneMap/WebODM#752]
****************************************

### How did you install WebODM? (Docker, natively, ...)?

[Type answer here]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

YOUR WEB BROWSER IS:
Chrome 78 on Windows 10

✓ Your web browser is up to date.
Is JavaScript enabled? | YesHow to enable JavaScript
-- | --
YesHow to enable Cookies
YesHow to enable third-party cookies

### What is the problem?

After update Volume calculation are not calculated Distance and area are computed but volume are not being calculated.
Yesterday 11-18-19 Volumes calculated after update to webodm from WEBODM Manager 1.6 no more volumes tried on different projects all the same

### What should be the expected behavior?

Yesterday 11-18-19 Volumes calculated after update to webodm from WEBODM Manager 1.6 no more volumes tried on different projects all the same

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Not Shure
Also my Windows Docker auto updated on 11-18-19 also

**Comment by dmbworld** [comment]
Same issue here since update. All existing and previously working projects no longer display volumes. Only Perimeter and Area reported.

**Comment by pierotofy** [comment]
Are you getting any error messages? Could you post a screenshot of what you are seeing?

Thank you.

**Comment by dmbworld** [comment]
No error messages, attached a screen dump.
![Annotation 2019-11-20 220736](https://user-images.githubusercontent.com/58004227/69274124-64cea480-0be2-11ea-96e8-94fd2c21a47d.png)

**Comment by MontanaVDS** [comment]
No Errors Messages.  I Get the same as above Screen Shot

**Comment by pierotofy** [comment]
Thank you! I will look into it.

**Comment by pierotofy** [comment]
Try to update in a few hours, then see if it's fixed (it should).

If not, please let me know.

Thank you for the report!

**Comment by dmbworld** [comment]
Thank you @pierotofy volume measurment now working.

**Comment by MontanaVDS** [comment]
Working again!!
Thanks  @pierotofy
