### ISSUE TITLE
MicMac working directory problem.

### ISSUE THREAD

**Issue by maciekish** [OpenDroneMap/WebODM#755]
### What's your browser and operating system?
Ubuntu x64 VM with limited disk space and mapped folders from host.

### What is the problem?
MicMac node is running out of disk space.

How do i change where MicMac stores temporary data? --media-dir doesn't help.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by maciekish** [comment]
Conversation? This is a bug/feature request imho.

**Comment by smathermather** [comment]
It's almost always better to start the conversation at community and then escalate on github. It helps get the bug report / feature requests in the correct places, and reduces the noise.
