### ISSUE TITLE
Docker : containers not restarting after host reboot

### ISSUE THREAD

**Issue by olivierdalang** [OpenDroneMap/WebODM#758]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Ubuntu 16.04

### What is the problem?

Containers do not restart after reboot (actually, here, webapp and worker do restart (unsure why?)  but not the others).

### What should be the expected behavior?

Containers should restart after reboot, so that the stack survives a host reboot without manual intervention. This should be an easy fix (just change `restart-policy` to `unless-stopped`

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Run the stack with `./webodm.sh start -d`. See that it works. Reboot the host. See that it doesn't work.

**Comment by pierotofy** [comment]
Hey @olivierdalang :hand: thanks for the report!

Would you be interested in making a pull request for this, since it should be an easy fix?
