### ISSUE TITLE
Volume Calculation is too large and Ortho image pixelated

### ISSUE THREAD

**Issue by dmbworld** [OpenDroneMap/WebODM#766]
### What's your browser and operating system?
Firefox 71 on Windows 10
WebODM server running on Ubuntu 19.04
whatismybrowser.com/w/DMLG6JE

### What is the problem?
Volume calculation in current version is inaccurate and on average four to five times greater than in older version of WebODM which is actually the correct calculation. Additionally in the newer vesion of WebODM Ortho view the image is pixelated and scaled down.

### What should be the expected behavior?
Correct volume expected and not so pixelated image

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Older WebODM Image with volume calculation:
![Older_WebODM](https://user-images.githubusercontent.com/58004227/70513038-8368f100-1b39-11ea-98a3-5322d41fc88a.png)

Newer WebODM Image with volume calculation:
![Newer_WebODM](https://user-images.githubusercontent.com/58004227/70513080-97acee00-1b39-11ea-99c9-550a817b25a1.png)

As can be seen in the newer version the image is pixelated, smaller in file size and shows an inflated volume of ariund four times the actual size in the older version.

**Comment by pierotofy** [comment]
Thanks for the report @dmbworld 

I think this is a bug due to the fact that the DSM/DTM is now in web mercator projection (EPSG:3857), before we used UTM, and GRASS is now calculating values in that projection, which is expected to be off by:

```(1 / cos (latitude)) ^ 2`

For your area I think that's a factor of `5.20`, which explains the different results.

Still not sure about the lower resolution, but can confirm that results in the web viewer look more pixelated compared to opening them in QGIS.

**Comment by dmbworld** [comment]
Just seen the merge and downloaded what appeared to be an update, calculation is still exhibiting the similar multiple too great.

**Comment by pierotofy** [comment]
Docker images haven't been updated yet; try again in a few hours https://hub.docker.com/repository/docker/opendronemap/webodm_webapp

**Comment by dmbworld** [comment]
Ok, thanks @pierotofy

**Comment by dmbworld** [comment]
Yep, it has now updated correctly, sorry about preempting the update. Volumes now look as they should.
The extra pixelation in the view is a little unusual and the TIFF files are smaller in this task after the update run on the existing TIF files. Could this simply be due to a fault in the viewer as you suggested? The older version did not allow such a large zoom as this version does, could that indicate something?

**Comment by dmbworld** [comment]
Is it better to move this pixelation feature/reduced image quality to a new issue as I have some more information that may help?

**Comment by pierotofy** [comment]
It's OK to leave the pixelation feature here, I've opened a PR that should address this. The problem was both related to the choice of sampling algorithm for tiling and allowed zoom levels in leaflet. :+1:

**Comment by dmbworld** [comment]
Thanks @pierotofy!
