### ISSUE TITLE
Surface Model colour key reversed and tile lines maybe be more visible

### ISSUE THREAD

**Issue by dmbworld** [OpenDroneMap/WebODM#770]
### What's your browser and operating system? (Copy/paste the output of 
Firefrox 71 on Windows 10
WebODM running on Ubuntu 19.04
whatismybrowser.com/w/HLFQAT9

### What is the problem?
The surface model displays the colour key in reverse order compared to earlier version of WebODM

### What should be the expected behavior?
High levels -> RED
Low Levels -> BLUE

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Original Colour Key:
![Surface_Model_Old](https://user-images.githubusercontent.com/58004227/70574286-72a59300-1bac-11ea-956d-0703d8441cc3.png)

New Colour Key:
![Surface_Model_New](https://user-images.githubusercontent.com/58004227/70574299-7cc79180-1bac-11ea-807e-f21b40405827.png)

**Comment by dmbworld** [comment]
There are clearly more options available with the coloring and now I'm not sure if this is an issue or operating as intended?

**Comment by pierotofy** [comment]
Ah, good catch! Yes we can color elevation models however we want using any of the palettes from matplotlib https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html

I've reversed the colors in #769

**Comment by pierotofy** [comment]
Tile lines should also improve with #769
