### ISSUE TITLE
How can I verify that PostgreSQL is indeed working within docker containers?

### ISSUE THREAD

**Issue by TheMrRandomDude** [OpenDroneMap/WebODM#786]
### What's your browser and operating system? 

The server is running in Debian, it was installed using Docker-compose and following the documentation.

### What is the problem? 

I'm not sure the PostgreSQL is working as intended and not sure how to test it. When first installing, it kept on saying that PSQL is sleeping and when I manually tested the command it failed to be recognized, then after restarting the WebODM container it all supposedly works as intended. But I'm stlil not convinced.

### What should be the expected behavior? 

Not sure either.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I think you can't reproduce this, it's unique and based on how my machine is configured.

The goal is just verifying that the PSQL is indeed working and that the database is working as well. How would I go doing that? I see WebODM installed five containers:

- broker,
- db,
- webapp,
- webodm_node
- worker

I can open all of them nicely in bash through exec, just not sure what to run to verify that PSQL is fine.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
