### ISSUE TITLE
DEM display

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#79]
Once OpenDroneMap is ready to generate DEM assets, they should be displayed in the 2D map display.

**Comment by pierotofy** [comment]
@smathermather how's the PDAL integration going? Any estimate on when DEMs will land in ODM?

**Comment by smathermather** [comment]
Expect it with v0.3. Dakota is going to build it in the next 3 weeks or so based on my experiments at the code sprint.

**Comment by pierotofy** [comment]
This has been done a while ago.
