### ISSUE TITLE
ERROR: Validation failed, reason(s): webapp.depends_on value ['db', 'db', 'node-odm-1'] has non-unique elements

### ISSUE THREAD

**Issue by McStrav** [OpenDroneMap/WebODM#83]
Hi,

Had no problems with previous build running in azure, i.e. prior to Potree implementation.  

I thought I would give this latest build a try, running in a new VM on Azure.

I'm getting a validation error when running 

`./webodm.sh start`

output as follows:

> Checking for docker...   OK
> Checking for git...   OK
> Checking for python...   OK
> Checking for pip...   OK
> Checking for docker-compose...   OK
> Starting WebODM...
> docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up
> ERROR: Validation failed, reason(s):
> webapp.depends_on value ['db', 'db', 'node-odm-1'] has non-unique elements

There are currently no docker images running or installed:

```
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

```

Any ideas?

Thanks,

Eamonn

**Comment by pierotofy** [comment]
Hi @McStrav, thanks for reporting the problem! I have made some changes to the docker-compose.nodeodm.yml file just now, could you please try to run:

```
git pull origin master
./webodm.sh start
```

And see if the problem is fixed?

Thanks!

**Comment by McStrav** [comment]
Hi @pierotofy that seems to have fixed it... 

I killed and removed all docker containers and images, then re-ran:

```
git clone https://github.com/OpenDroneMap/WebODM
cd WebODM
./webodm.sh start
```

It's now all up and running.

Thanks...
