### ISSUE TITLE
Volume Measurement reports "Invalid task output"

### ISSUE THREAD

**Issue by dmbworld** [OpenDroneMap/WebODM#833]
### What's your browser and operating system?
whatismybrowser.com/w/ADN7Z5H

### What is the problem?

Volume measurement reports  "Invalid task output (cannot find valid key)"

### What should be the expected behavior?

Should report volume of area defined
![Annotation 2020-03-13 234528](https://user-images.githubusercontent.com/58004227/76662131-d19cee80-6585-11ea-818a-645fb30ac513.png)

### How can we reproduce this? 
Attempt a volume measurement

**Comment by pierotofy** [comment]
Confirm, introduced by mistake in #829

**Comment by pierotofy** [comment]
Wait until docker images are rebuilt (~1 hour), update and test if it's fixed?

Thanks for the report @dmbworld ! :pray:
