### ISSUE TITLE
Unable to use behind front end NGINX reverse proxy

### ISSUE THREAD

**Issue by kmickeletto** [OpenDroneMap/WebODM#850]
### What's your browser and operating system?
https://whatismybrowser.com/w/H9TRTCT

### What is the problem?
Running on a CentOS 7 host using Docker 19.03.6.  However, I have configured the containers to use a predefined bridge network so that I may run it behind a pre-existing NGINX reverse proxy.  When I attempt to access the site, it returns the following.

> Forbidden (403)
CSRF verification failed. Request aborted.<

### What should be the expected behavior?
It should work

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Basically my docker containers are unmodified accept for the fact that I have them on a bridge network.  I am still have the webapp using it's own NGINX internally and I am attempting to reverse-proxy from my front-end NGINX for web presence and SSL front-end.

My front-end NGINX server is configured as follows.
#### nginx.conf
```
user abc;
worker_processes 4;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        client_max_body_size 0;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /config/log/nginx/access.log;
        error_log /config/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

        include /etc/nginx/conf.d/*.conf;
        include /config/nginx/site-confs/*;

}
daemon off;
```
#### proxy.conf
```
#client_max_body_size 10m;
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 3000;
proxy_send_timeout 3000;
proxy_connect_timeout 3000;

# Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
```
#### dronemap.conf
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name dronemap.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_host webapp;
        set $upstream_port 8000;
        proxy_pass http://$upstream_host:$upstream_port;
    }
}
```

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
