### ISSUE TITLE
View 3D Model fails to load since #863 merged to master.

### ISSUE THREAD

**Issue by dmbworld** [OpenDroneMap/WebODM#865]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

whatismybrowser.com/w/L6EMD38

### What is the problem?

After updating WebODM to version with #863 "View 3D Model" fails to load mesh and no error messages displayed.

### What should be the expected behavior?

Mesh view should be displayed

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Updated after #863 was merged in to Master. ALL existing tasks fail to load 3D Mesh.

![3D-task-to-be-loaded](https://user-images.githubusercontent.com/58004227/82633876-06bc6180-9c05-11ea-8110-b29fd897754e.png)

After selecting "View 3D Model:
![3D-task-to-be-loaded-fails](https://user-images.githubusercontent.com/58004227/82633934-281d4d80-9c05-11ea-9e90-24b0b46481bf.png)

View Map (2D) does work:
![2D-Map-Loads](https://user-images.githubusercontent.com/58004227/82633956-38352d00-9c05-11ea-9bdf-dc0d27f62c6f.png)

Waited for over 3 hours before updating to ensure that Docker had been uptated.
In an effort to resolve probelm used the rebuild option of "webodm.sh" and problem still exists.

**Comment by timotay07** [comment]
I can confirm that this is an issue that we are experiencing using both Firefox and Chrome.  We ran the update script yesterday evening and this morning.

**Comment by pierotofy** [comment]
Thanks for the report! This was a bug indeed. Should be fixed (docker images will get rebuilt soon).
