### ISSUE TITLE
Improved resume support

### ISSUE THREAD

**Issue by dawonn-haval** [OpenDroneMap/WebODM#869]
### What's your browser and operating system? 

Chrome, Ubuntu

### What is the problem?

I ran out of disk space, and want to resume where it left off after making space. 

### What should be the expected behavior?

The ability to 'restart from' is great but I don't know what steps have been completed and where to restart from. I wish there was some way to find out, or for it to figure it out automatically. 

### How can we reproduce this?

Process a large dataset on a small hard disk.

**Comment by KommandorKeen** [comment]
I have just run a few test cases through meshroom.  ODM produces a better result but has a poorer re-start visibility.
I think it comes down to re-structuring the options list so that they are delivered chronologically. I will have alook ate ths.

**Comment by smathermather** [comment]
Love it. And I think to the question above from @dawonn-haval, ODM does it's own check as to what steps still need run. You only need to specify the restart stage if you've changed parameters that would effect a stage that has already run.

**Comment by smathermather** [comment]
But I love restructuring the options list. It's a long and confusing list, and it would be quite helpful to add structure to it.

**Comment by pierotofy** [comment]
Please see if #893 solves this issue by updating and retrying. If the problem is still there, please reopen? :pray:
