### ISSUE TITLE
CCD width missing

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#87]
@pierotofy 

I'm flying the Autel X-Star Premium.  When I process photos through WebODM, I noticed that the CCD width is missing.  How do I retrieve that info to force WebODM to use it or add it to the WebODM list.

Thanks again,
Anthony

![webodm_ccdwidtherror](https://cloud.githubusercontent.com/assets/25381671/22622066/39f9bd8a-eaf7-11e6-990a-6cf0053f7788.JPG)

**Comment by pierotofy** [comment]
You can use the "force-ccd" option from the "Advanced" tab when you upload images to start a new task.

![image](https://cloud.githubusercontent.com/assets/1951843/22622331/737833bc-eb05-11e6-9316-e514092b49e0.png)

![image](https://cloud.githubusercontent.com/assets/1951843/22622334/7ee162c8-eb05-11e6-80eb-59f875fb2fa7.png)

See this link for more information about calculating the CCD width. http://phototour.cs.washington.edu/focal.html

**Comment by AnthonyCoughlin** [comment]
Thanks again.

**Comment by AnthonyCoughlin** [comment]
I believe I've got this one figured out.  Thanks.
