### ISSUE TITLE
Point cloud not displaying (affects Chrome and Edge Dev)

### ISSUE THREAD

**Issue by gjsa73** [OpenDroneMap/WebODM#873]
### What's your browser and operating system?

Chrome 83 on Windows 10

### What is the problem?

Point clouds are not displaying in WebODM:

- The canvas loads but only shows the selected background and any other features (eg Show Cameras, Box).
- No error is generated ([as has been reported previously](https://community.opendronemap.org/t/could-not-load-point-cloud-this-task-doesnt-seem-to-have-one-try-processing-the-task-again/3022)).  The last log entries for the NodeODM task are:

```
90
.
.
.
100
Found point cloud: odm_georeferencing/odm_georeferenced_model.laz
Entwine point cloud is already built.
Postprocessing: done (•̀ᴗ•́)و!
Compressing all.zip
Done!
```

- If I select `Textured Model -> Show Model`, the mesh displays after a reasonable loading time.

### What should be the expected behavior?

Point cloud should display by default

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Do not think this is data specific - have installed WebODM as a Docker instance using the instructions in GitHub and this problem occurs.

If however, I install the native [Windows WebODM](https://webodm.net/static/downloads/WebODM_Setup.exe), and process the same data, the point clouds do display in the canvas.

Typical screenshot of the missing point cloud below:
![image](https://user-images.githubusercontent.com/21994806/83385044-d312e000-a42b-11ea-8b72-7f8a51335497.png)

**Comment by pierotofy** [comment]
Hey @gjsa73 :hand: thanks for the report; if you open press CTRL+SHIFT+J (to open the Developer Toolbar), then navigate to the "Console" tab and refresh the page, do you see any error messages?

**Comment by gjsa73** [comment]
@pierotofy here is a screenshot of the errors after refreshing the page:
![image](https://user-images.githubusercontent.com/21994806/83424462-c4e6b300-a46f-11ea-94ff-bb46c5199747.png)

**Comment by gjsa73** [comment]
Found an issue in potree and tried one of the suggestions successfully:

Does it work when you **disable Eye-Dome-Lighting** and set splat-quality to standard?
**Yes**

_Originally posted by @m-schuetz in https://github.com/potree/potree/issues/541#issuecomment-416225053_

**Comment by pierotofy** [comment]
That could definitely be done; are you familiar with Javascript? If so would you be interested in contributing a pull request? It can probably be done with some changes here https://github.com/OpenDroneMap/WebODM/blob/master/app/static/app/js/ModelView.jsx#L194

**Comment by gjsa73** [comment]
Just updated the title as the problem only affects the latest Chrome and Microsoft Edge.  Firefox v76 displays the point clouds by default with Eye-Dome Lighting enabled.  Will use Firefox

**Comment by trevor-miracad** [comment]
```
initThree()
let context = canvas.getContext('webgl2', contextAttributes );
```

setting the three.js WebGLRenderer to 'webgl2' causes this issue for me when doubleclicking on the pointcloud.  Very similar error:  

```
viewer.js:879 Uncaught could not compile shader pointcloud: WARNING: 0:7: 'GL_EXT_frag_depth' : extension is not supported
ERROR: 0:74: 'gl_FragDepthEXT' : undeclared identifier
ERROR: 0:74: 'assign' : l-value required (can't modify a const)
```

To fix it, ensure  the context is set to "webgl"
Thought I would share my findings - if set, I have a feeling it would fix this error also
