### ISSUE TITLE
Enhancement request:  Zoom on 3D view

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#88]
This may be trivial compared to the other 'Issues', but, is it possible to incorporate zoom into the 3D view of a project?

Thanks in advance,
Anthony

**Comment by pierotofy** [comment]
Currently using your mouse wheel (if you have one) allows you to zoom in/out. What device are you currently using?

**Comment by AnthonyCoughlin** [comment]
Using a laptop.  I've got a mouse with a wheel thanks.
