### ISSUE TITLE
Export maps and elevation models in plain TIFF or JPG

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#886]
Some users want to have the results in plain RGB TIFF, not the RAW GeoTIFF. There should be an option to export DSM/DTM/Ortho/Plant health as plain RGB (JPG or TIFF).

**Comment by pierotofy** [comment]
There's now a fund open to get this done: https://fund.webodm.org/#/fund/4

If this feature is important to you, please consider pledging!

**Comment by W6oody** [comment]
A shame IMHO that this funding did not get over the line. How long until another attempt? Maybe there is more appetite now? The community seems to be growing.

Woody

**Comment by pierotofy** [comment]
We could certainly retry.
