### ISSUE TITLE
Missing documentation for POST /tasks/import endpoint

### ISSUE THREAD

**Issue by RGrze** [OpenDroneMap/WebODM#887]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 78 on Ubuntu Linux

### What should be the expected behavior?

There is no documentation for `[POST] /api/projects/{project id}/tasks/import` endpoint at [WebODM Documentation webpage](https://docs.webodm.org/#task)

It is possible, however, to use this request via `import` button from WebODM dashboard. I'd like to update the documentation, unfortunately I'm not exactly sure what are all parameters available for this endpoint.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

..

**Comment by pierotofy** [comment]
Hey @RGrze :hand: see https://github.com/OpenDroneMap/WebODM/blob/5ad0ccc764016a6f2ba1d29c74c663e9d3e0d882/app/api/tasks.py#L360

Would you be interested in opening a PR for this?

**Comment by RGrze** [comment]
@pierotofy hey, sure, I'm on it :)
