### ISSUE TITLE
Add option to link URLs for image upload

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/WebODM#89]
For example: https://github.com/OpenDroneMap/odm_data_toledo/archive/master.zip

It is just a zip file of images. WebODM would download, unzip, and load those images. There would probably have to be some validation and security concerns to implement as well.

**Comment by pierotofy** [comment]
I'm still debating if this is something that should be included server side, or if this should be implemented by clients (such as the WebODM UI).

It would work fine for simple cases, but I can see more complexity arising later on when we start adding GPCs in the equation, as well as any other data (video one day?). Then you need to start making assumptions about the archives, such as "if there's a GCP file, it should be placed in the root directory, have extension .txt". Or "only images in the root level directory will be considered".

**Comment by pierotofy** [comment]
This is now supported via the cloud import plugin, which include GitHub support.

**Comment by vlad-shevchenko** [comment]
@pierotofy cloud import plugin only works through UI, right? But is there a way to upload images by URL when using API?
