### ISSUE TITLE
Ability to overwrite default settings.

### ISSUE THREAD

**Issue by vesnikos** [OpenDroneMap/WebODM#9]
An ability to overwrite the default settings is usefull in numerous occasions. 

This can be implemented easily by appending :

> try:
>     from .local_settings import *
> except ImportError:
>     pass
> 

ofcourse local_settings.py  should be added in .gitignore as well

**Comment by pierotofy** [comment]
I agree, this should be added. Would you want to take care of this, or should I add it to my TODO list?

**Comment by pierotofy** [comment]
Never mind, I added this as part of #10. Thanks!

**Comment by vesnikos** [comment]
I would suggest to add local_settings.py as well to .gitignore. the file does not have any meaning outside local enviroments

**Comment by pierotofy** [comment]
Already there, see https://github.com/OpenDroneMap/WebODM/blob/master/.gitignore#L54
