### ISSUE TITLE
Entwine + Greyhound Plugin

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#92]
It would be cool to add the ability to link an external entiwine/greyhound server to WebODM so that point cloud results can be automatically added and merged into the index.

**Comment by pierotofy** [comment]
I wonder if an efficient system would be to simply allow users to configure web hooks that would be triggered on certain events (on task completion, on task deletion, on task restart, etc.).

Once you have that, you don't need pooling and a server running entwine / grayhound or openarialmap could simply retrieve/index the assets it needs via API calls.

**Comment by smathermather** [comment]
On a related note, I've been thinking about entwine / greyhound the last few days. FWIW, we are not far away from having the capacity to process datasets large enough that without LOD, streaming, etc. the current viewer won't be able to display the data produced.

**Comment by pierotofy** [comment]
Entwine is now integrated in ODM and WebODM, so this can be closed. Greyhound is no longer needed and datasets can be read with Potree.
