### ISSUE TITLE
Processing Nodes Offline

### ISSUE THREAD

**Issue by abrbhat** [OpenDroneMap/WebODM#923]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 81 on Windows 10

### What is the problem?

Processing Nodes are being shown as offline even though they are available. Even refresh does not change the status.

![image](https://user-images.githubusercontent.com/4189727/96151296-e335e280-0f28-11eb-932e-661144a269eb.png)

Clicking on each node results in showing the correct status.
![image](https://user-images.githubusercontent.com/4189727/96151558-2a23d800-0f29-11eb-9cc1-466081844fcb.png)

### What should be the expected behavior?

Nodes should always display correct status.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Not sure how to replicate.

**Comment by pierotofy** [comment]
The nodes are refreshed every 30 seconds (or as you found out, if you visit the node's page).

So do the nodes come back online after 30 seconds? 

If not, you might have run out of memory and the worker process in charge of refreshing the node statuses has been likely terminated, preventing the refresh to happen.

**Comment by abrbhat** [comment]
How can I observe refreshing of nodes? I think the worker process might have gone down. How to bring it back up?

**Comment by pierotofy** [comment]
Press the "Retry" button when creating a task.

**Comment by abrbhat** [comment]
Shows the same error and the node status is not refreshed.

**Comment by pierotofy** [comment]
> If not, you might have run out of memory and the worker process in charge of refreshing the node statuses has been likely terminated, preventing the refresh to happen.

**Comment by abrbhat** [comment]
Does not look like I'm low on memory. This is diagnostic for the WebODM instance. I'm running ClusterODM and NodeODM on separate instances.
![image](https://user-images.githubusercontent.com/4189727/96490104-febd2800-125d-11eb-8ba4-bb765e5e7d22.png)

**Comment by pierotofy** [comment]
Try:

`./webodm.sh restart`

?

It's possible that the worker gets killed when you process a task.

**Comment by abrbhat** [comment]
Tried this, seems good till now
