### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ParkwayProduction** [OpenDroneMap/WebODM#924]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Google Chrome is up to date
Version 86.0.4240.80 (Official Build) (x86_64)

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4

Software TypeWeb Browser
Hardware TypeComputer
Browser version (full)86.0.4240.80
Operating System version (full)10.15.6
Layout EngineBlink
Configured LanguageEnglish
Device Pixel Ratio2
Browser GMT Offset-04:00
PlatformIntel based Mac

### What is the problem?

I was playing around and found the account section then I deleted unknown since the other one showed my name.
I was uploading pictures, I accidentally closed the browser and restarted the system again.

### What should be the expected behaviour?

I would have expected to be able to log back into it and complete the project.
Since everything runs till I get told by the system when browser opens that password doesn't work.
I reset the password on odm manager setting and still no access on http://localhost:8000/login/

I am confused since I use simplified platforms like drone deploy and etc..now this hick up is bothering me since I have paid for it....Should I re-install everything or is there a solution to my problem?

**Comment by ParkwayProduction** [comment]
Here is additional information


Waiting for WebODM to start...
WebODM is running. Open your browser to http://localhost:8000
Updating WebODM...
From git://github.com/OpenDroneMap/WebODM
 * branch            master     -> FETCH_HEAD
Already up to date.
Stopping webapp            ... 
Stopping worker            ... 
Stopping broker            ... 
Stopping webodm_node-odm_1 ... 
Stopping db                ...
[5A[2K
Stopping webapp            ... [32mdone[0m
[5B
[2A[2K
Stopping webodm_node-odm_1 ... [32mdone[0m
[2B
[4A[2K
Stopping worker            ... [32mdone[0m
[4B
[1A[2K
Stopping db                ... [32mdone[0m
[1B
[3A[2K
Stopping broker            ... [32mdone[0m
[3B
Removing webapp            ... 
Removing worker            ... 
Removing broker            ... 
Removing webodm_node-odm_1 ... 
Removing db                ...
[3A[2K
Removing broker            ... [32mdone[0m
[3B
[1A[2K
Removing db                ... [32mdone[0m
[1B[2A[2K
Removing webodm_node-odm_1 ... [32mdone[0m
[2B
[4A[2K
Removing worker            ... [32mdone[0m
[4B
[5A[2K
Removing webapp            ... [32mdone[0m
[5B
Removing network webodm_default
Pulling node-odm ... 
Pulling db       ... 
Pulling broker   ... 
Pulling worker   ... 
Pulling webapp   ...
[5A[2K
Pulling node-odm ... pulling from opendronemap/nodeodm
[5B
[5A[2K
Pulling node-odm ... digest: sha256:4e0db0f0145b3db9c1...
[5B[5A[2K
Pulling node-odm ... status: image is up to date for o...
[5B[5A[2K
Pulling node-odm ... [32mdone[0m
[5B
[3A[2K
Pulling broker   ... pulling from library/redis
[3B
[2A[2K
Pulling worker   ... pulling from opendronemap/webodm_...
[2B
[2A[2K
Pulling worker   ... digest: sha256:aaeea475b90399d4bd...
[2B[2A[2K
Pulling worker   ... status: image is up to date for o...
[2B[2A[2K
Pulling worker   ... [32mdone[0m
[2B
[4A[2K
Pulling db       ... pulling from opendronemap/webodm_db
[4B
[4A[2K
Pulling db       ... digest: sha256:437e8772fddeb7e740...
[4B[4A[2K
Pulling db       ... status: image is up to date for o...
[4B[4A[2K
Pulling db       ... [32mdone[0m
[4B
[1A[2K
Pulling webapp   ... pulling from opendronemap/webodm_...
[1B[1A[2K
Pulling webapp   ... digest: sha256:aaeea475b90399d4bd...
[1B[1A[2K
Pulling webapp   ... status: image is up to date for o...
[1B
[1A[2K
Pulling webapp   ... [32mdone[0m
[1B
[3A[2K
Pulling broker   ... digest: sha256:33ca074e6019b45123...
[3B[3A[2K
Pulling broker   ... status: image is up to date for r...
[3B
[3A[2K
Pulling broker   ... [32mdone[0m
[3B
WebODM has updated. Press Start to launch WebODM

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by ParkwayProduction** [comment]
thanks
