### ISSUE TITLE
Add options to push to OpenAerialMap / OpenImageryNetwork endpoint 

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/WebODM#93]
We should add option to push to OpenAerialMap / OpenImageryNetwork endpoint

https://github.com/OpenDroneMap/WebODM/issues/92 is a sister issue.

https://openimagerynetwork.github.io/
http://openaerialmap.org/about/

cc @cgiovando

**Comment by pierotofy** [comment]
@smathermather is this still relevant?

**Comment by smathermather** [comment]
For sure. It's still a need, and would be a good throng to add to WebODM as well.

**Comment by pierotofy** [comment]
This has been implemented time ago! Closing. :clinking_glasses:
