### ISSUE TITLE
WebODM task queued / node queue has been stuck for days

### ISSUE THREAD

**Issue by Wex-Woo** [OpenDroneMap/WebODM#936]
Hi all, 

I'm a new user of WebODM and have recently managed to process some RGB images from my drone. 

I'm now trying to process a multispectral (5-band) image dataset from a MicaSense RedEdge-MX sensor and the task has been queued for a week. When I look at the processing node on the web interface, it says that these are 3 queued tasks even though I've already deleted all other tasks on the main dashboard.

![image](https://user-images.githubusercontent.com/71237548/99605985-f3c40600-2a5c-11eb-8d0a-bf04ec4079fc.png)

I've looked through the WebODM forums and Github and tried the following troubleshooting methods:
- killing the docker containers

- removing all other tasks

![image](https://user-images.githubusercontent.com/71237548/99605931-d7c06480-2a5c-11eb-9996-22a041ef2804.png)

Has anyone faced this issue before and how was it resolved?

Thanks in advance

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
