### ISSUE TITLE
Processing got terminated with exception

### ISSUE THREAD

**Issue by abrbhat** [OpenDroneMap/WebODM#948]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Ubuntu 18.04

### What is the problem?

Processing got terminated with exception

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

![image](https://user-images.githubusercontent.com/4189727/103351491-74990780-4ac9-11eb-94b2-955628907b1e.png)

Log: [console.txt](https://github.com/OpenDroneMap/WebODM/files/5754195/console.txt)

**Comment by pierotofy** [comment]
You ran out of memory (just like WebODM said in the message below the console output).

For other and future questions, let's move the conversation to the forum. :pray:
