### ISSUE TITLE
Task options - alphabetical order or grouping by section?

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/WebODM#950]
### What's your browser and operating system? 

Firefox 83 on Ubuntu Linux

### What is the problem?

In the "Edit task options" dialog (? menu? pop-up?) I see myself scrolling up and down for the options, but what if they were sorted alphabetically? Wouldn't it be easier to find them? Or maybe grouping the options by "sections" such as "SfM", "point cloud" etc.

Just a thought

**Comment by pierotofy** [comment]
They already are since https://github.com/OpenDroneMap/WebODM/pull/943 was merged.

Are you running 1.7.0?

**Comment by CarlosGrohmann** [comment]
Turns out I wasn't... sorry.

**Comment by pierotofy** [comment]
No worries! I'll close this.
