### ISSUE TITLE
DEM/Orthophoto - fine details missing when compared to Metashape

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/WebODM#951]
### What's your browser and operating system? 

Firefox 82 on macOS (Mojave)

### What is the problem?

I'm running WebODM and Metashape on a landslide dataset to check for similarities/differences. I don't have GCPs for this dataset.

In Metashape, I used the "high" option for sparse and dense clouds. The DEM has 6cm/px resolution and the orthophoto, 3cm/px (automatically calculated)

In ODM, I used the "ultra" option for `pc-quality`, `feature-quality`, and set the DEM resolution to 5cm and 3cm for the ortophoto.

At a first glance, the DEM and the orthophoto produced by ODM seem OK, but when zooming in, I can see that the ones produced by Metashape have more fine detail. The shaded relief of the ODM DEM is quite noisy and there are visible seams:

#### Orthophotos
Metashape
![ams_ortho_zoom0](https://user-images.githubusercontent.com/1870265/103905703-b7686a00-50dd-11eb-9b8a-bac7c64a3852.jpg)  

ODM
![odm_ortho_zoom0](https://user-images.githubusercontent.com/1870265/103905751-c222ff00-50dd-11eb-874f-66324cbbd6fc.jpg)  

Metashape
![ams_ortho_zoom1](https://user-images.githubusercontent.com/1870265/103905726-bdf6e180-50dd-11eb-90f5-8de4a9752c83.jpg)  

ODM
![odm_ortho_zoom1](https://user-images.githubusercontent.com/1870265/103905753-c2bb9580-50dd-11eb-8970-bb281327b809.jpg)  

Metashape
![ams_ortho_zoom2](https://user-images.githubusercontent.com/1870265/103905733-bf280e80-50dd-11eb-9e4a-4a63a1501e68.jpg)  

ODM
![odm_ortho_zoom2](https://user-images.githubusercontent.com/1870265/103905757-c3ecc280-50dd-11eb-86ce-cf17056362fb.jpg)  

#### Shaded reliefs
Metashape
![ams_shade_zoom0](https://user-images.githubusercontent.com/1870265/103905740-bfc0a500-50dd-11eb-925d-0847f8e46876.jpg)  

ODM
![odm_shade_zoom0](https://user-images.githubusercontent.com/1870265/103905759-c3ecc280-50dd-11eb-9a61-c5ad7ffac408.jpg)  

Metashape
![ams_shade_zoom1](https://user-images.githubusercontent.com/1870265/103905744-c0593b80-50dd-11eb-852a-44635d975243.jpg)  

ODM
![odm_shade_zoom1](https://user-images.githubusercontent.com/1870265/103905762-c4855900-50dd-11eb-881d-1e9d3fdb1762.jpg)  

Metashape
![ams_shade_zoom2](https://user-images.githubusercontent.com/1870265/103905748-c18a6880-50dd-11eb-8222-4a21e53d641d.jpg)  

ODM
![odm_shade_zoom2](https://user-images.githubusercontent.com/1870265/103905764-c51def80-50dd-11eb-9544-8b84f416e748.jpg)  

### What should be the expected behavior?

I would love to replace Metashape with ODM in my research. Just need help tuning the parameters maybe?

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

The dataset can be accessed [here](https://www.dropbox.com/s/h44ztyp72nskgs0/landslide_cgrohmann.zip?dl=0). Just note that this is part of unpublished research, so please keep it to yourself and contact me if you would like to use it for any publication.

The processing report from Metashape is [here](https://www.dropbox.com/s/fjc290awru4u1bq/landslide_report.pdf?dl=0). 

ODM processin options:
`resize-to: -1, rerun-from: opensfm, min-num-features: 8000, feature-quality: ultra, matcher-neighbors: 8, depthmap-resolution: 1000, opensfm-depthmap-method: BRUTE_FORCE, skip-3dmodel: true, ignore-gsd: true, mesh-size: 600000, mesh-octree-depth: 12, pc-quality: ultra, pc-las: true, pc-filter: 0, texturing-outlier-removal-type: gauss_damping, texturing-tone-mapping: gamma, dsm: true, dem-resolution: 5, orthophoto-resolution: 3, gps-accuracy: 5, optimize-disk-space: true`

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by OKaluza** [comment]
Just adding a link to the discussion for anyone finding this https://community.opendronemap.org/t/dem-orthophoto-fine-details-missing-when-compared-to-metashape/6401

**Comment by smathermather** [comment]
Super useful. Thanks for adding that link.
