### ISSUE TITLE
Occasional Python 'ConnectionResetError' while remotely accessed WebODM processes task

### ISSUE THREAD

**Issue by uydtm** [OpenDroneMap/WebODM#969]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 86 on Windows 10

### What is the problem?

I followed [this](https://docs.webodm.org/#how-to-process-images) tutorial to access WebODM remotely via Python (upload images, start tasks and download the resulting orthophotos). With a few tweaks I managed to get it running and - for the most part - it works. Occasionally however, Python stops while WebODM is processing a task and returns the following error:

```Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "...\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "...\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "...\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "...\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

Although Python stops, the task still continues and finishes successfully in WebODM. This seems to happen at random. The exact same code, uploading identical images with unvaried options, ran successfully at one time and failed at another. 

### What should be the expected behavior?

Python should not stop inexplicably sometimes while a task is successfully running in WebODM.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

- As stated above, the error is quite difficult to reproduce because it seems to happen at random. I have noticed though that it always occurs if the Python code is run in the Console and a previous run is not exited it before a new one is started. However, the error does also occur when this is not the case.
- I started using WebODM and remote accessing it via Python yesterday. Yesterday, the error message only occurred in the manner described before (running in Python Console). Only today (after reopening WebODM via Git Bash for the second time) has this new problem become an issue. However, as already mentioned, WebODM still works perfectly fine on its own.
- I have run tasks both successfully and unsuccessfully using different options and amounts of images. The latest set of options to promt an error message were the following:
  - camera-lens: brown, depthmap-resolution: 800, force-gps: true, gps-accuracy: 1, mesh-octree-depth: 12, orthophoto-compression: NONE, orthophoto-png: true, orthophoto-resolution: 0.05, skip-3dmodel: true, texturing-outlier-removal-type: none, use-3dmesh: true
   - amount of images: 200 (this is a comparatively large amount. I usually use 10 images and errors have occurred with so few as well)
- Here are screenshots of my python code so the changes I made to the tutorial linked above can be viewed. I wasn't able to share the file itself because the .py format apparently isn't supported. Seeing as these changes were necessary to get the code to work at all and the code has run successfully, I doubt the issue lies with the code itself.

![pythoncode1](https://user-images.githubusercontent.com/75898040/111821936-811c4780-88e3-11eb-89f9-544f7a20bd71.PNG)
![pythoncode2](https://user-images.githubusercontent.com/75898040/111821938-81b4de00-88e3-11eb-9512-16868da7ce1b.PNG)
![pythoncode3](https://user-images.githubusercontent.com/75898040/111821940-824d7480-88e3-11eb-9f99-da171e0efa86.PNG)

- Here are screenshots of the resulting error message (the parts written in German simply translate to "An existing connection was forcibly closed by the remote host").

![python_errormessage1](https://user-images.githubusercontent.com/75898040/111821980-8e393680-88e3-11eb-9b5d-c3da625084bd.PNG)
![python_errormessage2](https://user-images.githubusercontent.com/75898040/111821983-8e393680-88e3-11eb-8dc6-6ee74117d2c3.PNG)
![python_errormessage3](https://user-images.githubusercontent.com/75898040/111821986-8ed1cd00-88e3-11eb-91dd-04051de6f348.PNG)

- I've been using thermal images recorded by a FLIR Duo Pro camera mounted on a UAV. Regretfully I am not allowed to share any of them.

Thanks in advance for any help with this issue. WebODM is a truly remarkable and very useful application and I'm extremely grateful something of this magnitude has been made available to all for free!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

(It doesn't seem a bug in WebODM per-se, as much as it could be a problem or resource usage, network connections, timeouts...)
