### ISSUE TITLE
Feature request: send email alert on processes exit codes

### ISSUE THREAD

**Issue by niubii** [OpenDroneMap/WebODM#979]
I propose a new feature. 

I'd like to receive an email alert from WebODM when processes ends with some errorcodes.
This is because very often WebODM is running on different computer.
Hope this could be implemented as soon as possible.

Thank you in advantage.

Francesco AKA /niubii/

**Comment by pierotofy** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue providing **all** required information.
