### ISSUE TITLE
Export Surface Model as GeoTiff is not working

### ISSUE THREAD

**Issue by SCFred28** [OpenDroneMap/WebODM#981]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Tested with 2 browser and same problem:
https://whatismybrowser.com/w/KEZ6DHQ
https://whatismybrowser.com/w/NFXFSBA

### What is the problem?

Export Surface Model as GeoTiff is not working. The exported GeoTiff is completely white image and the contour is good.

### What should be the expected behavior?

Export a GeoTiff that represent to one in the web odm user interface

### How can we reproduce this?

1- Select the "Surface Model"
2- Open Layers Tool
3- Click on "Export: GeoTiff"

![image](https://user-images.githubusercontent.com/83292330/116257438-0d6f2500-a742-11eb-877f-77a4023753e9.png)

4- Open the file

![image](https://user-images.githubusercontent.com/83292330/116258134-ac941c80-a742-11eb-85fe-7d361170abbc.png)

**Comment by pierotofy** [comment]
Hey @SCFred28 :hand: you need to use a program such as QGIS to open GeoTIFFs. The built-in image viewer in Windows will not do. https://qgis.org

If you have other questions, let's move the conversation over to https://community.opendronemap.org
