### ISSUE TITLE
The Height Measurement tool not working in Chrome

### ISSUE THREAD

**Issue by SCFred28** [OpenDroneMap/WebODM#982]
### What's your browser and operating system?

Tested with this browser:
https://whatismybrowser.com/w/KEZ6DHQ

And no issue with Firefox

### What is the problem?

The Height Measurement tool not working in Chrome

### What should be the expected behavior?

Be able to set 2 measurement points and get the height

### How can we reproduce this? 

With Chrome
1- Go to the 3D View;
2- Select the Height measurement tool;
3- Place the first point
4- But not able to place the second point.

![image](https://user-images.githubusercontent.com/83292330/116259714-0b0dca80-a744-11eb-8e03-8246dc98f278.png)

**Comment by chemlabros** [comment]
For anyone stuck in an older version (like 1.7) just update. 
Or simply drag the first point you placed (it's the red dot behind the annottation saying 0.00m) and you will get the measurement line.
