### ISSUE TITLE
Error Invalid HTTP_HOST header:

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/WebODM#99]
I've recently cloned and updated webodm to run the newest version.  Now receiving this error when opening the browser.  I'm using windows 10.

Thanks for the help.

![webodm_hosterror](https://cloud.githubusercontent.com/assets/25381671/22854401/79b48fae-f033-11e6-8b90-fae5ebefaa8a.JPG)

**Comment by pierotofy** [comment]
Hi @AnthonyCoughlin thanks for reporting the problem!

This error was introduced from the Django core update. Nice catch!

I have made some changes to settings.py by adding a value of '*' in the ALLOWED_HOSTS variable. This should fix the error you are experiencing.

**Comment by AnthonyCoughlin** [comment]
That's what I read earlier, something like `ALLOWED_HOSTS = ['*']` should allow all hosts.  Thanks for the quick response @pierotofy.

Running `./webodm.sh update` and will attempt to restart WebODM, then let you know the result.

**Comment by AnthonyCoughlin** [comment]
Up and running!  Thanks again for the fast response @pierotofy
